### PR TITLE
Add cadence data to `recorder` app

### PR DESCRIPTION
**Pull request by Mineinjava**
Hi
This is my first contribution to this repository. If there is anything I missed, please let me know.
This PR adds cadence data to the GPX output file

### CODE REVIEW

**Comment by bobrippling** [comment]
Great first contribution :) Let us know when you're happy with the remaining items on your list and we can re-review

**Comment by gfwilliams** [comment]
Thanks! I guess my only concern with this is the CSV file already stores steps and time, so it should be easy to work Cadence out from what's in the stored CSV data already - basically just looking at the difference between the last timestamp and this one and doing `steps * 60000 / timeDifference`?

So we could just have the changes you made to `apps/recorder/interface.html`, but with a bit of extra code in there to work out the Cadence at the time the file was read back?

**Comment by Mineinjava** [comment]
> Thanks! I guess my only concern with this is the CSV file already stores steps and time, so it should be easy to work Cadence out from what's in the stored CSV data already - basically just looking at the difference between the last timestamp and this one and doing `steps * 60000 / timeDifference`?
> 
> So we could just have the changes you made to `apps/recorder/interface.html`, but with a bit of extra code in there to work out the Cadence at the time the file was read back?

That sounds like a better solution. I will revert and reimplement. Thanks

**Comment by Mineinjava** [comment]
oops didn't mean to close it

**Comment by Mineinjava** [comment]
reopening

**Comment by Mineinjava** [comment]
It appears that `pt.Time.getUTCMilliseconds()` returns zero.

**Comment by Mineinjava** [comment]
I got the cadence log in the gpx output to work. However, it appears that Strava doubles the cadence value. This is probably because gpx cadence for bikes is rotations/min whereas for running it is steps/min, and two steps is one cycle.

Source: [Garmin GPX schema](https://www8.garmin.com/xmlschemas/TrackPointExtensionv1.xsd):
```xml
<xsd:element name="cad" type="RevolutionsPerMinute_t" minOccurs="0"/>
```

I believe the standard is one revolution is two steps (one step per foot)

I will update the source code to divide by two as that appears to be the standard. I don't believe this will cause a problem on bicycles because step count while cycling is irrelevant.

**Comment by thyttan** [comment]
Off topic:

Hi! Once you're done with this would you be interested in working on gpx-stuff in Gadgetbridge for implementing the 'Activity Tracks' feature for Bangle.js?

https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3153#issuecomment-1314419

**Comment by gfwilliams** [comment]
This looks great - thanks for your work! 

Are you happy to merge this now? I know there are some items in the original PR note you haven't marked complete but even so the changes here seem useful

**Comment by Mineinjava** [comment]
> Off topic:
> 
> Hi! Once you're done with this would you be interested in working on gpx-stuff in Gadgetbridge for implementing the 'Activity Tracks' feature for Bangle.js?

Sorry, I don't use gadgetbridge (I have an iphone) and I'm not sure I understand what that feature is.

**Comment by thyttan** [comment]
Ah! Thanks anyways then 😉

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
