### PR TITLE
Settings: Move LCD Brightness settings to LCD menu

### PR DESCRIPTION
**Pull request by myxor**
- Move LCD Brightness settings to LCD menu to have all LCD settings on one place
- Renamed LCD Wake Up menu to "LCD menu"
- Unified "Wake On" strings to "Wake on"

### CODE REVIEW

**Comment by myxor** [comment]
Some changes are the same as in https://github.com/espruino/BangleApps/pull/283

**Comment by Purple-Tentacle** [comment]
What about the LCD timeout?
Shouldn't this be moved to the LCD menu as well?

**Comment by myxor** [comment]
LCD timeout menu is already under previously called "LCD  Wake up", now "LCD" menu.

**Comment by gfwilliams** [comment]
Thanks! This looks like a great idea.

**Pull request merged**
