### PR TITLE
NOS Teletekst app

### PR DESCRIPTION
**Pull request by avandermeer**
https://avandermeer.github.io/BangleApps/index.html?id=nostt

I created a teletext app based on the api of the Dutch Broadcast Foundation (NOS).

### CODE REVIEW

**Comment by bobrippling** [comment]
Nice! I've enabled the CI check, would you mind tweaking `metadata.json` for the warning that's appeared?

Also, I notice you've got a few `// @ts-ignore` entries - is renaming the app to a `.ts` file to enable typescript something you'd be interested in? Happy to merge as-is though

**Comment by avandermeer** [comment]
> Nice! I've enabled the CI check, would you mind tweaking `metadata.json` for the warning that's appeared?
> 
> Also, I notice you've got a few `// @ts-ignore` entries - is renaming the app to a `.ts` file to enable typescript something you'd be interested in? Happy to merge as-is though

thanks! I remove the src entry from metadata.json. 

Regarding the @ts-igore comments - that was legacy. I previously build this app in typescript. It worked well, but the  javascript output was unreadable for humans; I figured that it would be useful to have a readable javascript file in this repo, so I reverted back to vanilla javascript.

**Comment by bobrippling** [comment]
Cool, no worries - thanks for the changes!

The typescript in the repo should generate readable JS, but we can leave this for now. If you are interested I can talk you through it, if you didn't go down that route before

**Comment by avandermeer** [comment]
Ah, I was not aware of the typescript options in this repo, will look into it.

Anyway, thanks!

**Pull request merged**
