### PR TITLE
G-Meter

### PR DESCRIPTION
**Pull request by motorfiets**
Simple wrist G-Meter added.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi! I think because you maybe submitted a PR off the 'master' of GitHub, this PR now has a bunch of extra stuff in it - like avigps/gpsnav_aviation/etc.

Is it just gmeter you wanted to submit? If so I can manually copy the files

**Comment by motorfiets** [comment]
Hey yes sorry, started working on other files as well. I can send you the
gmeter folder and .json file via email?

**Comment by gfwilliams** [comment]
No worries - I'll pull them out of the PR

**Comment by motorfiets** [comment]
Thanks!

**Comment by gfwilliams** [comment]
Thanks! Just merged -  made a few tweaks to make this work nicely with the app loader too (there are a few files you didn't need).

**Pull request closed without merging**
