### PR TITLE
widget hand wash timer

### PR DESCRIPTION
**Pull request by MaBecker**
Inaktive:

IMG_9979

Active:

IMG_9980

Please  let me know if the widget function is clearly described  - Thanks.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Very cool, thanks - that's really nice and tidy.

In terms of description `Any swip will start`, I think we'd normally say `swipe`. But maybe `Swipe on the screen to...`

From a purely practical point of view though, you've just swiped your watch screen with a dirty hand. Maybe saying something explicit like `Swipe your wrist over the watch face`?

**Comment by MaBecker** [comment]
Thanks, so let me update that.

Can Bangle.setOptions() disable event twist or should there be a flag isWashing to ignore further twist events?

**Comment by gfwilliams** [comment]
> Can Bangle.setOptions() disable event twist 

You mean twist to turn on? It can.. but does it matter if Bangle.js turns on while hands are being washed?

**Comment by MaBecker** [comment]
It is just about another event during washing and drying.

**Comment by MaBecker** [comment]
>If it now responds to just twisting, doesn't just twisting your wrist to see the time cause the timer to come on?
 
Wow, now it's getting tricky, any suggestion how to avoid that?

**Comment by gfwilliams** [comment]
Well, swipe works ok? You don't have to swipe with a finger, you can swipe your wrist over the watch face (that's what I meant originally)

**Comment by MaBecker** [comment]
Ok, got you wrong, yes swipe works, even swiping with the wrist.

**Comment by MaBecker** [comment]
I would say, good to go

**Comment by gfwilliams** [comment]
Thanks :)

**Pull request merged**
