### PR TITLE
Gadgetbridge: move config to settings menu

### PR DESCRIPTION
**Pull request by rigrig**
Not happy about having to leave `{"name":"gbridge.app.js"},` under `apps.json` `storage`, but otherwise its left behind when updating...

### CODE REVIEW

**Comment by rigrig** [comment]
Travis isn't happy about it either :-(
```
> node bin/sanitycheck.js

ERROR: App gbridge file gbridge.app.js has no contents
```

**Comment by gfwilliams** [comment]
I think it's still referenced at `{"name":"gbridge.app.js"},` in `apps.json`? If you take that out it'll be ok?

**Comment by gfwilliams** [comment]
Ok, just spotted the top comment. I still think it should be removed.

Your https://github.com/espruino/BangleApps/issues/216 should fix it though?

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
