### PR TITLE
Move minify setting into expandable area, and warn

### PR DESCRIPTION
**Pull request by bobrippling**
This moves the minify option to an expandable advanced section, and changes the warning ("may" -> "will"). See #2562 for more details.

Deployed to my [gh pages](https://bobrippling.github.io/BangleApps/) if you want a preview.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Looks good, but maybe you could move the 'translations' setting above the 'Advanced Options'? it's a bit odd having it in the middle.

Also, I really appreciate the link for testing - it makes life so much easier!

**Comment by bobrippling** [comment]
Yeah that looks much nicer - [gh pages](https://bobrippling.github.io/BangleApps/) updated too if you wanted to re-check (maybe a bit of a gap (`<br>`?) between "advanced options" and the "default settings" button?)

**Comment by gfwilliams** [comment]
Looks great, thanks! Actually I think I'll move the 'Default Settings' button into 'Advanced' then it's less likely to get accidentally clicked!

**Comment by bobrippling** [comment]
Ah nice idea, and thanks for merging!

**Pull request merged**
