### PR TITLE
[alarm] Fix redrawing entry inside its submenu

### PR DESCRIPTION
**Pull request by storm64**
1. Fix redrawing selected Alarm/Timer entry inside its edit submenu through opening the menu after a short timeout.
2. Apply redrawing fix to dow submenu, too.
3. Removing the obsolete check-mark images.
4. Removing format on boolean values to use new check-marks.

---

5. Missed to ignore the _.gitignore_ file, should I remove the entry or can it stay?

### CODE REVIEW

**Comment by alessandrococco** [comment]
About 1 and 2: Could you explain the issue? Every submenu should be called throught the setTimeout?

About 3 and 4: see Gordon's comments in #1750.

**Comment by storm64** [comment]
1+2) On all menu entries displaying a value at the right-hand side (all except the entries with an >), the entry is redrawn after `onchange` is called to display the possibly changed value. See more: espruino/Espruino#2149

3+4) I see, will revert this changes asap.

**Comment by nxdefiant** [comment]
If I may hijack this: Currently there seems to be no way to exit the vibration pattern menu, do you have an eye on this?

**Comment by storm64** [comment]
> If I may hijack this: Currently there seems to be no way to exit the vibration pattern menu, do you have an eye on this?

This is handled inside [modules/buzz_menu.js](https://github.com/espruino/BangleApps/blob/master/modules/buzz_menu.js), will add a separate PR for this.

**Comment by nxdefiant** [comment]
+1

**Comment by gfwilliams** [comment]
So is this fixing an issue on Bangle.js 1 or 2?

And is it still an issue on recent firmwares? I haven't seen any problems, but I seem to recall that on some old firmwares we used the `rising` edge of button presses rather than `falling` and I can see that could cause issues.

**Comment by storm64** [comment]
> So is this fixing an issue on Bangle.js 1 or 2?

Bangle.js 2

>And is it still an issue on recent firmwares? I haven't seen any problems, but I seem to recall that on some old firmwares we used the rising edge of button presses rather than falling and I can see that could cause issues.

The problem occurred on fw 2v13.15 and I remembered this issue espruino/Espruino#2149.

**Comment by gfwilliams** [comment]
Thanks for the explanation. I'm really surprised I didn't hit this during testing - I wonder why not...

**Comment by storm64** [comment]
> If I may hijack this: Currently there seems to be no way to exit the vibration pattern menu, do you have an eye on this?

@nxdefiant: Fix is merged: espruino/Espruino#2188

**Pull request merged**
