### PR TITLE
chargent: allow a tap on the notification to silence it

### PR DESCRIPTION
**Pull request by bobrippling**
This allows a user to silence the buzz/notification once seen

### CODE REVIEW

**Comment by bobrippling** [comment]
@thyttan would you be ok with me merging this? (or ok to merge it?)

**Comment by thyttan** [comment]
Don't know if it's this PR or something else, but I just installed v0.06 on my watch and attached the charging cable. Started on ~60% went past both 80% and 90% without signaling. fw 2v21.51.

**Comment by bobrippling** [comment]
Interesting, I'll take a look

**Comment by thyttan** [comment]
I'll try again as well when the battery has come down, and connect with the web ide to look for errors.

**Comment by thyttan** [comment]
I tried again but with v0.05 from standard dev app loader, also no reaction going from 75% to 85% (fw 2v21.53). So maybe something particular is up with my setup. Does it work for you?

**Comment by thyttan** [comment]
And now I've tried v0.05 after a factory reset on fw 2v21.53 - still no reaction on my watch.

**Comment by bobrippling** [comment]
That's strange, I see the notification when I charge mine ok, I wonder - do you see it if you allow your watch to sit at full charge for 5 mins?

**Comment by thyttan** [comment]
Then I think go ahead with merging 👍 

Do you want me to do it?

As for my watch, I'll try you suggestion 🙂

**Comment by bobrippling** [comment]
Thanks! Yeah let's see if we get more reports and I'll keep my eye on it, let me know if you still see issues and we can debug, even if it's an unrelated problem :)

**Comment by thyttan** [comment]
Charged to 25% -> 100% today without noticing warning buzzes. I wasn't around it for the whole duration. When I got back it said 'Fully charged' over the widget field, some of the text went past the screen edge. The only way I got it to disappear was doing a regular `load()` with the hw button long press.

**Comment by bobrippling** [comment]
Thanks, sounds like there's a bug - I'll see if I've any odd local config that might be interfering. I also see the notification part-way off the screen, which I'll sort a fix for

**Comment by thyttan** [comment]
I think I didn't.test without fastload utils - maybe that's the culprit?

**Comment by bobrippling** [comment]
Yes I suspect so - I've seen similar issues / possibly watch hangs when charging, need to investigate still though

**Comment by bobrippling** [comment]
Cracked it - #3386

**Pull request merged**
