### PR TITLE
recorder: don't prompt the user when the columns change - force new file

### LINKED ISSUE #3081: [Recorder] Appending with different sensors causes data in wrong columns
### Affected hardware version

Bangle 2

### Your firmware version

2v19

### The bug

When recording anything and deciding after a while that you don't want to log a sensor anymore (eg to save battery) the resulting csv (downloaded from the app-store) shifts data to wrong columns (eg the charging column contains the altitude).

### Steps to reproduce:
* Start recording with HR, battery, steps and barometer
* Wait for a few datapoints
* Stop recording
* Deselect Battery Log
* Start recording and append to old file
* Wait for a few datapoints
* Stop recording and look into csv to see the bug

Note: This also has the consequence, that when logging GPS before and after appending and exporting the gpx and ignoring datapoints without GPS, many entries without GPS are generated (because GPS is stored as another value).

### Installed apps

openstmap (0.25)
widid (0.03)
antonclk (0.11)
wid_a_battery_widget (0.04)
bthrm (0.17)
widlock (0.08)
agpsdata (0.06)
widmessages (0.05)
messageicons (0.05)
widbt (0.09)
lightswitch (0.09)
android (0.32)
iconlaunch (0.19)
messagegui (0.74)
notify (0.13)
messages (0.62)
boot (0.59)
antonclkplus (0.10)
locale (0.17)
gbridge (0.27)
hrm (0.11)
health (0.27)
recorder (0.32)
setting (0.65)

### PR DESCRIPTION
**Pull request by bobrippling**
Resolves a small issue with #3081, see [commit comments](https://github.com/espruino/BangleApps/commit/dd96e33774bee9c0ce0aea9ffe336ce18a0d631c#r132592068) for more detail

Closes #3081

### CODE REVIEW

**Comment by thyttan** [comment]
Just tried, it works for me :+1:  

Thanks!

**Comment by bobrippling** [comment]
Great, thanks for checking - I'll not merge my own PRs, if you would mind doing the honours? We could leave it for a little while if you wanted to test more, of course.

r.e. fastload utils, is that because `recorder` doesn't use `setUI` / install a `remove` handler?

**Comment by thyttan** [comment]
Ah, I'll merge it now. Thanks again :)

> r.e. fastload utils, is that because recorder doesn't use setUI / install a remove handler?

I don't think there's any change there, and it's not fastload behavior that's the problem. It's when selecting to start recording that the app rectangle just goes blank. This is outputted to the web ide:
```
>
{"t":"status","bat":76,"chg":1}
Uncaught Error: Cannot read property 'forEach' of undefined
 at line 1 col 2805 in recorder.wid.js
...Recorders();settings.record.forEach(r=>{var recorder=recorders[r...
                                  ^
in function "getActiveRecorders" called from line 1 col 4959 in recorder.wid.js
...Headers(getActiveRecorders()).join(",")){options.force="new"...
                              ^
in function "setRecording" called from line 11 col 368 in recorder.app.js
...["recorder"].setRecording(v).then(function(){loadSettings();showMai...
                                     ^
in function called from system
> 
```

**Comment by bobrippling** [comment]
Thanks! And yeah I see, if you check your watch's filesystem, does `recorder.json` either not exist, or if it does, does the JSON within it omit a `record` property? If so - I have a fix: #3100

**Pull request merged**
