### PR TITLE
health/interace: Replace moving average for bpm with avg

### PR DESCRIPTION
**Pull request by nxdefiant**
Fixes also average bpm on 0 value

When hrm interval in health is off bpm data is only available when another app activates the heart rate monitor, for all other records bpm value is 0.

### CODE REVIEW

**Comment by bobrippling** [comment]
Nice spot!

@gfwilliams @thyttan thought I'd ask for a second review with this being a core app (for my part, I can't think of any potential problems and if anything @nxdefiant's fix is a very good-to-have bugfix)

**Comment by nxdefiant** [comment]
After sleeping a night about this I will probably change the moving average to average. Just checked the app and [it seem to use an average.](https://github.com/espruino/BangleApps/blob/master/apps/health/app.js#L79)

**Comment by nxdefiant** [comment]
replaced moving avg with avg

**Comment by gfwilliams** [comment]
This looks great, thanks! Yes, that really would have knocked off any bpm readings.

I guess I probably never noticed since when testing I'd turned the heart rate sensor on in the settings

**Pull request merged**
