### PR TITLE
sched: permit buzz count to be infinite

### PR DESCRIPTION
**Pull request by bobrippling**
... so an alarm will buzz until it is stopped by the user.

Also updated `sched`'s readme to align it with the latest code.

### CODE REVIEW

**Comment by bobrippling** [comment]
@thyttan does this look ok to merge?

**Comment by thyttan** [comment]
Currently trying it on my watch.

- The main functionality of forever buzzing seems to work.
- Snoozing seems to work.
- I can't change the `Buzz count` settings from `null` - the sub-menu will not be displayed.
-  (also, instead of a user facing ´null´ I think it should say something else? could we achieve a `∞` infinity sign?)

image

(I have fastload utils installed)

**Comment by bobrippling** [comment]
Great spot, thank you - I believe 6aa0b8d will fix that (and display the count as "Forever")

**Comment by thyttan** [comment]
That fixed it for me - nice!

I think this is one of the apps/libs @gfwilliams should see the PR before we merge - so I'll not merge now.

**Comment by bobrippling** [comment]
Sounds good, thanks for the checks!

**Comment by gfwilliams** [comment]
Yes, this all looks good to me - thanks!

**Comment by bobrippling** [comment]
Thanks both!

**Pull request merged**
