### PR TITLE
drained: make it clear when charging, via the clock

### PR DESCRIPTION
**Pull request by bobrippling**

### CODE REVIEW

**Comment by pavelmachek** [comment]
Would it make sense to add text "charging" somewhere on screen, too? People are not going to see the app too often, and may not know why the clock is now yellow...

**Comment by bobrippling** [comment]
Sounds good, let me know what you think

**Comment by pavelmachek** [comment]
Thank you, looks good to me.

**Comment by bobrippling** [comment]
Great, thanks for the review

**Pull request merged**
