### PR TITLE
kbmulti: reset caps when empty and add vibrate setting

### PR DESCRIPTION
**Pull request by bobrippling**
This turns caps back on if we clear the input (to match the initial state) and adds a setting to vibrate on interaction

### CODE REVIEW

**Comment by thyttan** [comment]
Nice additions!

What do you think of the situation when
1. no character written
2. user toggles to lower case
3. user does a backspace swipe

?

Should it reset to upper case? Now the lower case is preserved.

**Comment by bobrippling** [comment]
Thank you :)

So that shouldn't happen, because we only perform the upper casing if we've been able to delete a character (line 79), I can't get it to happen on my watch, do you see it?

https://github.com/espruino/BangleApps/blob/d6483983061bc998632d9e690ff1ba110e3c3f52/apps/kbmulti/lib.js#L77-L83

**Comment by thyttan** [comment]
No, sorry for being unclear. It doesn't reset for me either. I was thinking that it could be a little confusing maybe that it didn't restore upper case in that situation. But I don't know really 🤷‍♂️

**Comment by thyttan** [comment]
Happy to merge if you are!

**Comment by thyttan** [comment]
OK thanks!

**Comment by bobrippling** [comment]
Thanks for the review + merge!

**Pull request merged**
