### PR TITLE
Recorder: add clockinfo

### PR DESCRIPTION
**Pull request by bobrippling**
This introduces a clockinfo for the recorder, to allow quick toggling of recording state.

Currently the pause icon is white (for a dark background) - I use `drawImage({ ..., palette })` to alter this based on the `g.theme`, but I'd like the icon to highlight when the clock info is selected, like the step icon.

I can't see how the step icon does it though - it's a [fixed image](https://github.com/espruino/BangleApps/blob/8980be400c6a67809d545ca18a2cb021a23221ce/apps/clock_info/lib.js#L81-L81), which apps then draw just by passing to `g.drawImage()` - does it work by something like the icon is 1-bit and so `drawImage` uses the background or foreground colour as its palette?

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great idea, thanks!

Does `Recorder` really need its own category though given it only has one icon? Maybe it's better just as a member of `Bangle`.

Also, maybe if there is no widget (eg the clock face isn't loading widgets) we should just not create a clockinfo at all? I think `return { name: "Bangle", items: [] }` should do it. Currently if there is no widget it'll return `Paused` but I think if it's tapped on, it'll cause an exception. The whole recorder widget isn't great, a library would be better - but it's a bit of a hangover from how things used to be done.

> I'd like the icon to highlight when the clock info is selected, like the step icon.

You need to make sure you create a 1bpp icon, ideally transparent, with white as the color of the icon itself. I think most clocks expect 24x24px too - that's what we do for other clockinfos and it should work fine... If there's any trouble post the image up and I can do it here

**Comment by bobrippling** [comment]
> Does `Recorder` really need its own category though given it only has one icon? Maybe it's better just as a member of `Bangle`.
>
> Also, maybe if there is no widget (eg the clock face isn't loading widgets) we should just not create a clockinfo at all? I think `return { name: "Bangle", items: [] }` should do it. Currently if there is no widget it'll return `Paused` but I think if it's tapped on, it'll cause an exception. The whole recorder widget isn't great, a library would be better - but it's a bit of a hangover from how things used to be done.

Ah yes, it's much nicer like that, and likewise with handling a missing widget - thanks!

> a 1bpp icon, ideally transparent, with white as the color of the icon itself. I think most clocks expect 24x24px too - that's what we do for other clockinfos and it should work fine... If there's any trouble post the image up and I can do it here

Thanks - I believe I have it sorted but can't test on my watch - unable to write and I'm holding off resetting it in case you'd like to debug into the [`FW addr fail` error](https://github.com/espruino/BangleApps/issues/2865#issuecomment-1648495597)

**Comment by gfwilliams** [comment]
Thanks - let's wait until you can test nicely then - thanks for the help debugging storage

**Comment by bobrippling** [comment]
The 1-bit image did the trick, thanks again! I've made a small tweak to `clock_info` too, which helped debug a load issue (`WIDGETS` not being defined), happy to move to another PR if desired.

----

There's one problem: if a clock loads `clock_info` before it does `Bangle.loadWidgets()`, the user will never see the recorder clock info because [`WIDGETS` doesn't exist](https://github.com/espruino/BangleApps/blob/8a2a5851be0f7474f56d5f8b0b5cbb2b305c7b44/apps/recorder/clkinfo.js#L10) at that point.

Out of the clocks that use both `clock_info` and widgets, only [`lcdclock`](https://github.com/espruino/BangleApps/blob/ddc9ac34b1aa502ab5fb147fb05cf33293945dba/apps/lcdclock/app.js) loads widgets first, so all the other clocks won't see the recorder widget.

<details>
<summary>
Clocks using `clock_info` & widgets
</summary>

```sh
grep -l clock_info apps/*/*.js | xargs grep -El 'clock_info|Bangle\.loadWidgets'
```

</details>

To fix this I think would be difficult, we'd have to make it so clocks load `clock_info` after any widget loads, or somehow make the `clock_info` menu dynamic. What do you think?

**Comment by bobrippling** [comment]
Sorted it - we always show the recorder clkinfo and if the widget's not present, the clock hasn't run `Bangle.loadWidgets()` but we just let the user scroll to another clkinfo.

**Comment by gfwilliams** [comment]
Looks great, thanks! Is it worth putting in a PR for LCD clock to change it?

**Pull request merged**
