### PR TITLE
Adding Ben's first app. 

### PR DESCRIPTION
**Pull request by BenNewell32**
Testing the ability to publish an app.

### CODE REVIEW

**Comment by BenNewell32** [comment]
Looks good?

**Comment by gfwilliams** [comment]
Hi! Thanks!

The app itself looks good, but in order to get it to appear in the app loader you need some other files to describe it (name, icon, etc).

There's some info at https://www.espruino.com/Bangle.js+App+Loader about exactly what you need but you can use https://github.com/espruino/BangleApps/tree/master/apps/_example_app as a template.

**Comment by BenNewell32** [comment]
Adding description files.

**Comment by BenNewell32** [comment]
> Hi! Thanks!
> 
> The app itself looks good, but in order to get it to appear in the app loader you need some other files to describe it (name, icon, etc).
> 
> There's some info at https://www.espruino.com/Bangle.js+App+Loader about exactly what you need but you can use https://github.com/espruino/BangleApps/tree/master/apps/_example_app as a template.

Thank you Gordon! Look forward to getting my development going :)

**Comment by BenNewell32** [comment]
Fix file names

**Comment by BenNewell32** [comment]
Redoing repo

**Pull request closed without merging**
