### PR TITLE
sokoban: initial release

### PR DESCRIPTION
**Pull request by wagnerf42**
a nice sokoban game for the holidays.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great! So many levels too!

Please could you rename the `Microban.txt` file on the bangle though? Maybe just to `sokoban.microban.txt`?

It's just helpful so if someone looks on their Bangle they know what app a file belongs to

**Comment by gfwilliams** [comment]
Please could you rename the Microban.txt file on the bangle?

**Comment by wagnerf42** [comment]
hi everyone, i'm just back. the renaming is done.

**Comment by gfwilliams** [comment]
Hi - hope you had a good break! I'm afraid renaming to `Microban.sok` wasn't what I had in mind - I meant ensuring the name started with `sokoban.` so that all sokoban's files were `sokoban.*` - otherwise if you're looking at the files on the device you have no idea where `Microban.sok` comes from

**Comment by wagnerf42** [comment]
hi, yeah, we went biking with the familiy. 500km with the watch to guide us. it was excellent.

i renamed the file again, i hope it is ok.

**Comment by wagnerf42** [comment]
hi, just to let you know i pushed a few fixes.

**Comment by gfwilliams** [comment]
Great - thanks! Sorry for the delay - I was off last week too!

**Pull request merged**
