### PR TITLE
ColorWheel

### PR DESCRIPTION
**Pull request by rozek**
Normally, I'd like to separate apps into different branches - but then, they won't all be visible in my private app loader. As a consequence, I had to pack all into the same branch and one single pull request

ColorWheel - a tappable wheel of good looking colors for Bangle.js 2
Minimal Analog Clock - just with some hands and no further clock face
Simple Analog Clock - a simple, yet stylish, analog clock
Colorful Analog Clock - an analog clock with a colorful face

### CODE REVIEW

**Comment by HilmarSt** [comment]
colorwheel/app.js :
Nice App, for me it would be better useable with:
  let outerRadius = Math.min(CenterX,CenterY) * 1.2;
  let innerRadius = outerRadius*0.4;

Also a litte "screen locked" icon would be helpful.

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by rozek** [comment]
oops, that was quick!

Welcome back, Gordon, you hopefully had relaxing vacations!

**Comment by rozek** [comment]
@HilmarSt: I'll deal with your remarks as soon as I'll be done with my backlog of other activities - please, give me some time until the weekend!

**Pull request merged**
