### PR TITLE
New widget: Days left

### PR DESCRIPTION
**Pull request by Purple-Tentacle**
I developed a widget that shows you the days left until a certain date.
The date can be set using an app, it will be stored in a json file.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by Purple-Tentacle** [comment]
Should the app be in the app loader by now?
I cannot see it yet.

**Comment by gfwilliams** [comment]
Not yet, I manually update banglejs.com/apps every few days

It'll be in https://espruino.github.io/BangleApps/ (the dev version) though

**Comment by Purple-Tentacle** [comment]
Ah okay thought this would be done automatically.
Thanks for the hint. Learning something new every day.

**Pull request merged**
