### PR TITLE
Hand Wash Timer 0.02

### PR DESCRIPTION
**Pull request by adamschmalhofer**
Ported to Banglejs2

### CODE REVIEW

**Comment by MaBecker** [comment]
It uses swipe, because you don’t want to touch the screen directly with dirty fingers.

**Comment by adamschmalhofer** [comment]
@MaBecker I'm not sure what you are trying to tell me.

**Comment by MaBecker** [comment]
A swipe can also happen your arm, to keep the display clean.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
