### PR TITLE
[lightswitch] - Minor tidying up

### PR DESCRIPTION
**Pull request by stweedo**
What do you think @storm64? Does this look okay to you?

### CODE REVIEW

**Comment by stweedo** [comment]
Could either go like this :
```
} else {
        // backlight off
        g.setColor(g.getBgColor());
      }
```

Or like this:
```
} else {
        // backlight off
        let innerColorWhenOff = g.getBgColor();
        g.setColor(innerColorWhenOff);
      }
```

Either one will make it look more consistent when off between themes where the inner bulb color matches the background.

**Comment by stweedo** [comment]
Example here where the background color was changed, now it matches when the light is off instead of being just a black bulb shape. 

download

**Comment by stweedo** [comment]
> ```
> g.setColor(g.theme.bg);
> ```

Thanks! I forgot about that one.

**Comment by storm64** [comment]
The problem with using the bg color is on the light themes. In my opinion it is counterintuitive if a white bg should display an off status.

Here the default theme examples from the reedme:

**Comment by stweedo** [comment]
I think we can leave that as is if that's the intended behavior.

**Comment by gfwilliams** [comment]
Ok, I see what you mean - so I guess we pull out the `setBgColor(g.theme.bg)` change?

**Comment by stweedo** [comment]
> Ok, I see what you mean - so I guess we pull out the `setBgColor(g.theme.bg)` change?

I think so, I'm not sure how best to implement a new setting right now. Should I still go through with the PR for the rest?

**Comment by stweedo** [comment]
Sounds good. I changed it back.

**Comment by gfwilliams** [comment]
Looks good - thanks!

**Pull request merged**
