### PR TITLE
after 2v14 release: [Scheduler] UI improvements

### PR DESCRIPTION
**Pull request by alessandrococco**
This PR removes the custom boolean formatter since the new menu system handles the booleans better.

image

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! The only thing to say here is that I think pre-2v13 firmwares will output true/false instead of the checkbox.

I'm not sure how much we care about that (how many people are going to be on older firmware still?)

**Comment by alessandrococco** [comment]
I would not worry about it, this is not a breaking change (the app will still works for those users).

**Comment by gfwilliams** [comment]
Good point :) Although I just checked and on Bangle.js 1 2v13 we still display those menu items as true/false.

I just changed it, but it'll mean that until 2v14 Bangle.js 1 users get a rubbish experience.

I'm tempted to maybe hold off on this until the 2v14 release and then do a bit of a blitz and remove Yes/No and On/Off from pretty much all apps in BangleApps

**Comment by gfwilliams** [comment]
Thanks! I guess we could look at doing this for other apps too...

**Comment by alessandrococco** [comment]
> Thanks! I guess we could look at doing this for other apps too...

I have a local branch with many apps updated. I think I'll send a PR in the weekend.

**Comment by gfwilliams** [comment]
That'd be great, thanks! I'm away next week so won't get it merged then, but I will on my return :)

**Pull request merged**
