### PR TITLE
New Swatch Internet Time widget (widswatchbeats)

### PR DESCRIPTION
**Pull request by npbreland**
Just got my Bangle a few weeks ago and I wanted to try contributing a small widget. This widget shows the current Swatch Internet Time in the top left. Please let me know then if there is anything I should change!

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great, thanks! Only thing I'd say is you don't need the `widget-icon.js`/`widswatchbeats.img` - because it's a widget it doesn't appear in the launcher, so an icon won't ever be displayed anywhere.

Please could you take that out? Just remove `widget-icon.js` and the associated line in `metadata.json`? And I'll merge

**Comment by npbreland** [comment]
Thanks for having a look! That makes sense, since it's a widget. I just removed the image line.

**Comment by gfwilliams** [comment]
Thanks! Merging now :)

**Comment by npbreland** [comment]
Great! Thanks for deleting widget-icon.js file for me -- forgot that part.

**Comment by gfwilliams** [comment]
No problem - thanks for contributing!

It's on the dev app loader now, but won't go live on banglejs.com/apps until next week

**Pull request merged**
