### PR TITLE
Circlesclock v0.15

### PR DESCRIPTION
**Pull request by myxor**
Use Bangle.setUI({remove:...}) to allow loading the launcher without a full reset on 2v16

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Although actually both `let` and `const` are block-scoped, so there's no reason to change (it's just when there's `var` where it's needed).

The CI checks are complaining about mixed spaces/tabs (https://github.com/espruino/BangleApps/pull/2197/files) - please could you try and get rid of those?

**Comment by myxor** [comment]
I replaced the tabs with spaces.

Should i revert the `const` to `let` changes?

**Comment by gfwilliams** [comment]
> Should i revert the const to let changes?

If it's not hard, that would be preferable I think - as then lint (or espruino) can more easily tell if there are any bugs

**Comment by myxor** [comment]
Done.

**Pull request merged**
