### PR TITLE
Analog clock updates

### PR DESCRIPTION
**Pull request by nikmartin**
Refactored analog clock to get my feet wet with Bangle.js and Espruino:

- simplify timers to a single second timer
- fix draw widgets order of call 
- make seconds ticks more readable
- add elapsed seconds display
- add date

### CODE REVIEW

**Comment by MaBecker** [comment]
if you like add locales too 😉

**Comment by nikmartin** [comment]
@MaBecker My search-fu is failing me, does Espruino have a localization system, or does each app have to come up with their own locale scheme?

**Comment by MaBecker** [comment]
Well,  a full set of locales  would unnecessary blow up the firmware, so every one can pick a locale with app Languages to be available for apps on his Bangle.js

Sneak into[ Mixed Clock](https://github.com/espruino/BangleApps/blob/master/apps/miclock/clock-mixed.js) app to figure out how this work and look at this forum [conversion](http://forum.espruino.com/conversations/345155/#comment15172813)

**Comment by nikmartin** [comment]
Done!

**Comment by gfwilliams** [comment]
Thanks! Please could you add/update the ChangeLog so users know what has changed? https://github.com/espruino/BangleApps/blob/master/apps/aclock/ChangeLog

**Comment by nikmartin** [comment]
ah, yes, i did but didn't bring it to this branch.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
