### PR TITLE
Timer app

### PR DESCRIPTION
**Pull request by marcocastignoli**
Single click BTN1 to add 5 minutes. Single click BTN2 to add 30 seconds. Single click BTN3 to add 5 seconds. Tap to pause or play to timer. Double click BTN1 to reset. When timer finishes the watch vibrates.

I hope the name is ok :)

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Do you think it's possible to change the name though?

Because it's what I use in the example: https://www.espruino.com/Bangle.js+App+Loader

Adding it will mean that anyone who follows the tutorial will encounter problems :(

**Comment by marcocastignoli** [comment]
@gfwilliams ok done! Now it's **Chrono**!

**Comment by gfwilliams** [comment]
Perfect - thanks!

**Comment by marcocastignoli** [comment]
Thank you! Great Job! Can't wait to develop more apps. Today my pasta was drained following the timer installed on my watch, and for the first time no Google or Apple are knowing my pasta habits. I'm not joking I'm feeling free!

**Pull request merged**
