### PR TITLE
AC-AC bugfix and version change to 1.0

### PR DESCRIPTION
**Pull request by rozek**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - please can you update the changelog too?

**Comment by gfwilliams** [comment]
https://www.espruino.com/Bangle.js+App+Loader#making-changes

Ahh - looks like you never had a ChangeLog - usually you'd copy from `_example_app` and there's one in there to start with.

I'll add something to the readme as well - doesn't help the same info is duplicated

**Comment by rozek** [comment]
added ChangeLog as described in the docs

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
