### PR TITLE
Chrono Widget 0.03

### PR DESCRIPTION
**Pull request by Purple-Tentacle**
Display minutes:seconds when less than 1 hour is left.

### CODE REVIEW

**Comment by gfwilliams** [comment]
I guess this isn't ready to merge yet as it's using `graph`?

Please can you let me know next time if that's the case? Saves me merging accidentally :)

**Comment by Purple-Tentacle** [comment]
No, Active Pedometer uses graph, but there is no PR for this yet.
This does not, can be merged.

**Comment by gfwilliams** [comment]
Ok - I think the issue is you did a PR from your GitHub master branch.

When you do a PR it keeps updating it based on your branch - so it looks like you committed the active pedometer and that's updated this PR as well.

Closing for now - maybe you could create a branch with just the chrono widget on and PR from that, or just reopen this PR when you're happy with the active pedometer as well

**Comment by Purple-Tentacle** [comment]
Ah, did not realize that Active Pedometer was in here, too. Sorry.

**Pull request closed without merging**
