### PR TITLE
Add power usage module

### PR DESCRIPTION
**Pull request by bobrippling**
A follow-up to #3477, this adds `require("power_usage")` support

Also updates types (based on espruino/Espruino#2533), specifically for `startsWith()`

### CODE REVIEW

**Comment by bobrippling** [comment]
Blocked on a firmware bug - espruino/Espruino#2529

**Comment by bobrippling** [comment]
Firmware bug closed - will hold off on merging until 2v24's released

**Comment by gfwilliams** [comment]
That fix reverted because it breaks parsing `(1)/2` - I think it would be best to modify this code so it can be merged as fixing the issue properly is going to take a while.

What about changing `if(!/^(LCD|LED)/.test(key))` to just `if (!key.startsWith("LCD"))` - I could be wrong but as Bangle.js doesn't have an LED, it seems like there's no need to check it? And this code is likely faster and definitely more readable.

**Comment by bobrippling** [comment]
Sounds good, sorted - I'll test this for a little while and merge in a few days. Bangle.js has both `LED1` and `LED2`, but I doubt anyone's using them since they're just shown on the LCD, so it's probably not important

**Comment by bobrippling** [comment]
@Poolitzer I'll merge later today unless you've seen any issues?

**Comment by Poolitzer** [comment]
Yes looks good to me. For the end user it might be better to have it not that jumpy between screen on/off, but I feel like this is either a bigger addition to the module or smth the apps should take care of since they know in which intervals this gets called.

But thanks for putting it in a module and in the daisy app way better.

**Pull request merged**
