### PR TITLE
Add School Calendar

### PR DESCRIPTION
**Pull request by Ronin0000**
Sorry if my welcome was accidentally edited I did not mean to change that.
Read me file:
# School Calendar

School Calendar is a calendar that you can see your upcoming classes or schedule.

## Usage:
Enter your calendar events on the customizer then upload. (all day events are not supported yet)

Once uploaded on the watch when in the table mode you can use BTN1 and BTN3 to scroll up and down on the list. (The red rectangle indicates your current position on the table and your yellow rectangle indicates your current schedule item or your next schedule item.)

If you press BTN2 it will go into detail mode, and you can see additional information about your schedule item. Also, in this mode you can scroll up and down with BTN1 and BTN3 to move around in the table. To exit detail mode press BTN2 again. 

## Screenshots:
screenshot (5)
screenshot (6)

## Updates Coming Soon:
- [ ] Notifications
- [ ] All Day Events
- [ ] Improved Rendering Screen
- [ ] Better Graphics
- [ ] Scrolling Table
- [ ] Bangle.js V2 Compatibility
- [ ] Full Calendar (Calendar that does not have repeating weekly events.)

## Creator
Ronin0000

### CODE REVIEW

**Comment by gfwilliams** [comment]
Wow, looks nice - thanks!

Just before I commit this, will it work without the `apps/schoolCalendar/fullcalendar/interaction/src` folder? It seems like that's typescript that is likely compiled down to `main.js` or something like that. It'd avoid adding a whole bunch of extra files that are not required to the repo

**Comment by Ronin0000** [comment]
Hi @gfwilliams, I just tested and it will work without the files in: apps/schoolCalendar/fullcalendar/interaction/src folder. You can delete those files. Thanks!

**Comment by weeurey** [comment]
Heh this is a cool app! Wish I had something like this at highschool!

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
