### PR TITLE
pomoplus: increase size of fonts and buttons

### PR DESCRIPTION
**Pull request by thyttan**
for legibility and ease of use.

Changes made primarily for the Bangle.js 2. I haven't run them on an actual Bangle.js 1 watch - only the emulator. The update can be tried here (please report back if you try!): https://thyttan.github.io/BangleApps/?id=pomoplus

@bruceblore @notEvil thoughts?

Edit: After measuring ram use it think it still fits on the Bangle.js 1.

### CODE REVIEW

**Comment by pavelmachek** [comment]
Unrelated to this, I noticed that I don't know what pomoplus is and what it should be doing. Adding README would be quite welcome.

**Comment by notEvil** [comment]
I tried it on Bjs1 using the emulator and looks good to me, with `const SCALING = W/g.getWidth()`.

**Comment by thyttan** [comment]
> I tried it on Bjs1 using the emulator and looks good to me, with `const SCALING = W/g.getWidth()`.

That will undo the scaling though - it will evaluate to 1 and not do anything. Did it not look good with `= W/176`?

**Comment by notEvil** [comment]
True, silly me. Didn't know what its supposed to look like and preferred a little more spacing between things. But thats just a matter of taste, don't feel obliged to change, especially because I'm bad at visual design in general :)

**Comment by thyttan** [comment]
Thanks @pavelmachek and @notEvil for your feedback. I'll merge this now.

**Pull request merged**
