### PR TITLE
messagelist: new app

### PR DESCRIPTION
**Pull request by rigrig**
Displays messages inline as a single list.

Still plenty of room for improvement, but I think it's good enough for general release now.   

Maybe hold off merging this until the app loader is smart enough to detect+handle `messagegui` conflicts? ([forum discussion](https://forum.espruino.com/conversations/373307/?offset=25#comment16793104)) I'm in no hurry to get this merged, and you'll be the one getting the bug reports 😉

### CODE REVIEW

**Comment by gfwilliams** [comment]
:) Thanks! Yes, I'll try and get that added to the app loader this week sometime

**Comment by rigrig** [comment]
Whoops, I also just realized I haven't properly tested `uiRemove`. As in: fast loading *seems* to work fine, but I haven't checked for memory leaks yet, and might have forgotten some timeouts.

(This is as much a reminder to myself, as a warning that you might want to wait a bit with merging this ;-)

**Comment by gfwilliams** [comment]
Ok, I've just added the code to check for clashes to the development loader - if you get a second please could you check it works ok for messagelist?

**Comment by rigrig** [comment]
The loader seems to work fine, thanks!

`messagelist` is leaking memory though :-(

**Comment by rigrig** [comment]
Couldn't figure out the memory leak yet, so I converted it to draft.   
I'll have another look tomorrow, if I still can't find it I'll just disable the fast clock loading for now.

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
