### PR TITLE
bthrv - Always write interval data on kill and reset if at least the first measurement is available

### PR DESCRIPTION
**Pull request by halemmerich**
This works in most situations, but the kill handler set on line 98 just doesn't trigger. That causes lines without \n in the csv file when currently taking measurements.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Odd about the kill handler not triggering - how are you changing apps?

What's the reason to writing data as soon as possible though? From the point of view of Bangle.js it's definitely more efficient to write to Storage less often, but with more data, so writing whole lines would probably be better

**Comment by gfwilliams** [comment]
Ok, sorting the kill event would definitely be the best solution then...

So if you just paste `E.on('kill', ()=>print("Kill event"))` into the terminal and change app, do you see `Kill event` being printed to the console? Just tried it here and it seems pretty reliable.

**Comment by halemmerich** [comment]
Yes, I had tried that, worked without fail. I suspect some of my other code prevents it from working.

**Comment by gfwilliams** [comment]
Excellent - thanks!

**Pull request merged**
