### PR TITLE
Largeclock changes

### PR DESCRIPTION
**Pull request by nebbishhacker**
Tweak the layout to work better with the new vector font, and add support for 12 hour time.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! You've been busy :)

**Comment by Weiming-Hu** [comment]
Hi @nebbishhacker , I really like your LargeClock app and I'm using it everyday. I added one functionality to configure the tilt of the texts on the side. It can base on the wrist on which you are wearing the watch. I find it easier to read if I can configure the direction. Please check out my commits [here](https://github.com/Weiming-Hu/BangleApps/commit/8bfce14000371f5b886ad0945bb21fe62ee02d0f). Thank you.

**Comment by nebbishhacker** [comment]
@Weiming-Hu looks like a good change! You should submit it as a new pull request.

I'm not the original author of bigclock, btw. I just updated it when the vector font changed.

**Comment by Weiming-Hu** [comment]
Thank you. I will create a new pull request.

**Pull request merged**
