### PR TITLE
sleepphasealarm

### PR DESCRIPTION
**Pull request by nxdefiant**
Support javascript command to execute as defined in scheduler 'js' configuration

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! You might want a `if (nextAlarmConfig.js) { ... } else ...` though? Because I think if JS is supplied you're not meant to do anything else (like buzzing).

It's a shame there isn't a way to call into `sched` and use the code that's already in there

**Comment by gfwilliams** [comment]
> I would like to avoid the else path. If you call 'load()' in the eval() the sleepphasealarm.buzz() is not executed anyway.

But that means that if someone installs your code, suddenly alarms with JS work differently if they don't call `load()`?

That just seems like a really bad idea. And when this breaks for someone - which it will - it'll be me that ends up having to try and debug it :(

**Comment by nxdefiant** [comment]
ok, done

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
