### PR TITLE
add function meridian to locale

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by gfwilliams** [comment]
This sounds good, thanks!

Just so you know though, when changes get added to the `locale` library they also need to be added to https://github.com/espruino/Espruino/blob/master/libs/js/banglejs/locale.js which is the one that gets used if there's no locale installed (or in the emulator)

**Comment by gfwilliams** [comment]
I'll add that to it now

**Comment by gfwilliams** [comment]
Also - while it doesn't show as an error at the moment (just a warning), if you bump the version in the changelog it also needs to go in apps.json :)

**Comment by MaBecker** [comment]
Thanks!

**Pull request merged**
