### PR TITLE
:rewind: Release DANE 0.16

### LINKED ISSUE #613: Digital Assistant, not EDITH, counter is now chnaging with battary level over buttons
Hi
Not sure who is working on the Digital Assistant, not EDITH app but I think that the "count" variable has been overused and is now being updated with the battery level, not just with the buttons.
I have a feeling it is line 70 that is the issue? "count = l" where l is the battery level.
Maybe it is worth having this as an option in the setting as I am sure some people would love to have the big count show the battary.
Sorry if this all meant to be like that, I am just starting to code with the bangle.js so please ignore if it is meant to be this way.

### PR DESCRIPTION
**Pull request by OmegaRogue**
### Release DANE Watchface version 0.16

- [x] Testing

#### Changes:
- Revert Counter to being button controlled, as the previous batters display was for debug purposes while implementing the battery bar

Closes #613

### CODE REVIEW

**Comment by gfwilliams** [comment]
Are you happy with this? Looks good to merge to me...

**Comment by gfwilliams** [comment]
Is this good to go? You marked it as a draft so I'm just checking before merging

**Comment by OmegaRogue** [comment]
I did some testing, and everything works well, now it is ready to merge

**Comment by gfwilliams** [comment]
Ok, thanks! Merging now

**Pull request merged**
