### PR TITLE
Slopeclock/pp - Reset graphics to remove font from memory

### PR DESCRIPTION
**Pull request by halemmerich**

### CODE REVIEW

**Comment by thyttan** [comment]
Just a note to say that #2241 seems solved even before this PR, at least from looking at the RAM Widget (not tested ++)

**Comment by halemmerich** [comment]
Yes, but that depends on whatever is loaded after the clock doing a `g.reset()` somewhere.

**Comment by gfwilliams** [comment]
Thanks! It's a good point - hopefully apps won't assume that graphics will be reset but it'd be a good idea to do it in case. We just don't want to get into a position where we're implementing all of `reset/load()` just in JS each time we do `Bangle.load()` :)

... what about calling it in `setUI` instead? That might be quite a good idea in general as it pretty much always results in the screen being redrawn.

I'll merge this, but will actually tweak it slightly after - because IIRC the font is only used to redraw once in the `draw()` function, and after that it's not needed (even during the animation). We might as well reset state right after drawing and then the Bangle isn't sitting there for seconds with the font allocated

**Comment by halemmerich** [comment]
Since `Bangle.load()` calls `setUI()` anyway in case a fast load is done that would not make any difference. I think it is OK to have the apps being responsible to clear out changes to the global graphics objects.

**Pull request merged**
