### PR TITLE
Rings watch app.

### PR DESCRIPTION
**Pull request by lightnin**
Hello good people in the Bangle JS community. (I hope it's not just Gordon that reviews all the PRs!)
Here is a new watch face based on Rinkulainen but substantially different through the use of numbers in the rings, display of month / date in an outermost ring, and animation triggered by changes in lock state.

I am interested / open to feedback for any improvements / optimizations. Particular weakness I'm aware of:
- I don't understand the math used to position the gaps in the rings, so I bastardized what is there and average it to set the location of the numbers within those gaps. It's not pretty.
- I create an image object with the text for the month and year and keep it around in memory so I can drop it onto the date ring. Perhaps there are more efficient means of doing this (1/2 size maybe?)
- The text in outer ring is not so pretty. Perhaps I'm doing something with transparency or rotation that anti-aliasing doesn't play nice with?

Thanks!

### CODE REVIEW

**Comment by gfwilliams** [comment]
> I hope it's not just Gordon that reviews all the PRs!

Right now, it is... I've been meaning to try and do something about that ;)

This looks great - thanks! The date text is a tricky one - I think that's about as good as you'll get at the moment, although maybe rendering with the vector font and scaling down to 50% may get it a bit better.

**Comment by lightnin** [comment]
Thanks for the merge @gfwilliams  - and let me just briefly say: I'm so impressed by this project and the whole community as well. The hardware is great,  but the community aspects of what you are doing -- from support resources to workflow for app contributions -- is just amazing. I used to run a pretty big online programming community, so I just want to say: As a learning environment and open source ecosystem this is exceptionally well done and incredibly well thought out.  My hat is off to you, sir!!

**Comment by lightnin** [comment]
Also - I meant to ping @jukioo to say thanks and give credit for the code I remixed from the wonderful Rinkulainen watchface. And to explain - at first I meant to just contribute a new face within Rinkulainen. But things developed and got tricky with the animation stuff, so I decided to just fork and give you credit in the readme and code. I hope you like it and do let me know if you have any thoughts or suggestions for improvements.

**Comment by gfwilliams** [comment]
Thanks! That's great to hear - I'm glad you're enjoying it! What was the community you were running?

**Comment by lightnin** [comment]
> Thanks! That's great to hear - I'm glad you're enjoying it! What was the community you were running?
Scratch.mit.edu, up until 2015 when I moved to Denmark.

**Comment by gfwilliams** [comment]
> Scratch.mit.edu

Wow - that's massive! That's a very cool thing to be involved in!

**Comment by gfwilliams** [comment]
Thanks - yes, I think it could be quite a fun thing to have a class using them. I have heard of one or two places doing it, but I think so far they have used the emulator rather than real watches - which limits what you can do to simple apps that don't use the sensors.

**Pull request merged**
