### PR TITLE
magnav: Outsource tilt compensation to library

### PR DESCRIPTION
**Pull request by nxdefiant**
and let waypointer use the lib

Notify @jeffmer @hughbarney

### CODE REVIEW

**Comment by halemmerich** [comment]
Cool, could use this in GPS Trekking :)

**Comment by nxdefiant** [comment]
@halemmerich FYI I plan to write a small script that runs at boot time and overwrites the course value in the gps event with the compass direction for lower speeds.

**Comment by gfwilliams** [comment]
Sounds great, thanks!

If this doesn't specifically require 'magnav' we could just pull it out into something in the `modules` folder?

**Comment by nxdefiant** [comment]
Right now starting magnav is the only way to calibrate the compass. So right now I would not put it in modules.

**Pull request merged**
