### PR TITLE
sched: add day selection to interface.html

### PR DESCRIPTION
**Pull request by bobrippling**
This gives `sched`'s `interface.html` the ability to select which days an alarm will trigger on.

Deployed on [my gh-pages](https://bobrippling.github.io/BangleApps/?q=sched)

### CODE REVIEW

**Comment by thyttan** [comment]
On my laptop it's hard to make anything out of the days section:
image

**Comment by bobrippling** [comment]
That's fair - we could make the selection a little wider? How do you feel about its height?

**Comment by thyttan** [comment]
It might be better if two days fit the display box. But currently I don't understand how to toggla a day? If I could see more of the boxes content I might have understood though.

**Comment by nxdefiant** [comment]
I would say we give each entry two rows, that would give us additional horizontal space.

**Comment by nxdefiant** [comment]
I meant the entire scheduler entry: type, date, day of week, message, on/off and deleted could probably be split into two lines so each entry can get wider.

**Comment by thyttan** [comment]
Don't know if you want any feedback already, but here's a screenshot from my laptop after https://github.com/espruino/BangleApps/pull/3227/commits/1c620878cf3a1dced23678d8db38f36d4f6084d4 :

image

**Comment by bobrippling** [comment]
I'm interested in what you think now in fact - we can rowspan a few of the cells to give this effect, although it looks a bit more noisy than the original 1-row approach:

image

Original:

image


Perhaps we stick with 1 row and just buff the height (and width) of the day selection, what do you both think?

**Comment by thyttan** [comment]
Just looking at your screenshot with the changes, could the delimiters for the different alarms be as fat as the delimiter line under the header. Then if possible make that top delimiter even fatter? I think that could be nice.

I agree it currently looks a little more cluttered, but I still prefer it since I can actually see the info in days box. Extra space in the Summary field is also welcome!

**Comment by nxdefiant** [comment]
How about: Row 1: type, date, summary
Row 2: options.

Also I think that [select2](https://select2.org/getting-started/basic-usage) would make the better select box then spectre.

**Comment by bobrippling** [comment]
Pushed up some changes to declutter the table borders and align the type - I think `select2` is nice but let's see about merging the functionality change and we could discuss with @gfwilliams about bringing in a library or more thorough UI changes.

What do you think about the current layout? We could move options to the second row if this is a bit cluttered still.

image

**Comment by nxdefiant** [comment]
Basically ok with me. But the on/off toggle could be below the summary input, which would mean the summary could take more space.

**Comment by bobrippling** [comment]
Nice idea, let me see what I can rustle up

**Comment by bobrippling** [comment]
Ok, what do you think of this edition?

image

**Comment by nxdefiant** [comment]
Looks like the scrollbar is somehow missing

**Comment by bobrippling** [comment]
Phew about the scrollbar! Thanks for the save for events & timers. I've also adjusted the layout similarly to your idea above - shifted the options around. Let me know what you both think:

image

**Comment by nxdefiant** [comment]
I would put the date up, I believe it should be the first item since it is the most interesting one and probably the first to be edited. Any other opinions on this?

**Comment by bobrippling** [comment]
Sorted, tada:

image

**Comment by nxdefiant** [comment]
I hope I'm not pushing your patience too far, but maybe the type (event, alarm, timer) to the left?

**Comment by bobrippling** [comment]
Not a problem, easy change to make

**Comment by nxdefiant** [comment]
ok to merge :)

**Comment by bobrippling** [comment]
Great! Here's the final version now it's built, shall merge shortly

image

**Comment by bobrippling** [comment]
Thanks for helping hash out the design, both of you

**Comment by gfwilliams** [comment]
Looks great - thanks everyone!

**Pull request merged**
