### PR TITLE
New clock face - mosaic

### PR DESCRIPTION
**Pull request by sir-indy**
New clock face, bright and colourful but still easy to read. Options to show or hide widgets.

### CODE REVIEW

**Comment by alessandrococco** [comment]
The fullscreen version is really cool!

**Comment by sir-indy** [comment]
I forgot to reference my inspiration, the pebble watch face: https://store-beta.rebble.io/app/55386bcd2aead62b16000028
Should I add that to the readme?

**Comment by alessandrococco** [comment]
> I forgot to reference my inspiration, the pebble watch face: https://store-beta.rebble.io/app/55386bcd2aead62b16000028 Should I add that to the readme?

In my opinion, yes. Furthermore other [Pebble-inspired themes](https://banglejs.com/apps/?q=pebble) make it explicit.

**Comment by gfwilliams** [comment]
This looks great - thanks! Using g.drawImage for this is great too as it should be pretty speedy.

Not sure what you think but when I finally sort out https://github.com/espruino/BangleApps/issues/1466 it might be a neat thing to use when fullscreen.

**Comment by sir-indy** [comment]
Thank you Gordon (and Alessandro for your help and feedback)!
I like the sound of the hideable widget bar, that would be ideal for this.

**Pull request merged**
