### PR TITLE
[Health Tracking] Move settings

### PR DESCRIPTION
**Pull request by alessandrococco**
As suggested in https://github.com/espruino/BangleApps/pull/1734#issuecomment-1108413622.

### CODE REVIEW

**Comment by gfwilliams** [comment]
You sure this works? It seems like the `});` at the end may break it?

**Comment by alessandrococco** [comment]
> You sure this works? It seems like the `});` at the end may break it?

Yes, I run it on my Bangle. The `});` at line 43 closes the `(function (back) {`. Maybe it feels strange due to the `setSettings` function after the menu 😄

**Comment by gfwilliams** [comment]
Ok, thanks - in future can you try and avoid it though - because it's supposed to be an expression executed by `eval` so shouldn't really have the `;` on it

I'll merge now, but I'll also add a 'settings' link to the app menu to folks can still find the settings

**Comment by alessandrococco** [comment]
> but I'll also add a 'settings' link to the app menu to folks can still find the settings

Should the 'settings' link in the app be a standard practice? IMHO it's confusing if some apps link to theirs settings and some do not.

**Comment by gfwilliams** [comment]
I feel like where apps have a menu and it makes sense, they probably should link to settings as otherwise users may not be aware things *can* be changed. For clocks/etc where there's no obvious way to go to the settings menu I think they shouldn't.

**Pull request merged**
