### PR TITLE
[wrkmem] A working memory prosthesis

### PR DESCRIPTION
**Pull request by philipandresen**
# Working Memory Helper
screenshot screenshot2 screenshot5 screenshot6

## Description
Detailed information in the readme.

This app is why I bought the BangleJs in the first place. The idea is to have a device on my wrist that can remind me every 30 seconds or so of what I am doing, so that if I get distracted I can quickly get back on task. 

I created a custom menu system for certain parts of this app which I might like to abstract away into its own project eventually, but for now they are a large portion of the submitted code. Tried to ensure I was relying exclusively on "setUI" to manage user interface so that there wouldn't be any lingering listeners that could interfere with other apps or menus.

One feature I'm particularly excited about is the sorta-modular swipe control affordances. Each menu can be accompanied by up to four swipe hints giving users a little descriptive text and a swipe direction so they know that a given swipe control is available, and what it will do when they swipe that way.

## Known issues
The only real issues with this code right now is the clock is not updated once per minute - it may be updated more or less depending on how often the user gets a reminder. Ultimately the clock wasn't the focus, and updating "roughly once every time the user looks" was good enough for what I needed.

This app also supports keyboard pre-generation as implemented in [kbmatry] but should still work fine with any other installed keyboard library.

### CODE REVIEW

**Comment by philipandresen** [comment]
This code actually contains a few instances of a workaround for https://github.com/espruino/BangleApps/issues/2816 which was resolved with https://github.com/espruino/Espruino/commit/a0e2d9231df709849f81abf572a742b0fceab85b . 

I wans't expecting it to be fixed so quickly! I will add a commit to remove those workarounds in anticipation of that change.

**Comment by gfwilliams** [comment]
Looks great, thanks!

Out of interest, was there a reason that the Layout library didn't work for you? http://www.espruino.com/Bangle.js+Layout 

I really like the swipe indicators - I added something to the Messages library just a week or so ago but having something built-in and easy to use would be really neat.

**Comment by philipandresen** [comment]
> Out of interest, was there a reason that the Layout library didn't work for you? http://www.espruino.com/Bangle.js+Layout

I actually did a first implementation of this app with that lib, but it ended up not being flexible enough for everything I needed. In retrospect that was more my fault than the library's fault, but I think it helped me to do it all myself the second time.

Maybe next commit will adapt it to the layout library, now that I know what I want and can think just in terms of custom render functions in that framework.

**Comment by gfwilliams** [comment]
> Maybe next commit will adapt it to the layout library

I wouldn't worry about it. Layout can actually end up being quite slow to lay everything out, and what you have there doesn't look like it takes up much space and would be faster as well.

It has been suggested that actually what's needed is a simple (scrollable) grid layout system (maybe 3x3 which feels like the smallest most folks can reliably touch), which I guess may help with this kind of thing - but with your particular layout I'm not sure it would help

**Pull request merged**
