### PR TITLE
Skeleton files and some app fixes

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by gfwilliams** [comment]
I think there are still merge issues because the apps got moved into their own folders. Also I'd have thought that having drawWidgets in the LCD 'on' handler wasn't such a bad idea? If you're ok with it I'll merge this but just not the removal of drawWidgets in the clocks? Then it should be pretty easy to merge in

**Comment by MaBecker** [comment]
Ok with me

**Comment by gfwilliams** [comment]
Huh - actually it merged just fine :) I've just moved stuff around as I figured you could just copy the skeleton folder in order to create a new app

**Comment by MaBecker** [comment]
Thanks

> I figured you could just copy the skeleton folder in order to create a new app

Nice

**Pull request merged**
