### PR TITLE
Bootloader

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by gfwilliams** [comment]
That's great - thanks! When you're tweaking stuff like this, please could you bump the version and ChangeLog? I'll do it now anyway though.

**Comment by matjaz** [comment]
sure. did you forgot to merge this? I see you already bumped version. https://github.com/espruino/BangleApps/commit/ca0dcb53d7d83db20deec3022c54da0c0638815e

**Comment by matjaz** [comment]
added additional optimisation.

**Comment by gfwilliams** [comment]
Yep - sorry about that...

**Pull request merged**
