### PR TITLE
fastload - Add warning about automatic reload apploader option

### PR DESCRIPTION
**Pull request by halemmerich**
This adds a warning to the fastload README regarding bad behaviour in combination with the new automatic reload of the apploader.

### CODE REVIEW

**Comment by thyttan** [comment]
Thanks!

**Comment by bobrippling** [comment]
This is interesting - I've been using auto-reload in the app loader and not seen any major issues, but would be keen on discussing a fix even so. Do you have any plans so far to resolve this?

Perhaps we could have the apploader tweak a setting (or touch a file) or change how it performs the upload (e.g. [`reset()`](https://www.espruino.com/ReferenceBANGLEJS2#l__global_reset)) so that fastload isn't active during that time?

**Comment by nxdefiant** [comment]
I'm using fastload and auto-reload and for single app updates this works fine. When updating multiple apps at once it sometimes fails.

**Comment by halemmerich** [comment]
I can usually reproduce it with single app upgrades in under five tries. Did not yet look deeper into this but would very much like a fix. I think we might be hitting #1759 again with the boot code running and doing stuff.
I suspect the "cleanup" done to workaround this is not enough for fastload, since that replaces the global `load()`.

**Comment by bobrippling** [comment]
Cool, if you can get a console dump next time it happens, let's investigate more (and move the conversation to #1759 - nice find)

**Pull request merged**
