### PR TITLE
chronlog: new app for logging time on tasks, courses, work, etc.

### PR DESCRIPTION
**Pull request by thyttan**
Depends on these ~~pending~~ **merged** changes to Gadgetbridge for file sync: https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3563

Available at: https://thyttan.github.io/BangleApps/?q=chronlog

### CODE REVIEW

**Comment by bobrippling** [comment]
Nice! The tapping feels slightly above the burger menu for me, like I'm tapping the description instead. Not sure if you have the same experience? Happy to merge this like this though :)

**Comment by thyttan** [comment]
Thanks - I'll take a look at that! 

I also noticed yesterday I have some linter warnings to adjust.

**Comment by thyttan** [comment]
@bobrippling For me the button touch areas feel good. I use the LCD touch screen calibration, if that's a difference to your watch?

I think it's ready for merge :)

**Comment by bobrippling** [comment]
Yeah I think my calibration was slightly off, this sounds good to merge. And thanks for the nifty app!

**Pull request merged**
