### PR TITLE
Add PWA Support

### PR DESCRIPTION
**Pull request by OmegaRogue**
now working
#203

### CODE REVIEW

**Comment by OmegaRogue** [comment]
With the current configuration it only works for the production site at banglejs.com/apps

**Comment by gfwilliams** [comment]
Nice - thanks! Just a quick question before merge - is the service worker actually required for this?

Right now I'm not sure it really does anything? We can't realistically get the loader running offline (without downloading every app), and I've found that the service worker on the IDE (while great in allowing it to work offline) was quite a big source of pain for a while, as once it's loaded by a bunch of users it can be really difficult to change it on their browsers.

**Comment by OmegaRogue** [comment]
> Nice - thanks! Just a quick question before merge - is the service worker actually required for this?
> 
> Right now I'm not sure it really does anything? We can't realistically get the loader running offline (without downloading every app), and I've found that the service worker on the IDE (while great in allowing it to work offline) was quite a big source of pain for a while, as once it's loaded by a bunch of users it can be really difficult to change it on their browsers.

The service worker i included doesn't have offline functionality, i found that at least a simple service worker is required for a PWA, the service worker just logs the events to console, it doesn't cache the site.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
