### PR TITLE
Refactor some methods to scheduling library

### PR DESCRIPTION
**Pull request by nxdefiant**
As communicated in #1679, moved a few functions to scheduler lib.

### CODE REVIEW

**Comment by nxdefiant** [comment]
@frigis1 You might want to update noteify app if this PR gets ok.

**Comment by alessandrococco** [comment]
Aaaarg, I also just pushed an alarms app refactor  🤣

**Comment by frigis1** [comment]
@nxdefiant Thanks for the heads up! So if I understand correctly, instead of copying the decode/encodetime functions from the default alarm, I can use the sched library to do do that?

**Comment by nxdefiant** [comment]
Yes

**Comment by gfwilliams** [comment]
Thanks - looks good - but...

What's with the [css/main.css](https://github.com/espruino/BangleApps/pull/1722/files#diff-f131fc9dca7d0116bd2258c95e127905bb0db3b922c83db9c7648b32770fc532) change? `word-break: break-word;` would appear to basically be the default, and it seems to word break already for me just fine?

I'm just iffy about pulling in CSS changes like this after the last one broke app layout.

**Comment by nxdefiant** [comment]
Sorry, the css should not have been commited (git commit -a accident).

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
