### PR TITLE
[messagesoverlay] scroll six lines per swipe, on Bangle2 this leaves the previous first…

### PR DESCRIPTION
**Pull request by thyttan**
…/last line visible so the user know they got to see all text.

Not tested on Bangle 1.

@halemmerich

### CODE REVIEW

**Comment by halemmerich** [comment]
Doesn't work on B1 anyway so not a problem :)

**Comment by gfwilliams** [comment]
You could maybe get away with using `E.showScroller` so you have smooth scrolling if you needed it?

Please can you do changelog/metadata?

**Comment by thyttan** [comment]
Sorry, forgot 🙂 will do it later

**Comment by thyttan** [comment]
Ok with me to merge this now that version is bumped.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
