### PR TITLE
Burn - Simple Calorie Counter

### PR DESCRIPTION
**Pull request by slynchDev**
Fixes applied per your suggestion (prior PR)

### CODE REVIEW

**Comment by slynchDev** [comment]
My apologies, I should have kept the prior PR and updated that branch rather than create a new PR (still learning the process here). I applied your suggestions: remove a few unused variables, removed .prettierignore, renamed all app files per the standard in the repo. Thanks

**Comment by thyttan** [comment]
Thank you for the app and the quick changes! Always fun to see new contributors! :)

**Comment by slynchDev** [comment]
Thank you! I did have a couple questions if you don’t mind?

1) I see there a centralized health service to store calories information
like this?

2) Any chance you could elaborate on your boot.js feature request
(calculate on startup)?

Sean

**Comment by thyttan** [comment]
>Thank you! I did have a couple questions if you don’t mind?

Sure - I'll answer to the best of my abilities. :)

>1) I see there a centralized health service to store calories information
like this?

There's the `health` app that log some stats, https://thyttan.github.io/BangleApps/?q=health, is that what you're referencing? @gfwilliams has proposed to add more stats to `health` here: https://github.com/espruino/BangleApps/issues/3275#issuecomment-2006364430

>2) Any chance you could elaborate on your boot.js feature request
(calculate on startup)?

The suggestion was based of my misunderstanding of the app. I thought the idea was that it would automatically estimate calories burned based on activity. If that had been the case it would have made sense to have logic running at all times, also when other apps/the clock was running, to keep track on the activity/calorie burn. But as I understand it the idea is you use the app to count caloric intake?

**Comment by slynchDev** [comment]
Thanks so much. Yes, it’s simply used to count caloric intake.

Ok I will take a closer look at the health app to see if / when there’s an
integration opportunity.

Thanks!

**Pull request merged**
