### PR TITLE
Feature/pomodoro update

### PR DESCRIPTION
**Pull request by ra100**
I hope it's OK that I renamed it from Promodoro to Pomodoro.
Plus there is new feature and UI fix.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great - thanks!

**Comment by gfwilliams** [comment]
I just noticed:

```
setWatch(() => { console.log('BTN1') }, BTN1, { repeat: true });
        setWatch(() => { console.log('BTN2') }, BTN2, { repeat: true });	        setWatch(() => { console.log('BTN2') }, BTN2, { repeat: true });
        setWatch(() => { console.log('BTN3') }, BTN3, { repeat: true });	        setWatch(() => { console.log('BTN3') }, BTN3, { repeat: true });
        setWatch(() => { console.log('BTN4') }, BTN4, { repeat: true });
        setWatch(() => { console.log('BTN5') }, BTN5, { repeat: true });
```

Is there any need for this? Looks like debug code to me - won't do anything except spam the console?

**Comment by ra100** [comment]
@gfwilliams with console logs I just followed previous pattern. So it makes sense to remove it. And I still need to update changelog anyway, add notes about BTN4 and BTN5

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
