### PR TITLE
2FA Authenticator App

### PR DESCRIPTION
**Pull request by andrewgoz**
Implements a Google Authenticator compatible application. I don't have actual hardware, so have been unable to test PC/Phone<-->Bangle communication. This is critical as tokens have to be created on the PC/Phone and sent to the Bangle.

### CODE REVIEW

**Comment by andrewgoz** [comment]
I've been advised by a third party that they've tried out my app and everything appears to be working - including the interface page and PC/Phone <--> Bangle communications.

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by ccchan234** [comment]
AI polite version:
Subject: Security Vulnerability in 2FA App's Secret Key Storage

Hi,

I'd like to highlight a critical security concern in the 2FA application for the Bangle.js 2 smartwatch. The application stores secret keys in an unencrypted JSON format, accessible via the Bangle IDE:

```
{
  "tokens": [
    {
      "algorithm": "SHA1",
      "digits": 6,
      "period": 30,
      "issuer": "xxxx",
      "account": "xxx",
      "secret": "xxxxxxxxxx",
      "label": "xxxxx"
    }
  ],
  "misc": {}
}

```
This approach leaves sensitive data vulnerable on an unencrypted partition. Although there are minimal protections like a Bluetooth PIN and pattern launcher, these do not suffice for securing critical 2FA data.

I urge the team to implement stronger protections, such as encrypted storage, to ensure the security of the secret keys and safeguard user data effectively.

Thank you for addressing this issue.

Best regards,

[Your Name]..

-------------------in my own words


hi,

i would like to report that there is almost completely no protection to the "key", the secret key.

in the bangle IDE one could directly read the .json as 

{"tokens":[{"algorithm":"SHA1","digits":6,"period":30,"issuer":"xxxx","account":"xxx","secret":"xxxxxxxxxx","label":"xxxxx"}],"misc":{}}

which rest on an unencrypted partition.

to me, it's somehow protected from the bluetooth PIN which is weak, and also the pattern launcher somehow works like a screen lock.

if a watch become smart, it also need to be smart enough to know, what could be told, and what should be kept as secret.

thank you.

**Comment by gfwilliams** [comment]
Maybe if you have concerns you could contribute some changes to improve this?

For instance you could have the app require a PIN, and then encrypt the sercet with the PIN?

**Pull request merged**
