### PR TITLE
New app: Hour Strike

### PR DESCRIPTION
**Pull request by Weiming-Hu**

### CODE REVIEW

**Comment by Weiming-Hu** [comment]
Please see [README](https://github.com/Weiming-Hu/BangleApps/tree/master/apps/hourstrike) for its features.

**Comment by rigrig** [comment]
Looks neat. One suggestion though: I don't think it should `load("hourstrike.js")` to strike the hour, it would be nicer if the `notify_func` code was just inside inside `boot.js`.
Because now if you are using some other app while the hour strikes, it will exit and then load the clock.

**Comment by Weiming-Hu** [comment]
Or another way to avoid the infinite loop is to only reboot the `hourstrike` app if possible. Currently, when the app is booted, it figures out how long to wait until the strike.

**Comment by rigrig** [comment]
What you want is something like this:
```js
function setup() {
  // figure out how long until next hour:
  let t = ...
  setTimeout(strike_hour, t);
}
function strike_hour() {
  Bangle.buzz();
  setup(); // schedule strike for next hour
}
setup(); // schedule first strike
```

**Comment by Weiming-Hu** [comment]
@rigrig Fantastic. Thank you very much for your suggestions and I have made changes accordingly. As of right now, it is not calling the `load` function anymore.

**Comment by gfwilliams** [comment]
Thanks! Just merging...

**Pull request merged**
