### PR TITLE
marioclock: use short date format from locale, take timeout from sett…

### PR DESCRIPTION
**Pull request by DerGuteWolf**
…ings

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - it's tricky about the timeout... Bangle.js keeps the screen on whenever there's a `.flip` - but if you're animating then that's going to keep the screen on.

Maybe I could make that one of the `Bangle.setOptions` so your clock can turn it off when it boots, in order to allow the clock to sleep?

**Comment by DerGuteWolf** [comment]
Unfortunatly the few bytes more apparently means we gethit by "Upload Failed, got UNFINISHED STRING expected EOF" now.

**Comment by gfwilliams** [comment]
I'll fix that issue with the App Uploader today, so I wouldn't be too concerned.

**Comment by paulcockrell** [comment]
@DerGuteWolf How do I go about selecting the original date format?

**Comment by DerGuteWolf** [comment]
The setting is taking from the locale app, ie what is selected during installation/update of this app.

**Comment by paulcockrell** [comment]
Oh right, I might be missing something here, in `Settings->Locale` only see time-zone and clock-style, but nothing to do with date formatting.

**Comment by DerGuteWolf** [comment]
@paulcockrell : Yes, the language to be used is not in settings but in the locale app.

**Comment by paulcockrell** [comment]
@DerGuteWolf Looks to me like I can't get the original date format back in that case, and am stuck with this short date.

**Comment by gfwilliams** [comment]
Not sure I understand your problem? You install the `Language` app in the App Loader to set the language, and if you don't like it you can just remove the app.

In terms of Date format, ` locale.date(new Date(), true);` gives you a short date, but ` locale.date(new Date(), false);` will give you a long one

**Comment by DerGuteWolf** [comment]
@paulcockrell : locale defines only two variants: short and long (and long is really long in some locales - but only some - and thus won't fit). The original format was a mixture between both and there is no support in locale to localize such an intermediate variant. Perhaps you should suggest adding a third variant to  @gfwilliams .
Alternativy we could first try long and if it fits, use this and otherwise use the short version.

**Comment by paulcockrell** [comment]
My problem is I want to see the Day name and day number as I originally wrote it. The year is not something I need reminding of.

**Comment by DerGuteWolf** [comment]
@gfwilliams : Part of the problem here comes also from the fact, that esp the long versions are not consistent in the various locales, eg en_gb "Feb 28 2020" (which I would consider an intermediate variant as no weekday and month abbrev) vs de_de "Sonntag, 1. März 2020" (which is really the long variant, full weekday and full month).
en

**Comment by DerGuteWolf** [comment]
@paulcockrell: I understand, but this is unfortunatly currently not localisable....

**Comment by paulcockrell** [comment]
@DerGuteWolf It's fine, I understand making it valid for various locales important for other users. So I appreciate the change you put in. Maybe it's just me, but I do need reminding what the day of the week is, they all blend in to one  :-)

**Comment by DerGuteWolf** [comment]
see #183

**Pull request merged**
