### PR TITLE
clock_info: prepend swipe listener if possible

### PR DESCRIPTION
**Pull request by thyttan**
attempt to fix https://github.com/espruino/BangleApps/issues/3355

### CODE REVIEW

**Comment by bobrippling** [comment]
Thinking about this more, I suppose it's a good change to have since we want to be the first listener always, as when we don't have focus we're totally "transparent", if you will:

https://github.com/espruino/BangleApps/blob/b934653ff0c91fe649f9add2068de2fbb7e65d2d/apps/clock_info/lib.js#L256

**Comment by thyttan** [comment]
Yes I think something like this should go in. I was thinking maybe wait a week as to not conflate some bug that might arise. But the risk feels small so we could also just go ahead.

**Comment by bobrippling** [comment]
Yeah I think we merge it, it's low risk

**Comment by thyttan** [comment]
I'll merge this now then.

**Pull request merged**
