### PR TITLE
degree symbol replaced

### PR DESCRIPTION
**Pull request by lawern**
In the newer espruino versions, the degree symbol is not displayed correctly for the temperature in the clock.
I have therefore replaced it with an apostrophe, as shown in the screenshot.

### CODE REVIEW

**Comment by bobrippling** [comment]
This might be related to recent font changes: #3312 / espruino/EspruinoAppLoaderCore#60

@jordimas / @gfwilliams what do you think?

**Comment by gfwilliams** [comment]
Just checked into this. The Font used is provided in the file, AntonioMedium - it contains capitals/numbers, but no degree symbol (176) or anything above char code 94 - so I think this is the right solution.

I'm honestly not sure if Espruino ever would have properly displayed this in any version, but maybe Locale used to use `'` rather than the degree symbol?

**Comment by bobrippling** [comment]
Sounds good, I'll merge. Thanks for the fix @lawern!

**Comment by lawern** [comment]
Fixes #3128

**Pull request merged**
