### PR TITLE
Choozi - Recombine app files and some improvements

### PR DESCRIPTION
**Pull request by halemmerich**
- Combine code for both apps
- Better colors for Bangle.js 2
- Fix selection animation for Bangle.js 2
- New icon
- Slightly wider arc segments for better visibility
- Extract arc drawing code in library

### CODE REVIEW

**Comment by halemmerich** [comment]
Forgot to give lib the center values as parameter for completely custom arcs.

**Comment by gfwilliams** [comment]
Looks great - thanks for pulling out the arc into a library!

**Comment by gfwilliams** [comment]
Is there a reason it's still a draft though, or shall I merge?

**Comment by halemmerich** [comment]
Will push a fix for the lib missing the center point argument in my lunch break :)

**Comment by halemmerich** [comment]
@gfwilliams This is now ready for merging :)

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
