### PR TITLE
New clock - Numerals

### PR DESCRIPTION
**Pull request by ps-igel**
It's a simple clock only showing the time with big numerals in different colors.

### CODE REVIEW

**Comment by MaBecker** [comment]
Hi, I like clocks.

Can you please add a ChangeLog file. You can start with the one from here

https://github.com/espruino/BangleApps/tree/master/apps/_example_app

**Comment by MaBecker** [comment]
Close, sorry for not beeing precisely, please use the same text :)

**Comment by ps-igel** [comment]
Sorry, I tried being original here. ;-)

**Comment by gfwilliams** [comment]
Nice - thanks!

**Pull request merged**
