### PR TITLE
[Alarms & Timers / Scheduler] Fix bug with alarms not firing when repeat is set to "once"

### PR DESCRIPTION
**Pull request by alessandrococco**
In #1822 I merged the "repeat (Y/N)" and "days" menus. Before my PR a "repeat _once_ alarm" inherited a dow = 127 (_every day_) but in my updated app I allow a free customization of the days of the week so if the user select none of them then dow = 0 and the app assumes that the alarm will fire _once_.

I didn't noticed that an alarm with dow = 0 will never fire because the filter will discard it!

This PR fixes that (I also changed the filter conditions to be in the same order so they are easier to read)

---

Anyway, could the `rp `attribute be removed? The dow alone should be enough to understand if an alarm will run multiple times (dow > 0) or once (dow = 0). What do you think?

### CODE REVIEW

**Comment by storm64** [comment]
> Anyway, could the `rp `attribute be removed? The dow alone should be enough to understand if an alarm will run multiple times (dow > 0) or once (dow = 0). What do you think?

Sounds reasonable to me.

**Comment by gfwilliams** [comment]
What if I want an alarm that fires once on Monday, but not every Monday? That feels like a useful thing to be able to do, but this logic would break that - a non-repeated alarm could no longer have days of the week set.

But it also seems to me this makes the logic more complicated when actually the fix is just to ensure that `dow` gets set to 127 rather than 0? That should be pretty much a one-liner?

**Comment by gfwilliams** [comment]
> I can configure an alarm with repeat NO and days "MTW____": what should happen in this case? Today is Friday: the alarm will fire once on Monday and then it disables itself but then the TW days will be ignored because repeat is NO, not really clear imo.

Yes, that's true. It is a bit confusing. But I guess it's what you might expect.

How about for now we leave your menus as they are since they seem to make sense, but we leave the scheduler as-is so that if someone wants to do a custom app to enable no repeat with days of the week they can?

Then I think all you need to do is ensure that `if (!dow) dow=127` - which you could even maybe do in setAlarm?

**Comment by alessandrococco** [comment]
> How about for now we leave your menus as they are since they seem to make sense, but we leave the scheduler as-is so that if someone wants to do a custom app to enable no repeat with days of the week they can?

Ok!

> Then I think all you need to do is ensure that `if (!dow) dow=127` - which you could even maybe do in setAlarm?

Ok but I need to make some tweaks in the alarm app because a dow of 127 will print the full MTWTFSS string. I'll update the PR.

**Comment by gfwilliams** [comment]
That's great - thanks!

**Comment by gfwilliams** [comment]
Great, thanks!

**Comment by alessandrococco** [comment]
lol, it wasn't ready yet 😄 

I opened a new PR #1860

**Pull request merged**
