### PR TITLE
Dozenal Time

### PR DESCRIPTION
**Pull request by numerist**
A dozenal Holocene calendar and a dozenal diurnal clock. For information about them, go to https://dozenal.ae-web.ca/pdf/dozenal-calendar.pdf and https://dozenal.ae-web.ca/pdf/about-short.pdf. They've been in use for some years.

In the dozenal number base, ten and eleven are single digits, and 10 is a dozen. The clock simply divides the day by successive powers of a dozen. The day or parts of it may be divided easily into halves, thirds, quarters, sixths, or twelfths (dozenths). There is no conglomeration of bases two, ten, twelve, and sixty, as in the current system of time measurement.

The annual calendar has a dozen months of 5 weeks each, each week having 6 days. The 5 or 6 days beyond 360 (dozenal 260) are added where they keep the season beginnings the most accurate.

The year itself begins on the December solstice. Because that always happens, there is no need of a leap-year rule to keep the seasons from drifting.

The epoch (year numbering) begins in the last year when the perihelion coincided with the June solstice, near the beginning of the Holocene era. That astronomical basis makes the calendar free from politics, religion, or geography.

While the year number remains cardinal, BTN5 toggles between cardinal and ordinal for the rest of the calendar segments. BTN4 adds or removes a quickly changing digit to or from the clock.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great - thanks! I'll also just add your great description at the top of this PR as a README file in the app directory, so there's a bit more information available to others who are browsing apps

**Comment by numerist** [comment]
Thanks. All is well.

Not being a computer person, I don’t know whether slight updates in my code require a new pull request. The changes have appeared already in my github.io but, after a few hours, not in the general bangle.js uploader.

—
Paul Rapoport

**Comment by numerist** [comment]
Ignore this question. I submitted a new pull request. Having to do so makes sense.

**Comment by gfwilliams** [comment]
Hi! yes, your changes will take effect in your personal copy of the app loader on GitHub, but you have to submit a PR (and we have to accept it) before it goes live.

Also `banglejs.com/apps` is updated manually, so that can take a few days extra

**Comment by gfwilliams** [comment]
Yes, I haven't updated the main repository yet. I will do soon though

**Pull request merged**
