### PR TITLE
waypoint_editor: allow text waypoint names, allow marking current GPS position

### PR DESCRIPTION
**Pull request by pavelmachek**
Plus some cleanups as a bonus.

I wanted to ask: would it be okay to merge this with "waypoints" app? app.js file is small enough that keeping them separate is just complicating things and taking more resources...

### CODE REVIEW

**Comment by pavelmachek** [comment]
(Plus, "waypoint_editor" name is descriptive but quite long. Merging this with waypoints would help with that, too).

**Comment by bobrippling** [comment]
> would it be okay to merge this with "waypoints" app? app.js file is small enough that keeping them separate is just complicating things and taking more resources

> Plus, "waypoint_editor" name is descriptive but quite long. Merging this with waypoints would help with that, too

Sounds good to me - Gordon's done [something similar](https://github.com/espruino/BangleApps/commit/91728c147) in the past. Would you prefer me to merge this PR before your merging with the waypoints app?

**Comment by pavelmachek** [comment]
I'd prefer to merge this and base new work on top of it (better for my workflow and not sure when I find time).

**Comment by bobrippling** [comment]
Sounds good, in that case thanks for the PR!

**Pull request merged**
