### PR TITLE
Stweedo patch 1

### PR DESCRIPTION
**Pull request by stweedo**

### CODE REVIEW

**Comment by stweedo** [comment]
Updated metedata.json to include forgotten quotation marks

**Comment by gfwilliams** [comment]
Hi - did you intend to close this? I think it got automatically closed because you deleted the branch?

**Comment by stweedo** [comment]
Hi Gordon,

What happened was I made a branch in my repo by mistake and then accidentally did a PR to the main repo instead of my own.

This is all new to me.

Thanks

**Comment by gfwilliams** [comment]
No problem at all - yeah, it can take a bit of getting the hang of. Pretty sure I've merged it all in with https://github.com/espruino/BangleApps/pull/2715 now though?

**Comment by gfwilliams** [comment]
Great! You could do it by a settings page on the watch, or potentially could even pull it out of the current theme (since there's foreground, background, and a highlight color you can specify)

**Comment by stweedo** [comment]
That's a good idea, I've mostly finished with the html interface and having it write the color to a settings.json file would be the way to go I think. That way it's quick and easy to set it from the app loader and can also be changed on the watch itself if needed. I'll have a look at the settings tutorial tonight.

It's set up as an interactive live preview of what it will look on the watch. Kind of fun to mess around with.

image

**Comment by stweedo** [comment]
// Clock with large colored digits using the "Londrina" font and a slightly larger "Londrina Shadow" font on top

Graphics.prototype.setFontLondrinaSolid = function() {
  // Actual height 59 (64 - 6)
  return this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('ADX/4AJHv/gBI8/+AJHj/4BI8P/gJHg/+BI8D/4JHgP/wBQbAFEBBJEHKBEfKCJuBUI6CBUI8P/6hHn//UI//AAImHAAJQFg4JCKAsfBJF/Do5XBAAI7FEwZPFEwZtFEwaBEEwYwFEwYwFEwaKFPwImGCYh1FTgKTHGISxGSYTPGJ4TjHWA5tCZw5QBew5QBJooACgwIHAELmIOAReGRwR8GBIhpEVgYeFBIozDBIr9DBIooDBIooDHYjhEBIxRCBIwyCdAXgbAQyCO4LxCBwP+dAb7Dv48CBIpLBHgRVEG4JvCv4iCFARGCn5fDG4JGCEQgtEEQgtEKAgTBKAgeCa4TmFS4w8BS46rGBISNCagwtCbw4JJGQoJDYAoJDFAoJDFApFCKIwJEDwavDaAjDECgq9CAEMBEpEDcYQAFg5DGQYRXGNwYJJRIirEHg4JBHg6BB/AJIIw4dBIw47BCY7dBE4LrCBwUHfgoiCc4oABSoQJGb4QJGOYTcCAAZzCHAQADOYRQBAAhzCKAIAEKF7+IAHUHNQR0BKASOCMAJVBKYaiBB4KhEB4ihEBIQPBUIgJCB4KhEBIQPBUIgJCB4KhFbwSbDKAQJCwAJCKAToC4AJCKAToC8AXCKAToC+AJCeQuABITyEBwIrB57yEBIeHeQgJBGoODeQgiBBIOBKAYuBBIWAKAa0CH4JmBKAQQB4DHCn5QE+AJCj5QE/wWB8ACBKAYAC8AqCKAQAC+AZBUIoJBDIKhFaoahFBIRQDEQKeDKAY8DR4TyFR4gJCGQQJBKAjACBIJQELYQJBKAgeCHAV/KAQPCJgQAjj5LCAAt/IIRPESQiMDBIQFCe4QJDLIReBNwiSCRgJkDPAIJDFAahBIwKRBVYojBYgQJCG4JQBYgRfCBIItCBII8CIIPwgfAEQLyE+DlBHgg3B+DlBGQJfCBITlCIwYOB/DlCPIbICcoQ3BIwQiBBIPgEAJGCv/+CwPwEAKwCEQQgDKAQiCv/8ewgYB4AWBBIJQCIwRsB8JQDRAQAEWogAEKAQbBBI48BAAhaCL4IAELQTFCBIw8GBIQyGfgZiBCY4yFBIYyFIoQoGLIQUEDYYAjh4oIeAgAEM4JPEBIgeHLgKBDAAZbBeAQADUYTwCBIzwCPIzwDAAUHRg6sEKAoJB/hQGNgP8v5QFBIP4n5QFNgPwj5QFNgPgh5QFBIRIBOw3ALgJQEBIRwCKQYdBCAIJCKQQ7Bf4hSCJ4IAEKQR3DAARSCRYYACKQSfDAAazEAAhSCBIxQEAAhQEAAhQSWwoNDBAxeCdApeDdApeDdAqvDGI4AkHAJCHS4fwBwJbDS4R/BI4iXCaAN/aYSXDaAL3DS4gOCG4ToDwAOBPQToD4AOBWoToD8AOBfgRQGGQZQFLYZQFGQZQGMoRBBBYJLCHgQEBx4kBGQJvCIIPHMIV/IwQOB8YuCPIn/+IkCFYJGCv/4EgQ3BQYU//gkCG4JQD/wkBwAJBKA3gKBH8BwJQE4aPCBIZQB8IJDUInwBIahE/CZCBIhQBTISrEKALgDMgZBBawbyFwDMCBIZQB4AoDPAQbBNgQJEKAT1DBIZQBcIYnCKAIhDJ4YAEgIcDAFhOEAASEBAALcCKIaqGBIwUEBIjTDBIpvEBIo+DBIqSBagQJEFAYJFFAZZDdA4AEKIT6EGQgJG/jyD/4MDHgTQBDAIKDHgQJGHgTyCEIRvDv4sBEIPPIwc/FgIJB4JGDNwIrC4AJDMgI2Bv/An5QCHAIsBn/gj5QCHAIOBj/wEYYkBEoMP/AjDEgIeBg/8EYJaCX4PwEIIJEDAP4KAJkEBwIyBBIoQBIIIrBNwYQCa4YJDGQOAZoTyDAwPAS4QJDFAItBBIovBEYIhBBIkHBIIhBGIYAEJ4YAgsAEDgL8DG4kDfgpLDHoTYDOgQZCbAYFCeQhzEeQg2CG4LyEGwTLCSwoOCDIZQDEQIZDKAbACKAzUFKAa1BWwZQDeQpQDBAJBF4BOCKovgIgRpF+BECPov4IgQJEKAJECTYv+IgSvFDYRYDPwhYESQgJGK4ZiDKAZiFKAZiGSYhYEU4hYEKAgJGKARiEKAhiEKAhYEKAhYFIwZYFIwYIGAEcBMwxQBn5xFI4KbCJQgGB8ByGQYSQGYAa4FBIp9DBIooDBIqvDbwbXFBIwyCdAb/FdAQADYgQJGHgTyCAAOHHgbyB/A0BwJvDeQP4CwOABgLyD/gWB4BBBIwQYBCwPgG4JGCDAIWB+AgBQYQYCEAZQEWgP+IIRQG45QFAAhQEBI6rGUKgJCHgirEHgwJCNgLyLz4JFGQS0BBIgoCQgInDFAaRDBISOBNQJzBBAYAzv48BgKqDN4ZXBLQgJCbQN/boQJDDYM/DwiyDe4JvDTwa6BFAYJC/CRB+DeF/yDB/joGTYIyDdAfAeRHgDAIyCIIIAB+AOBZQT8D/gOBMoT8DHgoEB/AlBKoI8CBIRsCBgTnCMQXAPIgiBCwJ5FWgRGBCwJGCJYIJBEARGCF4YJFEQU/LQRQCTgR7DKAgAFKAYAFKAYAFKAQlDBIqhDVwahFBIo8GdAQ8GeQwJGGQoJDZQYxELYxPCCgwIDAAcBEwYA/QoK8Bn5IFMQUfeQQJDOwMPeQSZDDQMHeQQACn4aBXYIJEj4aBGoYACh4aCTA4rCVggkBKCQAkA='))),
    46,
    atob("DyEqHigoJikpJygqEQ=="),
    81 | 65536
  );
};

Graphics.prototype.setFontLondrinaShadow = function() {
  // Actual height 63 (67 - 5)
  return this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('ADX/8AJH4EQBI9AhwJHkEHBI8QgeABI0IgPABI0EgA8HgUAuAJGgMAnAyHwEcKBH+BI8f/4JHg//KA49CDxATInFgBI/wKA8D4BQHh8AUI88I4IJG/AfBHgsBSgKhGg4QCUIseAYShFGAJbCK4oDC/hXFGgQJEK4I0CBIgmDh5SBEw0/IoYmDgF/AgYmDgLIEvgwDbggmDj4wEXAd/OwkwAYX/RQkYHwT5FhgmCMIkAgwmHDQJNCXYxNBEwoABwAmGKAV/LgYADiJNFQQYmHV4wAa/4ABMwwGCv49FWI8AjgEDhyiGP4SGDWwbGFBIsIAYUQBIkCBJAoDBIooDHYgABnArFcooCCg/4AYToDbwP/BQIyCH4MDRoQHBYoLoDwE/SANwCwSXDvA8D4EDbwUESYdggITCFoKYCQQIJCFoRkDRwYtBHwJaBWweAgItBEQMHAgIRCEYIiBbYJaBAgJQBDAIKCJARSBYYiXFVYw3CS4QJGgYJFjxLDBJAyFBIbUFBIZ8CAAU+ewZXCBIpUDAAP+AgcPDAf8BIcBeAUPAYQACn/wdQPwBIjyDGwgUC/4wEKISPGAAMOR4yRCgwJHjEBR4r9DHIyXCZgwHCPQgACDYI8HBII8HHIMDHg1ABII8GkBvB8EPQgKYCOwMHA4YsChAaFFgUEBIraCgRhIgJ/IKASdFKAaxFKAbFFKAZGHKAxGCKA0A8BQI+BQIuACB//9QQIACRoU/BAn//gJBToQJGAFIzBAYMf/5kBAAM8f4V8gEYLwixBBYKhCPgUYgKUBUIQPDBIShCBIUHBIShCBIUDwIQCHgQJBB4IJCS4T1BB4IaCnAJEuAJCeQT/CuD2CKAToCnAXCKAToCjgJCKAUMAoN+kDyGgf/FYIVBeQYJB2EAbgJQBeQMD/A1BaQJQCwEB8CdB/xQDoAJBH4P5KAY4BBIV4wBQCEgMwJIN4oBQCCAMcBIUgKAkHFoM8DIJQDJoU8DIJQCU4UAjwZBKASdCBIIZBKAR/CgEPNQKhFBIJqBKAQiBVAWAKAY8CBIRQDDAKyC4BQDbwYJBKAcASgIJCKAkGBIXgKAgrCBIJQEbgI7BFwP//5XDAoIJBn//IYUBBIIgBg4JDABV/CQIXBBIngmADBz/wBASsBdoZFDBILtDXgYDBdoiyCBIKcCPoJ/CS4JwCegJ/CUIRjBRgIYCG4KcCXQS1CBIKcBRgKrDGoJQCDYKrCMQMOv/4DAI0BJYUPsEGIgI8CZwMP0EBww8DIIMPyEB8ZVDCwMPxBSBFAJVBgaxBwhDBG4JGBPAWCIYItBIwXAgfBIYItBKoVgFgOAgxvBUwQiB8AWBwYtBBIJVBmA5BEAJQFfYRQDEQIECDYQOBSQQAES4SuCAAd4UIYAELQSXBAAhaCUgQADjwCBZ4QJGQYIJEh4DCMQIJHGQsfAYTNCBIwoFv4EE/4ADDAgID/wJDgYJD+CJGABIgBBI6JBL4qnDSoQAEXYKVCAAbKCeAQJGagRREOAICCAAYQCCwQADEgY0BBI7wCbAkBKA0YGARQFmAzB4BQFEYMH8BQFsDaB6BQFIIMfxBQFAgMfghQEBwU/gUAu//CoQiBvxQBj/AIQKwCvgNCUYcgeYQaCKQUQTgpSChCmIIQK6HIQLYHIQLsHIQYADUYRQBWIxQCYo5QGj5QDgf/+EA///F4MHAgP//AJCKAMBBIX8PgP+EIQRCLwLoFNYREDAAuAvwJHUYIJHj5ECACpiBAAPwL4JCEAAMMKIL9DFgUHBwMMBIShCaAOAgYJCUITQBBwL1CUIfgBwMweQtwBwIoCeQc4WAQFBeQccBwMBIYJQDhwOCKIRQFGQZQFeQxQDeQjmB8E8EIJQDvBQBh48DIIIQBnAfBN4RBBFgIBBFoNwKAQsBAIItBegWAFgIBBFoJGCoBOBAIKBBIwUgFwYJBIwRQDmAJCIwJQDg/8OQRQECwQjCKAMefQiXBKAMPTIQWDKASZCZoRQD2AJDG4JQC5AJDG4RQB8wJGKANxGQZBCKAM4sAJFUISICgEfaASHBOgQJDKALGB/AFBn4JCv//CAJ1BAgIXC/6rB////wJCg//CIM/BIgADgP/FQQAWFIIABBIs/WAMDZQKlGBQJABAAS0ESwQJGgYJIgAeDBIsYAYSpDAAMGAYUgOIqlCmBWFFATeBAAgQCFYYACZwToBGQ7oBAAhbCBgKpBFwUBAYLyBS4KLDSQLyBh4JESYTyB8BhDnBTCg+AEIIHBIwVggeAEIN+gEOLoQ2BOoM/wEHMgY2B4E8oAZBgEMOYVAj0gKAQ4Bh6aBhyIBcYRSB8EQg4jBKAZBBhEDxEAvDJDhyGBMwJaCGAMHLQyhBgeBYwUeS4nAS4RkCNYJBBcIRLBGQdwZoRuCGQU4YYSSBEIccEIQJDgfABYIyBBIcAvhBBJ4MPH4UAj//CIUfCYbnBWwP/AYL3DL4U/C4IAITwICB/6lBAAQ8CJgJiCKwSrDPoTaCUIVAOYZ0BUIUgcQSQCDIUQcQSkCDIS1BHgQXBDISTBGwQRBDITQDXoYZBKAI2CAQRQGCwRQGCARQGHwRQFYQKxCKAhwDn5QEQgd/AQJQCFoUAWwRQCIIUB/wNCwEGIgUD/gJCoEDQYf4BIUggKhCg/wBIUQWgcPbAZQBAAUfLgRQCLAYJDKAJiFKAZiFKAYDCLAZQCC4RYDKARiGKAkHMQZQEh5iDKAkfMQZQELAhQEv5JDKAixCKAqxEOgn/JwpNC/5OFBw40Fj5ZBn4rFv0/gHwgJTEMQPgA4MYLYYjBjoCBgwJFgYCBdocDXItgBIoACFATUEAAIoCBIwoCFYYADKIQJGuDoEGQw/CAAcOAQMwA4YEBg4WDh6GCNAcMBIKEBawQ8BKYMHWwM8G4IvBNwMDwgJBkEAnBaCgPCgEciACBLofhEQMIIwYgBuIgBghGDJYMfAgPMIwbDDGQIJBEoJQBS4oJBgT/GL4KrGS4ahGvCXIMgMAL4IAEHwI8HjwCBHgYhCBITeDFwQJCH4a0BOYaQDvphBn4JCg4eB/geBv42D/EH/kf9/+BIc///4gf/BIgGB+AcBa4IADh57GABYaCGgKvE8BIBgTICGIQEBuCwBbQIJCSAeASYYJCQwNAAoQJDS4MggB7BagkYXQIoCUIcGhC8DBIcDggkEEIUA4QQEoAJCuICB8DyFjARBGQRBBAAMODALGCfgcHCIMOAoJBBIAWcOosPHwPHHgcGBIK/BuAMBHgIWBh+8gE4G4NwCwUHwQ5BG4M4MgUDwI5BG4JGCsEB4GAh43BIwRLB8HAg4RBg5qCBYIgBcALQCDAMcR4YjBKATkEKAS/DAAZQBcYIJFvCrFAAU8UIoACUIwACjwCBbIIAEh4CBgQJIHg0PAwQyFBIZvBAAcfBIRtFv4FD/6CCgP/DAn/AAX+BIcDBIf8JgoJCSoIAig5DCv/wBIbMBK4NgfwIACR4LGBkDyCMIUAnCxBOouAXgMIeQQACoEOXYRcEEgQrDAAQkCFYYACEgYrCAAQkDFYRQEMIMgbwaXC/DTB/5QEn6pBWAJQEh4FCWwwAFA'))),
    46,
    atob("DyEqHigoJikpJygqEQ=="),
    81 | 65536
  );
};

Graphics.prototype.setFontDotGothic16 = function() {
  // Actual height 18 (17 - 0)
  return this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('ADkf//gB5l4gE+AoUDCgIIBAAsggU/gHf8f8wEMkEDv+P//DBAQzBh0P4fCjEZw0G///7kwsUMjHx/kYn0H8Fj/lwwd4n/4g//wF/+F/g08/+Ij/Agfwvv+n/hxF4sUfjGOs0/h+Hw4RBzBoHMQQARh/8R4PnwF9DgIMDgkAhvgj9//+D/4eIgkQgPMgEbgEHAIP4gFwQwMAjnACIIVBoEAmEASgIyBh/+BAwRCAAMB+EAvkAjxeNgICBsEAjEAgwIBwAICHQQADnEAhwzBB4IAKD4MPwABBCYJnCAIeAFoRbBa4PBwEZwEGsEBYINlwEYv/8NoRRJDgP5/4PEgHw/F8v0YmOYhlmgcZwOGrHBw/gsHwhEwmEeh5TBs0GCIVgsOWnFh/fwni9BboKoBgfAg/wg/Eg/BHwsEj/5g/+uODMQPBzEws0MjIIBoF/cYX/8BrBjARHKAWf4HD8LGHvOA+Fj4Eb8EH4ChDj0H9/BxxiEzEYsuOjF+UIMegfxgP+uFg41gjOYg1mgOZBAMf/8D/7kH8PAnFwh0cexYABnF8h0fgeHJYIAFiEAhxjBfgOwgHGNwPAjEwh0OgbtCgEMoEDDAPEgExBA4ABmEQhkOgODEYUMsAsCtA1CE4M4gBaBAIMGgf5wP+sFjzkwgP4gE8doP8PoPB/847/mk0JxP+sd/zF/80P+AqBXoP4gfwg+MVYMAvHAB4V/OAPn//5/41BYoVmgzOCrHhw/v4Hx8E//C8BeANmgEZwEGMoOWgFh8PwmF4v//z//8wRFzEAsuAjF/eQP+EoI+CGoI+IsFByEAk5QEsEYjEGg0BwOABAUQgi1BKBAsDy0YsPn+Ex/BQD8AUBgOAZgMAjC9BgI1BCIILBAAwuB8AKHWoUAvgmIBAI1B4//8IsEuEAmYSBsEMhz5B45ZBgECKAgjFFg8ACIKhB/E8A4P4gEDeAOAn/AEYfj//wHwMOCYIrBAgkfh4RDeR4RDeQkDJgPAsEwjEMguGgF/gBCBgf/VAPgOYIjBzED80AnNgh41B4f/i7yMrH8g/v8HwvE8mEfx8GmFmgzyH8fwmFwiCbHGoJNBBAgRBBQOHNYKzKOgIRC4BkBNIKaBg4TBnEAvED/kf/EHCIXgeQQUBQQN8Zwc/a4J0BRAMBz4RBAAMOFQI7B90A+fh+E+CIOeGwJPBjhPB4CtB8AGBj61Cj0AgjXCDQMPzEOs0cjOcMQI1BgFkgEIIwIAFLIP/LIPQgE0gEMBoaCBg5NBngUBPocBM4KYBAAQ+BhsAgYjB76oCABMOL4IBCgYIBCgKTBgAuBAAUCAQIJBkBZCBBYABbgSMBZAIqCAA0z4E9/EMs0DSYPGsExzEP/0Aa4MAkP//F//0BwOA4FgmEYhkGgYIBn/AQ4MBLQP/bIIRFgOAdoMMuEBiEAvz7B4EYCIosBnEYGoMfHwM/QQPwgxQHcgI1CnpmCZ4JyBg//8///OMgFja4KCBAAMH00D//A48wmPMhlzgcc4H9mE+vkIgw+Bw//8D1BFgcAUwiPBv6PBAAw+BbAgAKoEAmArBOgMbWYQACPokOGYPAgOQgFkgEx4CPBhDyEAAgaCBZBHBn/4gxiDn/gNIIwCWYQRCfYLEBOgRRCCIIIBCIMH/EB/DyNa4IRBWYX/+EYfoMMgY/B4BiBsED+EAvhcBeQPAg0YCIkwmEOBAIjDLoJQBLIROBKAgNBPwcHxkD++A41gmOYhlmgcZBAU9/EHngWCOgd//ihC4BrEUIaRBIAIIBSAVggEYBAJHCWYIpBMgMAnCbDAgIBBBoP8AYSRBDQUB8DyBh4zBBoTFD+DzBwHw8EcuEAIAI5BCwMe+EPhwRC4EQn6xB4bsBIIPgAIKzBWoQJBkBrBj0DhuA4aPD40DsI1BPoMIPYQADgkB/v+v8/6EAmi7CABM/a4IMJgkAhqLBEYPf7/gBIIAJEAJ4BOwLuCaYYIBgAA='))),
    32,
    atob("CQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkA"),
    18 | 65536
  );
};

(function() {
  let drawTimeout;

  function draw() {
    const x = g.getWidth() / 2;
    const y = g.getHeight() / 2;
    g.reset().clearRect(Bangle.appRect);
    const date = new Date();
    var hour = String(date.getHours()).padStart(2, '0');
    if (hour[0] === '0') hour = hour[1];
    var minutes = String(date.getMinutes()).padStart(2, '0');
    const timeStr = hour + ':' + minutes;

    g.setFontAlign(0, 0).setFont("LondrinaSolid").setColor(0, 1, 1).drawString(timeStr, x - 1, y);
    g.reset().setFontAlign(0, 0).setFont("LondrinaShadow").drawString(timeStr, x - 1, y);

    const locale = require("locale");
    const dayOfMonth = date.getDate();
    const month = locale.month(date, 1).slice(0, 1).toUpperCase() + locale.month(date, 1).slice(1).toLowerCase();
    const year = date.getFullYear();
    var dayOfMonthStr = dayOfMonth.toString();
    if (dayOfMonth === 1 || dayOfMonth === 21 || dayOfMonth === 31) {
      dayOfMonthStr += "st";
    } else if (dayOfMonth === 2 || dayOfMonth === 22) {
      dayOfMonthStr += "nd";
    } else if (dayOfMonth === 3 || dayOfMonth === 23) {
      dayOfMonthStr += "rd";
    } else {
      dayOfMonthStr += "th";
    }
    const dayOfWeek = locale.dow(date, 0).slice(0, 1).toUpperCase() + locale.dow(date, 0).slice(1).toLowerCase();
    const dateStr = month + " " + dayOfMonthStr + ", " + year + "\n" + dayOfWeek;
    g.setFontAlign(0, 0).setFont("DotGothic16").drawString(dateStr, x, y + 48);

    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = setTimeout(() => {
      drawTimeout = undefined;
      draw();
    }, 60000 - (Date.now() % 60000));
  }

  Bangle.setUI({
    mode: "clock",
    remove: function() {
      if (drawTimeout) clearTimeout(drawTimeout);
      drawTimeout = undefined;
    }
  });

  Bangle.loadWidgets();
  draw();
  setTimeout(Bangle.drawWidgets, 0);
})();

**Comment by stweedo** [comment]
Let me know if i should remove these or post them up somewhere else, but I would love to hear your feedback on this if you have time to try it.

**Pull request closed without merging**
