### PR TITLE
New app - Smart Switch, for controlling smart devices via EspruinoHub

### PR DESCRIPTION
**Pull request by wdmtech**
My first app - I love the Bangle.js!

demo gif

This app works by sending (on swipe left/right) advertising data via Bluetooth LE advertising to EspruinoHub.

Thanks!

Will

### CODE REVIEW

**Comment by gfwilliams** [comment]
This looks really cool! It's great using EspruinoHub too!

Just checked on this and it's just because you've got `"type": "bluetooth",` - the app loader/launcher expects app/widget/etc in there. By having `bluetooth` the launcher is just ignoring it.

Just remove that line from `app.json` and you're sorted :)

**Comment by wdmtech** [comment]
Thanks Gordon! That was it! 

Just a few bits of documentation to go and I'll push it up 😄

**Comment by wmurray-es** [comment]
OK! First draft of documentation done.

Let me know if there's anything else I need to do, otherwise this is ready to roll.

demo gif

**Comment by wdmtech** [comment]
OK! First draft of documentation done.

Let me know if there's anything else I need to do, otherwise this is ready to roll.

demo gif

**Comment by gfwilliams** [comment]
This looks great! Thanks for the detailed docs as well!

**Pull request merged**
