### PR TITLE
[Messages light] - new message GUI app

### PR DESCRIPTION
**Pull request by Rarder44**
a new app that replaces the message app GUI.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Let's wait until https://github.com/espruino/BangleApps/pull/2297 goes in and then we should be able to tweak and merge this and the module renaming won't be needed

**Comment by Rarder44** [comment]
yes yes, no problem!
since perhaps the work on the message could be long, I thought of starting to publish this (also for my order) and then, when the new methodology is completed, modify this app.
(I also uploaded it, so in splitting the message, there is a reference to what could be needed in a "custom" GUI message)

**Comment by gfwilliams** [comment]
Yes, ok - makes sense. I'll merge this now and I think we can remove the extra bits pretty easily later

In future, it'd be handy if you could make your version numbering have 2 decimal places like other apps though? - even if you want to start with `1.xx` instead of `0.xx` is just seems less confusing for users.

**Comment by Rarder44** [comment]
oh ok, no problem!

**Pull request merged**
