### PR TITLE
settings.js for metronome

### PR DESCRIPTION
**Pull request by bengwalker**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - looks great! Was there a reason for changing all the file permissions, or was that just an accidental commit?

**Comment by bengwalker** [comment]
Wow, I don't know how this happened. This was a mistake. Do you know how I can revert this?

**Comment by gfwilliams** [comment]
That's a good question! The easy way would be to clone the repository into another directory, copy your new files in and then commit that.

... Or you can:

```
git checkout -b oldbranch
git checkout origin/master
git checkout -b newbranch
git checkout oldbranch -- apps/metronome/ChangeLog
git checkout oldbranch -- apps/metronome/...
git checkout oldbranch -- apps/metronome/...
git checkout oldbranch -- apps/metronome/...
```

And then you should be able to commit that new branch (made up out of just the files from the old branch but nothing else?).

I can do that for you if you want? It'll have my name on the commit though.

**Comment by bengwalker** [comment]
I have created a new pull request https://github.com/espruino/BangleApps/pull/423

**Pull request closed without merging**
