### PR TITLE
load only clock apps

### PR DESCRIPTION
**Pull request by matjaz**
Haven't done benchmarks, how internally Espruino works.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - this looks great. I'd moved to doing this in other places but it seems I didn't spot it here

**Comment by matjaz** [comment]
Maybe sth like

    clockApp = require("Storage").listAndRead(/\.info$/, file => {
        const app = require("Storage").readJSON(file,1);
        if (app && app.type == "clock") {
            return app;
        }
        // returns undefined, so it skips this file
    })
    .sort((a, b) => a.sortorder - b.sortorder)[0];

**Comment by gfwilliams** [comment]
That's an idea - so without even allocating the array of filenames.

Although I guess since we're filtering with a regex anyway the list size will only ever be the amount of apps, which is probably <100?

**Comment by matjaz** [comment]
yeah, array of all names, and more importantly contents of all files at the same in memory.

yeah, not sure if we could have more than 100 useful apps. maybe widgets/workers.

**Pull request merged**
