### PR TITLE
Created Digital Clock Face

### PR DESCRIPTION
**Pull request by Shashank-Prasanna**
This is a pull request to add the Digital Clock Face to the official Bangle.js App Loader. The short name is Digi Clock, and it has all of the necessary files, including a change log.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great! Do you think you'd be able to tweak your month/day code to use this functionality? http://www.espruino.com/Bangle.js+Locale

So you currently do:

```
 var day = date.getDay(); 
...
  switch (day) {
    case 0:
      day = "Sunday"; 
      break; 
```

But you could just do:

```
var day = require('locale').dow(date);
var month = require('locale').month(date, 1);
```

The benefit is it uses a bit less code, but also if someone installs a non-english language pack it should also automatically translate the watch face :)

**Comment by Shashank-Prasanna** [comment]
Ok yeah will put that in next update coming VERY soon!!!!

**Comment by gfwilliams** [comment]
Ok, great! I'll merge for now then :)

**Comment by Shashank-Prasanna** [comment]
Hello! I have 2 questions:
1: Why don't I see the Digital Clock Face in the App Loader?
2: What is the process for updating the clock? Do I have to make another pull request?
Can you please answer those questions? Thanks! :)

**Comment by Didgeridoohan** [comment]
@Shashank-Prasanna It just haven't been transferred to the stable App Loader yet. Apps are always found in the development App loader first and then moved over after a while.

https://espruino.github.io/BangleApps/

**Comment by gfwilliams** [comment]
Sorry, just pushed it live to banglejs.com/apps - but as @Didgeridoohan says, dev version is pretty much immediate, then banglejs.com only happens every week or so.

> What is the process for updating the clock? Do I have to make another pull request?

Yes, that's right - just another PR and then it'll get pulled in.

**Comment by Shashank-Prasanna** [comment]
k thanks, will make another PR in a few days for v0.02 :)

**Pull request merged**
