### PR TITLE
settings: restore previous menu's scroll position

### PR DESCRIPTION
**Pull request by bobrippling**
To improve settings usability

- [x] Confirm no memory leaks
- [x] Confirm all menus still work
- [x] Find max memory usage (for banglejs 1)
- [x] Document `{push,pop,restore}Menu`

### CODE REVIEW

**Comment by thyttan** [comment]
Tried it - works good on my watch!

I'll leave the merging to @gfwilliams.

**Comment by bobrippling** [comment]
> This is a pretty big change - how sure are you it's not going to break something, and that there aren't memory leaks with the push/pop menus?

I've been through most menus, particularly the ones that don't fit the typical pattern, but I'll do an exhaustive check for memory leaks and thus confirm there's no hidden bugs

> And do you know if it noticeably increases memory usage? It looks like maybe it wouldn't by anything noticeable but it'd be really bad if it stopped working on Bangle.js 1.

Will add my findings from the above check

> It might be nice to have some kind of docs on when push/pop/restoreMenu should be used so that if someone works on this in the future we don't end up with it getting broken?

Sounds good, yes I'll add that

**Comment by bobrippling** [comment]
Exhaustively checked all the menu items, memory usage stabilises on returning out of the menus and I've [noted down](https://github.com/espruino/BangleApps/pull/3630/commits/308956b17b2cdd298650145535391cfc11cc0271) the usage in the readme. Give me a shout if there's anything I've missed

**Comment by gfwilliams** [comment]
That's awesome - thanks! Let's merge then!

**Comment by bobrippling** [comment]
Thanks!

**Pull request merged**
