### PR TITLE
Add scroll and swipe direction system settings

### PR DESCRIPTION
**Pull request by jt-nti**
Contributes to #3048

### CODE REVIEW

**Comment by jt-nti** [comment]
Hopefully the settings make sense and I got them the right way round! I split out horizontal and vertical scrolling so that it's possible to keep the current behaviour, not that any apps use the new settings yet.

**Comment by nxdefiant** [comment]
What does the setting actually change? Am I'm missing something? I see the code for the setting, but I don't see it used somewhere.

**Comment by nxdefiant** [comment]
Anyway iirc default apps must be reviewed by @gfwilliams

**Comment by nxdefiant** [comment]
Wouldn't it be better to invert the direction globally instead of each app individually?

**Comment by jt-nti** [comment]
Possibly but I'm not sure. There may be some apps that always want/need swipes to work one way or another, e.g. to move something around on the screem. Maybe if apps could opt out of the setting somehow? I also don't want to break anything related to entering numbers etc.

**Comment by nxdefiant** [comment]
I would assume that those are the exception. I would still change it globally and handle those when a bug is filled.

**Comment by gfwilliams** [comment]
I think having configurable swipe direction would be nice, but I don't think this way of doing it is a great idea I'm afraid. It'll cause a massive amount of confusion having this global setting which has effect in exactly 0 of the 600+ apps available.

We have the `Bangle.setUI` function which pretty much all apps use to work with swipes, so actually you could just override it like the https://banglejs.com/apps/?q=backswipe app does, and then change the sign of numbers coming out of the `drag` event.

I think at this point, that would be the best way of doing this - just a separate app with boot code that can run to change the default behaviour. Then for people who keep the default scroll direction there's no extra code installed/running - but if you want to change you just install the app, change the settings as you want them, and it 'just works'. It could also include (like `backswipe`) the ability to exclude certain apps if the user wanted

**Pull request closed without merging**
