### PR TITLE
widminbat: Show while charging

### PR DESCRIPTION
**Pull request by notEvil**
I've changed a few parts so it would show while charging.

@LeonMatthes what do you think?

### CODE REVIEW

**Comment by gfwilliams** [comment]
This looks like a good idea, but probably you will also want to respond on the 'charging' event to check whether the widget should be shown? Also changelog/version bump would be needed

**Comment by notEvil** [comment]
True, even though I wouldn't mind the consequence: widget remains visible up to 10m after disconnect from charger. Also, it is easy to force update widgets (long press BTN3) if one desires the widget gone. I can add the event if requested, or describe the behavior in a README.

Regarding changelog and version, thanks for reminding

**Comment by gfwilliams** [comment]
Thanks! I think adding the handler might be better - then it works the same way as other power widgets

**Comment by notEvil** [comment]
Done

I still don't get why we can't just pass `WIDGETS.minbat.update` to `Bangle.on`, JS is a mystery to me xD

**Comment by gfwilliams** [comment]
:) Yes, JS is great like that. The handling of `this` is pretty confusing!

**Comment by gfwilliams** [comment]
This looks good, but the test fails because the ChangeLog is in the wrong order. I'll merge and fix here though

**Comment by LeonMatthes** [comment]
@notEvil I'm a bit late to the party xD
Thanks for implementing this was bugging me for a while as well :D

**Pull request merged**
