### PR TITLE
tetris: major overhaul

### PR DESCRIPTION
**Pull request by Anonymous941**
I've been enjoying this game on my Bangle.js (in fact, I usually only play tetris and chess on it), and the changes @nxdefiant were enough to finally encourage me to work on it :)

I've added scoring, levels, pausing, bugfixes and misc, inspired by NES tetris.  This can use some more testing, but it seems to be working currently.

### CODE REVIEW

**Comment by nxdefiant** [comment]
Is there a reason why you dropped control = 4?

**Comment by Anonymous941** [comment]
> Is there a reason why you dropped control = 4?

Oh, I see that now.  That's because version 0.04 hadn't been updated on the Bangle.js website, so I accidentally made it based on 0.03, which didn't have swipe controls.  I can add that back later today or tomorrow

**Comment by Anonymous941** [comment]
Fixed in 60bab26d838a2b45d15c734741bd00ab26e7d2b9

**Comment by bobrippling** [comment]
Thanks for the improvements, happy to merge - all good with you @nxdefiant?

**Comment by nxdefiant** [comment]
Yes

**Pull request merged**
