### PR TITLE
chargent: fix manual/tap hiding of notification

### PR DESCRIPTION
**Pull request by bobrippling**
Introduced by and documented in #3262.

This also shortens the message length to fit on the screen

### CODE REVIEW

**Comment by bobrippling** [comment]
@thyttan does this fix that [notification problem](https://github.com/espruino/BangleApps/pull/3262)?

**Comment by thyttan** [comment]
> does this fix that [notification problem](https://github.com/espruino/BangleApps/pull/3262)?

I tried this the other day and no, not for my setup as it seemed... 🤷‍♂️

**Comment by thyttan** [comment]
I'm sorry - much of this has probably been user error on my part :)

After reading the readme more carefully I see it's supposed to warn when battery indication in UI said 100 % for a few minutes. I mistakenly believed it should have buzzed at UI indication 80 %.

**Comment by thyttan** [comment]
Thanks!

**Comment by bobrippling** [comment]
Ah no worries! Thanks for helping test it out - wouldn't have found the fix without you :)

**Pull request merged**
