### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by naden**
fixed typos in readme, removed some unnecessary code

### CODE REVIEW

**Comment by naden** [comment]
replaced icons with "Graphics.createImage"

**Comment by bobrippling** [comment]
Looks good, would you be able to update the PR title with the changes? And it looks like there's a lint error introduced in `app.js`, with `hs` no longer being needed, if you could tweak that too?

**Comment by naden** [comment]
removed no longer required import of "heatshrink"

**Comment by naden** [comment]
> Looks good, would you be able to update the PR title with the changes? And it looks like there's a lint error introduced in `app.js`, with `hs` no longer being needed, if you could tweak that too?

good catch, fixed it

**Comment by bobrippling** [comment]
Nice, thanks!

**Pull request merged**
