### PR TITLE
[BW Clock lite] make clock_info border one pixel wider

### PR DESCRIPTION
**Pull request by thyttan**
... to extend all the way to the right.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Closing as duplicate of #2698

**Comment by thyttan** [comment]
It's not a duplicate. This PR is for bwclklite, and #2698 is for bwclk.

**Comment by gfwilliams** [comment]
Ahh - sorry! I had a quick glance and the diffs looked identical - but I guess I didn't look at the filenames!

**Comment by thyttan** [comment]
Totally understandable👌

**Pull request merged**
