### PR TITLE
app: Scribble

### PR DESCRIPTION
**Pull request by enricorov**
A keyboard prototype inspired by [Tertiary Text](http://pebble.rickyayoub.com) for Pebble.

### CODE REVIEW

**Comment by hughbarney** [comment]
This looks brilliant !!!!

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by gfwilliams** [comment]
Actually I just realised the automatic checks fail with this. I've made some minor tweaks here: https://github.com/espruino/BangleApps/commit/aa94abe3befe36085d4e8ab69713c312ba076cef

Please could you check I haven't broken anything? Specifically I know the current `super` handling is a bit odd so it maybe be we can't actually do what I've done, and I just need to disable those checks in the linter

**Comment by enricorov** [comment]
Ya, I don't see issues with the fixed version. Thanks for checking :)

**Pull request merged**
