### PR TITLE
[Icon launcher] Use Bangle.load and Bangle.showClock

### PR DESCRIPTION
**Pull request by thyttan**
Not tested yet.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks good - let me know if it works ok.

Only think I'd say is that `remove` generally gets called from `Bangle.setUI`, so calling `Bangle.setUI();` from it might cause issues. If it does let me know though as that'd be a good thing to fix

**Comment by thyttan** [comment]
>Only think I'd say is that remove generally gets called from Bangle.setUI, so calling Bangle.setUI(); from it might cause issues. If it does let me know though as that'd be a good thing to fix


Adding some prints like this:
```
  let mode = {
    mode: "custom",
    drag: onDrag,
    touch: (_, e) => {
      if (e.y < R.y - 4) return;
      updateTimeout();
      let i = YtoIdx(e.y);
      selectItem(i, e);
    },
    swipe: (h,_) => { if(settings.swipeExit && h==1) { Bangle.showClock(); } },
    remove: function() {
      print('1');
    Bangle.setUI();
      print('2');
      if (timeout) clearTimeout(timeout);
    }
  };
```

After trying to open an app, I get this output to console field:
```
>
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
Before Bangle.setUI() inside mode
```

And then the Bangle reboots of it's own accord.

**Comment by gfwilliams** [comment]
Thanks! Ok, I'll have to fix that then.

.. but if you can remove the setUI and this is tested with those other changes I'm happy to merge

**Comment by thyttan** [comment]
Will do.

One first thing I got now, If i have "one click exit" enabled on Icon Launcher and press HW button on clock to load it, it will immediately load the clock with a "Loading..." message. I'll come back when I figured that out.

**Comment by thyttan** [comment]
Seems to work fine now!

`if (settings.oneClickExit) mode.btn = Bangle.showClock();`

was the problem

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by thyttan** [comment]
@halemmerich Do you think the implementation of 'One click exit' should be kept as is, or replaced by a 'back' function in setUI?

**Comment by Rarder44** [comment]
@thyttan do you mean by restoring the red button in the widget?
I had implemented those features just to make the app fullscreen and to be able to go back to the clock without having to hold down the button for 3 seconds or enter a random app.

**Comment by thyttan** [comment]
Ah, yes I see! Good point.

**Pull request merged**
