### PR TITLE
LCARS clock custom theming 

### PR DESCRIPTION
**Pull request by Ronin0000**
#1577 
@peerdavid 
EDIT: Fixed the bug

### CODE REVIEW

**Comment by peerdavid** [comment]
Hello,

I just tested this and its not properly working on my bangle, so I'm not sure if its a problem on my side or a bug: I updated the app from the source repo as well as the settings of lcars. I changed the color to red and got the following:
screenshot

It seems that the image is not rendered correctly. This is my settings file:

`{"alarm":-1,"dataRow1":"Battery","dataRow2":"Steps","dataRow3":"Temp","speed":"kph","fullscreen":false,"themeColor1BG":"#f00","themeColor2BG":"#FF00DC","themeColor3BG":"#0094FF"}`

Best, 
David

**Comment by peerdavid** [comment]
Update: If I select green, I get the following: 
screenshot

**Comment by peerdavid** [comment]
At least on my bangle its not working correctly as the color of the images (left) is different than the lines (horizontal). Also sometimes no images are shown. So I would suggest to fix this first.

**Comment by Ronin0000** [comment]
Hi, sorry about this I thought I had tested it. I will close this for now and open it when I have fixed it.

**Comment by Ronin0000** [comment]
Looks like it had to do with how I defined some of the colors in the settings page I did not realize that all the hex coeds had to be 6 digits long and you can see that the red green and blue colors are not the same as the other ones.
image

**Comment by Ronin0000** [comment]
Now looks like it is working 
image

**Pull request merged**
