### PR TITLE
fix: 3/4 moon orientation

### PR DESCRIPTION
**Pull request by fbedussi**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Please can we stick with simple version naming though? Eg `0.02` vs `0.01.1`? That's what we use for everything else.

**Comment by MaBecker** [comment]
Cool clock, especially the moon  :)

**Comment by fbedussi** [comment]
@gfwilliams I fixed the version number

@MaBecker in readme I gave credit for having basically copied your widget, hope this doesn't hurt you :-)

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
