### PR TITLE
New medical alert widget

### PR DESCRIPTION
**Pull request by jt-nti**
Signed-off-by: James Taylor <jt-git@nti.me.uk>

### CODE REVIEW

**Comment by nxdefiant** [comment]
What does this actually do?

**Comment by jt-nti** [comment]
It currently just shows the text "medical alert" in the bottom widget space but see the readme for future enhancements

**Comment by jt-nti** [comment]
I've tidied things up a bit and added a screenshot, which should hopefully show what it does

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
