### PR TITLE
`sleeplog` Fix lint warnings

### PR DESCRIPTION
**Pull request by atjn**
The exemption for these files were broken in #3280 but the warnings were not fixed.

I have tried to test these changes as best I could, and I cannot find any issue with them. Maybe @storm64 or @ishidres would be willing to test and confirm that this works well :)

### CODE REVIEW

**Comment by thyttan** [comment]
@Ishidres does your :+1: mean you tested this and found no problem? If so I'll merge.

**Comment by Ishidres** [comment]
> @Ishidres does your :+1: mean you tested this and found no problem? If so I'll merge.

Hi. Sorry I didn't test this yet because I didn't have the time yet and I also didn't really understand what this PR does. Judging by the changes tab it only adds/replaces some "global" vars to avoid lint warnings?

**Comment by thyttan** [comment]
Yes I think this looks unproblematic and welcome just looking at the diff :+1: 

I'll install it and run it over night and merge tomorrow.

**Comment by Ishidres** [comment]
> Yes I think this looks unproblematic and welcome just looking at the diff :+1: 
> 
> I'll install it and run it over night and merge tomorrow.

Tyvm! 👍

**Comment by atjn** [comment]
Yes most of the changes are minor. The only big thing was that I made `tmpWearingCheck` local instead of spilling into the global scope. From my testing, this works correctly.

**Comment by thyttan** [comment]
Merging - thanks! 🙂

**Pull request merged**
