### PR TITLE
added leading zero to hours and minutes

### PR DESCRIPTION
**Pull request by MalteKiefer**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Cool - thanks!

**Comment by gfwilliams** [comment]
Just to say, if you wanted to you could check the 12/24 hour clock setting and use that to choose how you displayed it...

**Comment by MalteKiefer** [comment]
Thanks for the merge

**Comment by MalteKiefer** [comment]
When will it release to the app page?

**Comment by gfwilliams** [comment]
It'll go on next time I push an update - it might be later today, I'm not sure.

However it should be on the dev version immediately: https://espruino.github.io/BangleApps/

**Pull request merged**
