### PR TITLE
[Long Press, Buzz!] Add longpressbuzz app (boot code)

### PR DESCRIPTION
**Pull request by thyttan**
Buzz on long press (assumed and hardcoded to 1500ms) to indicate the watch will be reinitiated per your command.

Would there be a 'better' way of doing something like this? Starting out I tried implementing it by using the init event and buzzing once the watch was reinitiated. But that involved some manipulation of storage which I can leave out when doing it this way instead.

EDIT: Logic changed per suggestions below.

### CODE REVIEW

**Comment by gfwilliams** [comment]
If you just want to buzz when the watch reboots, maybe you could try `if (BTN.read()) Bangle.buzz()` in boot code?

Because generally if the watch reboots the button will still be pressed?

But otherwise what you're doing seems good. You could maybe define vars with `let` in `{` so they're not global, and could always have just one `setWatch` on `both` edges and use `e.state` instead?

**Comment by gfwilliams** [comment]
Thanks! Did you intend to swap it to `if (BTN.read()) Bangle.buzz()`? It seems like the underlying code hasn't changed?

**Comment by thyttan** [comment]
Yes, thanks for noticing. I thought I did that. Will fix it tonight.

**Comment by thyttan** [comment]
Did a fixup of commit https://github.com/espruino/BangleApps/pull/2672/commits/e34728849f0fba853ab27abf229e4d1bb6ec3c5c ("change the logic to buzz at boot instead of before reboot")

**Comment by thyttan** [comment]
Ready for merge.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
