### PR TITLE
Kineticscroll - Implement kinetic scrolling as replacement for E.showScroller

### PR DESCRIPTION
**Pull request by halemmerich**
Sneakpeek at [https://halemmerich.github.io/BangleApps/?id=kineticscroll](https://halemmerich.github.io/BangleApps/?id=kineticscroll)

### CODE REVIEW

**Comment by thyttan** [comment]
Did you consider adding `"ram"` for the drag handling function to maybe improve performance?

**Comment by halemmerich** [comment]
Yes, but I believe the benefits would be negligible, minified it is not that much code and the most expensive operations are drawing the icons.

**Comment by thyttan** [comment]
Ok! 👍 Adding `"ram"` to dragboard made it much snappier in my experience.

**Comment by gfwilliams** [comment]
Looks great - thanks!

**Pull request merged**
