### PR TITLE
New app : GPS Speed Alt

### PR DESCRIPTION
**Pull request by nujw**
1. Tweaked setting to allow a maximum locale time offset of +13 hours to cater for current New Zealand daylight saving time.
2. Adding a new GPS speedometer app.

### CODE REVIEW

**Comment by gfwilliams** [comment]
This looks great - thanks!

**Comment by gfwilliams** [comment]
Just a quick one though - what is the Theme set for? (theme: jekyll-theme-slate in _config.yml)

It seems that since the main site is styled with its own CSS, we probably don't want this? Or am I missing something?

**Comment by nujw** [comment]
Hi Gordon,Honestly, I dont have a clue where that theme file came from. I Followed the tutorial and instructions for adding an app and I only spotted it when doing a compare earlier today before the pull request. 10pm right now so give me a day to work it out. I haven't consciously included anything like that so delete if you like. My intention is to add a bog standard app to the list.  Cheers Mike.
-------- Original message --------From: Gordon Williams <notifications@github.com> Date: 29/01/21  21:48  (GMT+12:00) To: espruino/BangleApps <BangleApps@noreply.github.com> Cc: nujw <mike@kereru.com>, Author <author@noreply.github.com> Subject: Re: [espruino/BangleApps] New app : GPS Speed Alt (#651) 
Just a quick one though - what is the Theme set for? (theme: jekyll-theme-slate in _config.yml)
It seems that since the main site is styled with its own CSS, we probably don't want this? Or am I missing something?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/espruino/BangleApps/pull/651#issuecomment-769667096",
"url": "https://github.com/espruino/BangleApps/pull/651#issuecomment-769667096",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gfwilliams** [comment]
No worries - I'll take it out now and add it to 'gitignore' so it doesn't happen to anyone in the future. Everything else is spot on

I think it might be something that Git tries to put into new projects by default now.

**Pull request merged**
