### PR TITLE
Save messages in append-StorageFile

### PR DESCRIPTION
**Pull request by rigrig**
Implements #1460
* No special case for music (yet), but I think that would probably be best combined with autostart-for-music
* Right now it writes a fresh StorageFile when exiting the app, and [randomly](https://github.com/espruino/BangleApps/pull/1498/files#diff-73da835ccb0c190b9545584c57154f5d990da6450c16586486edd30a7afa8d8bR154) when "modify"/"remove" lines are written and the app is not open. Not sure if that is the best way to go and/or if these are reasonable values.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! There's a lot there so I'll have to go through this later. It looks good but it's a surprising amount of extra code needed.

I think it's probably worth not rewriting it in the messages app (as I imagine that'll be opened for most notifications anyway), but maybe reallocate if the size would grow above 40k (which is the point where storagefile would create a new file)

**Comment by rigrig** [comment]
> it's a surprising amount of extra code needed.

Well, "needed"...

The two main bulks are
- `exports.load()`: it keeps a list of ids while reading messages, so removing/modifying only needs to look at that list, instead of filtering the whole array every time.
- `exports.haveNew()`: basically the same as `load()`, except it only keeps a list of new ids. This might be over-optimized, we could just replace it with `exports.load().some(e=>e.new)`. (But I was happily coding away, so I figured I'd optimize a bit for the widget while I had the thing in my mind)

> maybe reallocate if the size would grow above 40k

I thought about looking at the size, but [the docs ](https://banglejs.com/reference#l_StorageFile_getLength) says "This requires Espruino to read the file from scratch, which is not a fast operation.". So I figured checking that every time we append a message would kind of defeat the purpose. Unless most of the delay comes from parsing JSON?


Also I wasn't sure if every event definitely has an `id` set, if so It would probably simplify some things.

**Comment by rigrig** [comment]
I rebased it onto master, and got rid of separate `exports.haveNew()` code: we don't check for new messages often enough that it needs special optimized parsing.

**Comment by gfwilliams** [comment]
Thanks! I will get on this, I'm just pretty busy at the moment

**Comment by rigrig** [comment]
Sure, there's no rush, and I definitely want you take a good look at changes like this before merging.

**Comment by rigrig** [comment]
Still TODO: look into the [numbers](https://github.com/espruino/Espruino/blob/9327f504c7e0bcdedb29ff47d3cc3bc4122eec9d/src/jswrap_storage.c#L32), come up with a sensible value to compare to `StorageFile.getLength` to determine whether to `compact` the messages file (and maybe make it smart enough to check if compacting will help at all)

**Comment by rigrig** [comment]
Rebased it onto master, and got rid of `compact()`: it already rewrites the entire file every time we close the app anyway, so I figured that keeps it small enough for now.

But we can probably do better:
1. Instead of saving an updated `MESSAGES`, just append changes to the file, and only rewrite it when it gets too large
2. Make it even smarter: keep track of changes, and only write messages that need updating when leaving the app. (Alternatively: compare the in-memory `MESSAGES` with the saved file.)

**Comment by gfwilliams** [comment]
Looks great - thanks! I'll have a play with this branch on mine and see how it's working :)

**Comment by rigrig** [comment]
If you've got some time now that's great, but note that I really meant the **untested** bit for my last changes: I think it *should* work, but haven't gotten round to actually testing it, at all.

**Comment by rigrig** [comment]
I tested it a bit in the emulator and fixed a few bugs, seems to work OK now:   
* I uploaded `messages/lib.js` as `messages`, loaded `android/boot.js` into RAM, and pasted `gbridge/sample_messages.js` into the REPL. After that I checked `require('messages').load()`, and it looked good.
* After pasting in enough copies of the sample messages for `messages.jsonl` to grow over 40000bytes, it erased the file and started a fresh one without losing any messages.
* Doing 
  ```
    M = require('messages').load();
    /* modify M: delete/modify messages */
    require('messages').write(M);
  ```
  only added lines for the deleted/modified messages.

**Comment by gfwilliams** [comment]
Ok, great! Maybe it's best to hold off on merging this just a little more then until you've been running with it on the watch itself for at least a few days.

Just thinking aloud here but the actual file size is ~40930 bytes I think? So if you do a check at 40000 and then you add another 930 bytes of messages, a new file would get created anyway. I think it's unlikely but I guess we could drop the check to 38000, in which case it would be hugely unlikely that any one message would push it into a second file.

I'd also be interested to see if you notice any slowness when exiting the messages app. While I like the idea of the `.write` function, I guess in a lot of cases (marking read/deleting/etc) it'd be pretty easy to just write the extra line directly into the messages file without having to parse the entire thing. It also avoids having to read the whole file on exit even if nothing has changed, and potentially opens the way for not actually ever having to load all messages into RAM (we could just parse the file and read the single message out as and when it was needed).

... but maybe that's one for later when we've got this merged ;)

**Comment by rigrig** [comment]
>  if you do a check at 40000 and then you add another 930 bytes of messages, a new file would get created anyway. 
> we could drop the check to 38000

Good point, I'll adjust that.

> in a lot of cases (marking read/deleting/etc) it'd be pretty easy to just write the extra line directly into the messages file

Sure, but in most cases you probably open the app, open a message (marking it as read), and then delete it, so you end up writing a copy of the message except with `new=false`, and then delete it anyway.   
But we could do this:
* write deletions to the file right away
* keep track of changed messages, only write those on exit   

That way we don't need to parse the file on exit.

**Comment by gfwilliams** [comment]
Could do, but probably not worth the extra effort just yet. Let's set your this PR goes.

Taking of which I used this branch and put in on my bangle and something is very wrong - short buzz and no notifications at all. But I'll have to look into it on Monday

**Comment by rigrig** [comment]
Turns out it wasn't that much effort, so I added it before reading your comment.   
I guess somewhere along the line something broke during some merge/rebase :-(    
I just rebased onto master, figured the easiest way forward was to just fix merge conflicts in the rebase as best as I can, and now try to stamp out the bugs. (Merging in half a dozen options every now and then probably wasn't great for the code)

**Comment by rigrig** [comment]
I gave it a try on my Bangle.js 1, but didn't have time to properly debug stuff yet.
Apart from other issues, I just noticed my `messages.jsonl` now contains exactly this line:
```
{"t":"modify","track":"\u0000\u0012\u0015\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000F\u0000\u0003\u00F0\u0000\u00FF\u0000?\u00F0\u000F\u00F8\u0003\u00F8\u0000\u00F8\u00008\u0000\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 Body Machine | Priest","dur":-1,"c":-1,"n":-1,"id":"music","title":"Music","new":true,"state":"play"}
```
That's from Firefox playing media being forwarded to my phone, so the "Body Machine | Priest" bit is fine, but all the `\u0000` and the fact that there is exactly one line worries me.

**Comment by gfwilliams** [comment]
Ahh, that'd do it! Although if you're not in a clock, do message icons still appear? That didn't work for me either.

Do you not get out of memory errors with the current latest messages app? I've noticed the newish message icon code appears to keep the entire messages list in RAM, which is pretty wasteful.

How many messages did you have? It doesn't look to be like your code should use *that* much extra memory.

**Comment by rigrig** [comment]
>  if you're not in a clock, do message icons still appear? That didn't work for me either.

Whoops, only tested it from the clock.

> Do you not get out of memory errors with the current latest messages app?
 
I don't know, I've been using my [own version](https://github.com/rigrig/BangleApps/tree/new-messages). I didn't get round to merging in either these changes *or* the icon update yet though.   
But it happened with just a few messages, so I'll at least look at it a bit harder.   
(Also: it looks like I broke `music` messages...)

**Comment by rigrig** [comment]
Just tried the messages app from `master`, and getting `LOW_MEMORY` there as well, so I'm going to assume it isn't because of these changes :wink: 
(Looks like drawing the scroller with all messages is what pushes it over the edge, loading a single message works fine)

**Comment by gfwilliams** [comment]
Interesting - thanks! Might have to have a look at that - although I guess for most users you probably have 5 messages max

**Comment by rigrig** [comment]
I didn't mean that the scroller uses excessive memory, just that creating it was the tipping point when the memory ran out. (I didn't test it on an empty watch, so there were already widgets eating up memory)
Anyway, it didn't run out of memory since the widget was [fixed](3be786841e1f65006ef744f7d77daa3a93989aa0), and [this PR](https://github.com/espruino/BangleApps/pull/2065) should help a bit more.

Apart from that, it has worked fine for me the last couple of days.

**Comment by rigrig** [comment]
Whoops, fixed another small bug, and rebased onto master.

**Comment by rigrig** [comment]
TODO: I just noticed that [`7x7dotsclock`](https://github.com/espruino/BangleApps/blob/387e037a6111af84ff3625f2c7091376a5582d91/apps/7x7dotsclock/7x7dotsclock.app.js#L272) and [`hcclock`](https://github.com/espruino/BangleApps/blob/387e037a6111af84ff3625f2c7091376a5582d91/apps/hcclock/hcclock.app.js#L247) load `messages.json` directly, so those will need fixing.

**Comment by gfwilliams** [comment]
Thanks - I'll file an issue for that as there should really be a way to just query the messages library/widget

**Comment by rigrig** [comment]
Strange, I *know* I tested filling up the storage file before, and it worked fine. But today I finally filled up my watch "naturally",and it broke :-(

Fixed now:   
Turns out you can't do this (simplified a bit):
```js
    const file = require("Storage").open("messages.jsonl", "a");
    if (file.getLength()>38000) {
      file.erase();
      file.write(JSON.stringify(e)+"\n"); // throws "Can't write in this mode"
```
So I changed it to
```js
    let file = require("Storage").open("messages.jsonl", "a");
    if (file.getLength()>38000) {
      file.erase();
      file = require("Storage").open("messages.jsonl", "a");
      file.write(JSON.stringify(e)+"\n");
```
and now it works again.

(I'm not surprised that writing to an erased file throws, just that it used to work before, maybe I broke it during some merge/rebase...)

**Comment by gfwilliams** [comment]
Ahh, interesting, thanks! It's good it fails though - that could have led to storage corruption before.

I'm pretty sure you don't actually need an erase. You can just use `w` and it'll erase as part of creating the new file:

```
file = require("Storage").open("messages.jsonl", "w");
```

**Comment by rigrig** [comment]
Rebased it onto `master`.   
I notice this PR has accumulated quite a bit of formatting cruft, I'll see about cleaning that up.

**Comment by rigrig** [comment]
Rebased onto `master` (i.e. message events).

**Comment by rigrig** [comment]
Set it back to draft, as it will need a bit of work(+more testing) to apply onto #2205 

Some good news: now that the `messages` library can be extended, I am using this code as daily driver for my `smessages` custom messages app, so the chance of me running into any lurking bugs is higher :-)

**Comment by gfwilliams** [comment]
> I am using this code as daily driver for my smessages custom messages app, so the chance of me running into any lurking bugs is higher :-)

You mean you're using append-storagefile?

Thanks! and sorry It's taken so long for me to test/merge this one in - it just feels like quite a big one :)

**Comment by rigrig** [comment]
> You mean you're using append-storagefile?

I have been for quite a while now, just not this exact code:   
My own (still WIP) fork already uses the storage file. The difference is that now the [message events PR](https://github.com/espruino/BangleApps/pull/2146) landed, it uses `require("message")` (the version in this PR) instead of duplicating a bunch of code.

> Thanks! and sorry It's taken so long for me to test/merge this one in - it just feels like quite a big one :)

I totally understand, it's a big change and we definitely don't want the messages app to break.   
And waiting a bit doesn't really bother me: I can just load this code onto my watch anyway ;-)

**Comment by rigrig** [comment]
Putting this on hold for a bit, at least until we have a stable `require("messages")` API.

**Comment by gfwilliams** [comment]
I guess we do now have a more stable API - and I think we could in fact just create a separate `messages_sf` app now that would allow both the old and new to coexist?

However, do you think there's a need for this now? I've made a few changes to storage in the last 6 months that has made slowdowns from lots of file writes basically disappear completely - even completely uncompacted it should be basically as fast as right after a compact.

By contrast I'm a bit concerned that reading the messages line by line from a StorageFile may actually end up being slower than the current solution.

With your recent changes to the library it seems we have the option to *not* save messages too, and we already fast-load the `messagesgui`, so with a little more work I think we could probably avoid saving the messages to Storage in 90% of cases (eg. when getting a message when on the clock, dismissing it, and going back to the clock).

**Pull request closed without merging**
