### PR TITLE
New App: Magic 8Ball

### PR DESCRIPTION
**Pull request by johanbove**
Adding my own small contribution to the Bangle.js app store.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - please could you remove the `add_to_apps.json` from version control, and remove the change to `apps/_example_app/add_to_apps.json`?

Also, please can you try and avoid reformatting all of `apps.json`? It makes subsequent merges a nightmare!

**Comment by johanbove** [comment]
I will make the requested changes.

**Comment by gfwilliams** [comment]
Looks great! You don't actually need `apps/jbm8b/app.json` but I'll take that out after merging - thanks!

**Comment by johanbove** [comment]
Thank you Gordon!

**Pull request merged**
