### PR TITLE
android - Handle GPS events from Gadgetbridge instead of connection events

### PR DESCRIPTION
**Pull request by halemmerich**
I had a go at using the GPS events from GadgetBridge as soon as they arrive. This removes the need to handle connection events and fixes GPS not working if for some reason (e.g. config) GadgetBridge never sends an GPS event or stops sending them.

### CODE REVIEW

**Comment by halemmerich** [comment]
There seems to be a condition, where GB GPS stays active sending GPS positions, but the bangle side stops reacting, will have look at that before merging. Disconnecting from GB fixed it, so not that easy to diagnose. Logcat showed the Bangle not reacting at all which is a bit strange since I currently have some prints in there.
@gfwilliams Is it possible to send commands through GB to the connected Bangle? Maybe attach a debugger to GB?

**Comment by gfwilliams** [comment]
Very strange... It is possible to send commands via Android intents - or yes you could debug and then call the relevant functions in BanglejsSupport.

Another option is you could ask it to use a custom App Loader which you could then add the ability to send/receive data into.

**Comment by halemmerich** [comment]
Should be fixed in [https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3132](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3132). I'm waiting and testing until that is merged before marking this as ready.

**Comment by halemmerich** [comment]
I have now used this successfully for a few days of hiking. With the current nightly version of GB containing
[https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3132](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3132) I could not get it to break using the metal box method.

**Comment by gfwilliams** [comment]
That's great - thanks! I've just pushed a new Gadgetbridge version to the play store which has your PR in it, so this should be good now.

**Pull request merged**
