### PR TITLE
Addition of widget BangleBridge

### PR DESCRIPTION
**Pull request by JorgePRamos**
BangleBridge allows the connection of the bangle. js with the banglebridge android app developed as part of the SmartPPE .

Project.Project page: https://jorgepramos.github.io/Smart_PPE/#
Android app page: https://play.google.com/store/apps/details?id=de.bangle_bridge.bangle_bridge

### CODE REVIEW

**Review by gfwilliams — APPROVED** [review]

**Comment by gfwilliams** [comment]
Hi! This looks good.

Just got your mail. Unfortunately I'm on holiday this and last week which is why I didn't merge this sooner. I'm away from the office and I just can't get this live on banglejs.com for you until my return.

Until then, the development app loader should have this on though

**Comment by JorgePRamos** [comment]
Thanks for taking time off you holidays for this.
Enjoy your rest
Greetings
Jorge Pérez Ramos

**Comment by gfwilliams** [comment]
Hi - just so you know it seems there were a few issues picked up by 'npm test' - I've tried to fix these and have now made it live

**Comment by JorgePRamos** [comment]
Thanks for the help, really.
How could I get to know this issues? Just to know where I failed.
Again thanks for your time I appreciate it a lot.

Jorge Pérez Ramos

**Comment by gfwilliams** [comment]
Hi - if you took your branch and ran `npm test` at the command-line on it, it'll would throw up an error/warning about no entrypoint I believe. Usually that should happen automatically but it seems the automatic builds have stopped for the moment

But you can see what I changed here: https://github.com/espruino/BangleApps/commit/2dda299cabf308507c1f5ca6e16dc6b1937adced

**Pull request merged**
