### PR TITLE
back translation

### PR DESCRIPTION
**Pull request by matjaz**
tested and working.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great - thanks for these!

I'll change 'gpsrec' as well so it'll use the `< Back`

**Comment by gfwilliams** [comment]
Hmm - actually it's not quite that easy for gpsrec as it's just using drawString, not a menu. I'll leave that one for later :)

**Comment by matjaz** [comment]
what about `locale.translate('< Back')`

**Comment by gfwilliams** [comment]
Yeah, but it's still got the arrow when that's not required. I guess `locale.translate('< Back').slice(2)` is an option, even though it's a bit of a hack

**Pull request merged**
