### PR TITLE
Test User Input app v002

### PR DESCRIPTION
**Pull request by dapgo**
very basic app, allows to test the bangle.js input interface, 
v.0.0.2: removed warnings, added images and screenshots to README.md

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Looks really handy.

Do you have any changes to `apps.json`? Right now your app won't appear in the app loader without them. The `apps/testUserInput/test_userInput.info` file doesn't actually need to be committed as it's created automatically.

Info here: https://www.espruino.com/Bangle.js+App+Loader

**Comment by dapgo** [comment]
> 
> 
> Thanks! Looks really handy.
> 
> Do you have any changes to `apps.json`? Right now your app won't appear in the app loader without them. The `apps/testUserInput/test_userInput.info` file doesn't actually need to be committed as it's created automatically.
> 
> Info here: https://www.espruino.com/Bangle.js+App+Loader

I think i was following a deprecated procedure. I've just modified the apps.json, added the app.png and a minor change on js.

It will be easy to commit my 2nd and next app :)

**Comment by gfwilliams** [comment]
Thanks! I don't see the apps.json yet I'm afraid...

Just so you know the icon's usually done in JS as well (rather than a `.img`) - did you find some out of date instructions somewhere? Do you remember where? I can try and get them changed :)

**Comment by gfwilliams** [comment]
I believe the issue is it's case sensitive - so you have a folder called `testUserInput` but the app ID is `testuserinput`. I'll just merge and tweak this here.

**Comment by gfwilliams** [comment]
Just sorted! I'll get it live on banglejs.com/apps today. If you're interested in what needed tweaking, it's here: https://github.com/espruino/BangleApps/commit/11530da1726dac368f7dc961246ec286b68bd9a2

**Pull request merged**
