### PR TITLE
fix pull request by correcting icon file name

### PR DESCRIPTION
**Pull request by BenNewell32**
Missnamed my icon file :)

### CODE REVIEW

**Comment by BenNewell32** [comment]
New Repo with emulator and sort order

**Comment by gfwilliams** [comment]
Hi! Are you ready to merge this? There are a few extra files in here that you probably don't want to go in... https://github.com/espruino/BangleApps/pull/596/files

* Did you intend to add GentleNudge2?
* There's `_config.yml` and `apps/benWatch/code_3 (1).js`
* If you're not planning on adding anything to the README files I'd just delete them and remove the `README` reference from the `apps.json`
* The `apps/widviz/benWatch/benWatch-icon.js` file contains `require("../../GentleNudge/node_modules/heatshrink")` - when it should just be 'heatshrink'

**Comment by BenNewell32** [comment]
Gordon! I think I understand the process now! I'm going to develop off of my fork and I'll have a "real" app for you to merge here soon. Thank you so much for reviewing and guiding me to the right spots :)

**Comment by gfwilliams** [comment]
Great - thanks! I look forward to it :)

**Pull request closed without merging**
