### PR TITLE
new Clock watch: TheBin Watch

### PR DESCRIPTION
**Pull request by Vingelar**
Binary watch face for BangleJs2, inspired by RALtec LCD wrist watch

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - any reason for closing this? it looked really good

**Comment by Vingelar** [comment]
Sorry, I don't know how to resolve the merge conflict regarding apps.json

**Comment by Vingelar** [comment]
the data to be added in the end of apps.json should look like this:
{ "id": "TheBinWatch",
  "name": "Binary Watch",
  "shortName":"BinWatch",
  "icon": "app.png",
  "version":"0.02",
  "allow_emulator":true,
  "description": "Famous binary watch",
  "tags": "clock,b2",
  "type": "clock",
  "storage": [
    {"name":"TheBinWatch.app.js","url":"app.js"},
    {"name":"TheBininWatch.img","url":"app-icon.js","evaluate":true}
  ]
}

**Comment by gfwilliams** [comment]
Ahh, ok - I wouldn't worry about that - I can generally fix that very easily myself when I merge. Although it looks like the most recent commit deleted apps.json which isn't ideal - I might skip that one ;)

**Comment by Vingelar** [comment]
Yes, right. I just delete the apps.json in my copy. I was hoping that it just get's replaced by the original one where then the addition code for my app can be added in the end.
I think I need to learn more about github, up to now I was an SVN user :-)
Sorry for the inconvenience.

**Comment by gfwilliams** [comment]
Just merged it - renamed it to just `binwatch` though as generally all the other apps have lowercase names.

I think the merge issue was just that your repo hadn't been updated in a while and I made some massive changes to apps.json maybe a month back

**Comment by Vingelar** [comment]
ok, great, thank You. Can You please give me a hint how I can update my repo ? I first need to update it on Github, then locally ?

**Comment by gfwilliams** [comment]
I think this should do it? https://medium.com/@sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e

I believe you can do either way though

**Pull request merged**
