### PR TITLE
Fixes for alarm, settings & waypoints

### PR DESCRIPTION
**Pull request by nxdefiant**
alarm: defaultDeleteExpiredTimers detection
Fix new alarm when selectedAlarm is undefined

settings: Fix syntax error

waypoints:
- Do not register as type waypoint - show in launcher
- Fixes for Bangle.js 1
- hide some menu entries if textinput is not installed

### CODE REVIEW

**Comment by nxdefiant** [comment]
tests ok

**Comment by nxdefiant** [comment]
@gfwilliams Got a syntax error in settings from 681bd41945, should be ok now

**Comment by nxdefiant** [comment]
Lets fix also the menu entry of #3095

**Comment by gfwilliams** [comment]
Looks great, thanks! Sorry for introducing that syntax error - not sure how that happened. I'd made these changes a while back and only just pushed them so I must have forgotten to test :(

**Pull request merged**
