### PR TITLE
Rinkulainen, Poikkipuinen and Henkinen!

### PR DESCRIPTION
**Pull request by jukioo**
Three new apps!
Rinkulainen - a minimal and stylish watch face
Poikkipuinen - another minimal watch face
Henkinen - tiny app to help you breathe

### CODE REVIEW

**Comment by gfwilliams** [comment]
Wow! Thanks! You've been busy!

**Comment by jukioo** [comment]
> Wow! Thanks! You've been busy!

Thank you! Bangle.js 2 is so great! Hopefully have more time to make some more little things for it soon.

**Comment by jukioo** [comment]
Hey! Just added ChangeLogs to the new watch faces, so now they should be all good to go!

**Comment by gfwilliams** [comment]
Excellent - thanks!

**Comment by gfwilliams** [comment]
I just noticed, but if you're doing screenshots in future, please can you try and make them 1:1? They scale better when they're viewed in the app loader then

You might be doing a screenshot on the emulator? There's actually a button in the bottom right which saves to a file, or even when you're running on a real device you can run `g.dump()` in the IDE and then copy&paste the image that gets displayed :)

**Comment by jukioo** [comment]
Gotcha! Will update all the screenshots in the near future!

**Comment by gfwilliams** [comment]
> Gotcha! Will update all the screenshots in the near future!

Thanks! I just rescaled the images here so it's all good now - just in future it'll make your life a lot easier :)

**Comment by jukioo** [comment]
Great, thanks!

**Pull request merged**
