### PR TITLE
bug fix in menu and optimization

### PR DESCRIPTION
**Pull request by stweedo**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Normally we'd want a version bump but I think you changed this already very recently?

**Comment by stweedo** [comment]
Yes, sorry. This was a quick hotfix I suppose

**Comment by stweedo** [comment]
I found another small bug in the menu. So just one more small commit and everything should be all good now.

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
