### PR TITLE
Add Touch Menu

### PR DESCRIPTION
**Pull request by kyleplo**
# TouchMenu

A redesign of the built-in `E.showMenu()` to take advantage of the full touch screen on the Bangle.js 2.

## Features

- All of the features of the built-in `E.showMenu()`
- Icon support for menu items:
    ```javascript
    menu.items[0].icon = Graphics.createImage(...);
    ```
- Custom accent colors:
    ```javascript
    E.showMenu({
      "": {
        cAB: g.theme.bg2, // Accent background
        cAF: g.theme.fg2  // Accent foreground
      }
    })
    ```
- Automatic back button detection - name a button `< Back` and it will be given a special position and icon

## Controls

- Scroll through the options
- Tap on an option to select it
- Tap on a button again to use it
- Tap on a selected Boolean to toggle it
- Tap on a selected number to change - tap the right side of the screen to decrease, left side to increase
- If detected, tap on the back button in the upper left to go back

## Requests

Contact information is on my website: [kyleplo](https://kyleplo.com)

## Creator

[kyleplo](https://kyleplo.com)

### CODE REVIEW

**Comment by hughbarney** [comment]
@kyleplo this sounds great. Any chance of some screenshots of how this looks ? a screenshot is worth a 1000 words.

**Comment by kyleplo** [comment]
Alright, added.

**Comment by gfwilliams** [comment]
This looks excellent - thanks!

**Comment by Didgeridoohan** [comment]
@kyleplo This does indeed look really nice. But I'm wondering if it's possible to not have the space at the bottom of the screen? I'm assuming it's to accommodate bottom widgets, but if there's no bottom widget it's a bit distracting/annoying.

**Comment by Didgeridoohan** [comment]
Adding a photo to show what I mean:
PXL_20220105_155751715
PXL_20220105_155801234

**Comment by gfwilliams** [comment]
... it might need a `g.clearRect(Bangle.appRect)` at the start to ensure it erases anything in the background of the screen?

**Comment by Didgeridoohan** [comment]
Sounds plausible.

**Pull request merged**
