### PR TITLE
Update 0.02

### PR DESCRIPTION
**Pull request by mjearlb**
0.02: 
- Removed HRV functionality
- Added milliseconds to the timestamps

### CODE REVIEW

**Comment by thyttan** [comment]
Calling @ekwawu for feedback.

**Comment by mjearlb** [comment]
Hi @thyttan - I am working on the continuation of the Capstone project which @ekwawu started. The HRV function is not accurate, so that's why I have removed it. I totally understand why you need approval first though. Thanks!

**Comment by thyttan** [comment]
Ok! When will you want to be using this in classes again? I.e. when would you like to see this merged? Do you have direct contact with @ekwawu and do you think he will respond here? If not I think we can go ahead.

**Comment by mjearlb** [comment]
@thyttan I apologize, I must have missed your reply. @ekwawu has graduated, so might not be active on their account any more. I would like it merged soon so that we can get started programming the batch of watches we ordered. 

Thank you for your help.

**Comment by thyttan** [comment]
I merged it now. It will be available on the [development app loader](https://espruino.github.io/BangleApps) right away. It will probably be pushed to the official app loader in a week or so.

**Pull request merged**
