### PR TITLE
localize miclock

### PR DESCRIPTION
**Pull request by DerGuteWolf**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Please could you also add a note to the ChangeLog and update the version in apps.json to people know it's a new version? http://www.espruino.com/Bangle.js+App+Loader#making-changes

**Comment by DerGuteWolf** [comment]
Version is updated (to 0.03 despite the type in the commit message...) and Changelog is updated.

**Comment by DerGuteWolf** [comment]
@MaBecker : I had first used `locales` in my change for the mclock, cf. https://github.com/espruino/BangleApps/commits/master/apps/mclock/clock-morphing.js exactly because of this problem, I am not sure what to do best?
```javascript
var locales = require("locale"); 
```
looks a bit unusual, here I agree with @gfwilliams .

**Comment by MaBecker** [comment]
this code needs some change to allow 

    var locale = require("locale"); 

https://github.com/espruino/BangleApps/blob/a874d5838c1dee5a5dfb4e71844d961506dd29e9/apps/locale/locale.html#L63-L78

**Comment by DerGuteWolf** [comment]
@MaBecker: `var locale = require("locale");`  works in apps! This is not the problem...

**Comment by gfwilliams** [comment]
Thanks - I just fixed the `locale` app to just add `var` so it defines a local variable. I'd changed `mclock` from locales->locale and so had broken it, and not tested with a custom locale installed :)

This looks great - thanks!

**Comment by MaBecker** [comment]
@DerGuteWolf:  Thanks for adding the  language specific part.

**Pull request merged**
