### PR TITLE
Make the alarm scheduling more reliable

### PR DESCRIPTION
**Pull request by m0n5t3r**
Fixes https://github.com/espruino/BangleApps/issues/433: instead of only selecting the alarms that didn't already run during the current day for scheduling, get all active alarms, sort accordingly and add 24h to the timer if the alarm already ran.

### CODE REVIEW

**Comment by m0n5t3r** [comment]
should I do the version bump in here, or is it handled somewhere else / automatically?

**Comment by gfwilliams** [comment]
Great, thanks! So the issue was when scheduling an alarm for tomorrow, today?

If you could bump the version in apps.json and add a note to ChangeLog that'd be great: https://www.espruino.com/Bangle.js+App+Loader#making-changes

I'm afraid it's not handled automatically :)

**Comment by m0n5t3r** [comment]
done; would an auto-snooze function be considered useful? (as in, if there is no reaction to the first round of buzzing, schedule another round in 10 minutes...)

**Comment by m0n5t3r** [comment]
The issue was that when you set up an alarm for the first time, `.last` is 0, the bootloader code would select it and schedule it somewhat correctly (`t` would be negative, get reset to 1s, so it would check every second until midnight, when it would finally schedule the run for the alarm time - I just pushed a commit to address this as well)

However, after the alarm runs and you dismiss it, `.last` becomes equal to the current day, and the bootloader code would just skip it and not schedule the next run unless something else happened to trigger a `load()` after midnight (say, restless user fidgetting with the watch instead of sleeping? :grin: )

**Comment by gfwilliams** [comment]
Great, thanks! I'm not so sure about the auto-snooze. We could add it but I think it'd be good as an option rather than the default...

**Pull request merged**
