### PR TITLE
update submodule core

### PR DESCRIPTION
**Pull request by BartS23**
Fixes https://github.com/espruino/EspruinoAppLoaderCore/pull/45#issuecomment-1375717724

### CODE REVIEW

**Comment by thyttan** [comment]
I think it would be practical to have the apps be hidden in a drop down, like so:

<tr><td><b>Apps Installed</b></td><details><summary>Drop down</summary><td>

> kbmulti (0.05)
> widbthide (0.01)
> widram (0.03)
> calculator (0.07)
> activityreminder (0.10)
> pomoplus (0.05)
> widanclk (0.02)
> kbtouch (0.02)
> run (0.14)
> heartzone (0.01)
> wohrm (0.09)
> sevenmin (0.01)
> banglexercise (0.03)
> sleeplog (0.12)
> swp2clk (0.04)
> torch (0.11)
> hrm (0.11)
> lightswitch (0.06)
> boot (0.55)
> recorder (0.20)
> spotrem (0.07)
> podadrem (0.07)
> sleepphasealarm (0.12)
> annoy (0.01)
> messages (0.58)
> widmsggrid (0.04)
> messageicons (0.03)
> messagesmusic (0.05)
> slopeclock (0.04)
> tetris (0.01)
> smpltmr (0.07)
> weather (0.23)
> circlesclock (0.23)
> alarm (0.37)
> android (0.20)
> setting (0.56)
> dragboard (0.07)
> aiclock (0.07)
> widminbat (0.02)
> notify (0.12)
> quicklaunch (0.08)
> taglaunch (0.02)
> altimeter (0.02)
> messagelist (0.02)
> dtlaunch (0.22)
> sched (0.19)
> swscroll (0.02)
> fastload (0.03)
> health (0.21)
> bwclk (0.29)

</details></tr>


So modifying line 1053 maybe like this:
```<tr><td><b>Apps Installed</b></td><details><summary>Drop down</summary><td>${(device.appsInstalled || []).map(a => `${a.id} (${a.version})`).join(", ")}</td></details></tr>```

(I'm no expert on this, I could be suggesting something wrong. Just tested it here in this comment and saw that the formatting seems to work)

**Comment by BartS23** [comment]
Yes, that would be cool. 
The problem is that the form is automatically generated by github. I don't know any way to change the form.

We can only modify the template: https://github.com/espruino/BangleApps/blob/master/.github/ISSUE_TEMPLATE/bangle-bug-report-custom-form.yaml

It is possible to add a dropdown here. But this can then no longer be filled in automatically.

See also: https://forum.espruino.com/conversations/382404/

**Comment by gfwilliams** [comment]
Thanks! Sorry - I thought this had already gone in :)

**Comment by thyttan** [comment]
Could it be done by changing line 1293 to something like:

```
const apps = "<tr><details><summary><b>Installed apps</b></summary><td>
" + "\n" + (device.appsInstalled || []).map(a => `${a.id} (${a.version})`).join("\n") + "</details></tr>";
```

?

**Comment by BartS23** [comment]
@thyttan Thanks for the hint. I was not aware that Github forms supports Markdown in the text fields.

I have provided a new version at https://barts23.github.io/BangleApps/.
Could you please test it. The link goes into my own fork at the moment, so you can also create an issue :)
New issues will look like this: https://github.com/BartS23/BangleApps/issues/17

@gfwilliams could you please have a look too

**Pull request merged**
