### PR TITLE
Fixed the date

### PR DESCRIPTION
**Pull request by elykittytee**
- used `date_utils`
- replaced "second interval" with `queueDraw()`

### CODE REVIEW

**Comment by elykittytee** [comment]
also fixed the date for pokeclk to save battery life

**Comment by gfwilliams** [comment]
Great - thanks! Please could you bump the version numbers in those two apps and add a line to the ChangeLog as well?

**Comment by elykittytee** [comment]
Accidentally proposed changes to main instead of editing my fork.
My fork has all changelog and version numbers.

**Comment by gfwilliams** [comment]
Looks great - thanks!

**Pull request merged**
