### PR TITLE
Adding GadgetBridge weather to the LCARS watchface

### PR DESCRIPTION
**Pull request by BartokW**

### CODE REVIEW

**Comment by peerdavid** [comment]
Nice idea! I also used version 0.10 in my latest PR. Should I change it to 0.11 @gfwilliams to keep everything clean - otherwise 0.10 is shown 2 times in the changelog...

**Comment by BartokW** [comment]
@peerdavid I just updated to 0.11 for this change. If there's any other updates to it that you think should be there, feel free to either make the changes, or let me know.

**Comment by peerdavid** [comment]
Thanks a lot!

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
