### PR TITLE
[BW Clock] Add fastloading

### PR DESCRIPTION
**Pull request by thyttan**
RAM leaks gone thanks to @BartS23, thanks!

Bug #2361 will not be fixed with this PR.

### CODE REVIEW

**Comment by thyttan** [comment]
Hmm, I've tried to get this working but can't seem to do do it. If anyone has an idea what I might be missing please say :)

**Comment by BartS23** [comment]
@thyttan it is the Kill handler.

If you replace Line 445-451 
```
E.on("kill", function(){
  try{
    storage.write(SETTINGS_FILE, settings);
  } catch(ex){
    // If this fails, we still kill the app...
  }
});
```

with 
```
let save = () =>  storage.write(SETTINGS_FILE, settings);
E.on("kill", save);
```

and then add in the remove method:
```
      // save settings
      save();
      E.removeListener("kill", save);
```

**Comment by thyttan** [comment]
Thank you @BartS23! That did it :)

**Comment by gfwilliams** [comment]
Looks great - thanks!

**Pull request merged**
