### PR TITLE
Created ISO Clock Face

### PR DESCRIPTION
**Pull request by Fscked-In-The-Head**

### CODE REVIEW

**Comment by Fscked-In-The-Head** [comment]
Also added decrement and touch functions to counter.js. Sorry, I think these could have been done separately. I'm a github noob.

**Comment by gfwilliams** [comment]
Cool, thanks! If you change an existing app it's good to add something to the Changelog and bump the version number so folks know they can upgrade - but I'll do that for you now

**Comment by Fscked-In-The-Head** [comment]
Will do, thank you! This is the first time I've contributed to a public codebase, I'm still getting the hang of things.

**Comment by gfwilliams** [comment]
Well, thanks for making your first contribution here! I wouldn't have guessed it was your first PR :)

**Pull request merged**
