### PR TITLE
[gpsnav] Corrections wpindex=0, draw + nm calc for b2

### PR DESCRIPTION
**Pull request by storm64**

### CODE REVIEW

**Comment by nxdefiant** [comment]
Does waypointer need the same fix?

**Comment by storm64** [comment]
Just looked into waypointer, yes in deed, I will add this fix too.

**Comment by gfwilliams** [comment]
Thanks! Please could you bump the waypointer version too so that folks know they can get an update?

**Comment by storm64** [comment]
> bump the waypointer version
Oops, forgot about it.
Done.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
