### PR TITLE
iconlaunch - Directly eval apps instead of loading them

### PR DESCRIPTION
**Pull request by halemmerich**

### CODE REVIEW

**Comment by gfwilliams** [comment]
I'm really not sure this is a good idea (at least as a default)... For instance if you load any app that doesn't load widgets, widgets will stay loaded and it'll break.

Do you think you could make it an option?

**Comment by halemmerich** [comment]
Thats a valid point. I had looked at this from the standpoint of using the upcoming hidable widget bar. But I see how it would cause problems in the current state of things. Option it is.

**Comment by halemmerich** [comment]
Direct eval is now an non-default option.

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
