### PR TITLE
[messageicons] Add Jira icon + color

### PR DESCRIPTION
**Pull request by m-p-3**
Add an icon for Jira software notifications.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks but did this work when you tested it?

I think you also need to add it to https://github.com/espruino/BangleApps/blob/5a2597ae5c03a34f50b344dad7dcd4d9944e2169/apps/messageicons/icons/icon_names.json and to re-run the script which regenerates the icons file

**Comment by m-p-3** [comment]
I wasn't aware of the `icon_names.json` file, I'll fix that today.

**Comment by m-p-3** [comment]
Now I'm not exactly sure how to run the generate.js file to get the updated version, I tried running the code on my Ubuntu (Windows Subsystem for Linux) with NodeJS installed but I haven't figured it all out. I'll try to get that done tonight.

**Comment by gfwilliams** [comment]
Thanks - I'll just run it here after merging

**Comment by m-p-3** [comment]
Thank you! I'll figure it out in my end and make sure I can do it next time.

**Pull request merged**
