### PR TITLE
Improved dozenal watch face

### PR DESCRIPTION
**Pull request by numerist**
Novice here; haven't found the change log yet to update it. Changes:
-- extraneous comments and code removed
-- display improved
-- now supports Adjust Clock widget, if installed

### CODE REVIEW

**Comment by numerist** [comment]
Not understanding the conflicts; just trying to update apps/doztime2/app.js

**Comment by numerist** [comment]
It's app-bangle2.js that needs the changes.

**Comment by gfwilliams** [comment]
I think the issue may be that I don't think `apps/doztime2` exists in the main repository. I'm pretty sure last time you submitted, you'd made that a copy of `apps/doztime`, so we decided to merge the two together so there was one app, but that just had one file for Bangle.js 1 and one for 2.

It might be worth trying to get your repository to be exactly the same as the main one (even if that means removing and re-adding it from GitHub) and I think things will be a lot easier then. I'll try and make your changes here though.

**Comment by gfwilliams** [comment]
Just merged manually

**Pull request closed without merging**
