### PR TITLE
App Manager Sorting: use less memory

### PR DESCRIPTION
**Pull request by jl-cs**
@gfwilliams I've updated the app by your suggestion, here's the pull request. Thanks again!

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! Did this work ok?

I'd posted up the code but I didn't actually test myself :)

**Comment by jl-cs** [comment]
Yes, it helps a bit. I've tested a it and now one has to try a little harder to get the memory warnings, but you can still get them. It's almost certain you get them when you sort ASC/DESC in succession a couple of times (3-4x) and then try to enter the "Sort: manually" sub-menu. Then there will almost always be the memory/low memory warning. Maybe it's possible to alleviate this be clearing/garbage collecting the memory when navigating back in the sub-menus, but I'm not sure.
(It also could just be me or my Bangle.js, see my question [here](https://github.com/espruino/BangleApps/issues/381#issuecomment-626365278).)
Since I'm not very used to programming as "close" to the hardware as with the Bangle.js, I don't quite understand why i. e. the garbage collector seems not to be helping here.
But maybe you could point me in a direction here to understand it better or provide a spot in the documentation where I could look to try to improve it even more.

**Comment by gfwilliams** [comment]
Ok, thanks! The biggest issue with this kind of stuff is usually having a reference to old data hanging around - either via a variable, or with a function closure.

One big issue in settings was setting a menu item with `menu["foo"] = newMenu` - which cased newMenu to be called with an argument which was the old menu - and *that* meant there was a reference to it hanging around. I don;t think that's an issue here though

Looking at the source there's actually a global `m` variable that doesn't need to be there. I'll merge your changes and remove that  now, and that should help a lot.

**Comment by jl-cs** [comment]
Thank you very much!

**Comment by jl-cs** [comment]
Another short question: I've added to the changelog, but it doesn't show the new version number in the App Launcher at https://espruino.github.io/BangleApps/
I assume there has to be a value that has to be changed somewhere to make that happen, but I didn't see one in the App Manager folder in the repo.

**Comment by gfwilliams** [comment]
Ok, just made some changes, but there's still some kind of issue. Actually just tracked this down to a firmware bug - `writeJSON` had a memory leak. I'll fix it now, but it'd need a new firmware update to work properly.

> I assume there has to be a value that has to be changed

Yep, it's in `apps.json` - we have to have it in a central place so the App Loader doesn't have to load all 100+ files each time it starts :)

**Comment by jl-cs** [comment]
Thanks for the info.

Is there a schedule for when new firmware updates get released or is it done if you've got time? Not trying to pushy here, just curious. ;-)

**Comment by gfwilliams** [comment]
The 'cutting edge' firmwares are built automatically every time there's a fix.

The 'official' releases are basically when I have time and when I think it'd stable!

**Pull request merged**
