### PR TITLE
health: calculate distance from steps & introduce myprofile

### PR DESCRIPTION
**Pull request by nxdefiant**
- Adds myprofile to set various personal settings

Health:
- new submenu distance: multiplies step counts with stride length
- distance menu under step counting is only available if stride length is
    set in new app myprofile

### CODE REVIEW

**Comment by pavelmachek** [comment]
Should we make step length global setting? At least "pebble clock with distance" and "sixths" depend on that value already.

**Comment by nxdefiant** [comment]
ok, I was not aware of that, this brings back [the "My Profile" idea](https://forum.espruino.com/conversations/391660/#comment17193275).

@hughbarney How far are you with this?

**Comment by nxdefiant** [comment]
> [thyttan](https://github.com/thyttan) marked this pull request as ready for review [1 hour ago](https://github.com/espruino/BangleApps/pull/3120#event-11143151206)

uhm why?

**Comment by thyttan** [comment]
Sorry, don't know how that happened!

**Comment by nxdefiant** [comment]
I have added an initial version of "myprofile" to store personal data and use that instead.

**Comment by nxdefiant** [comment]
I'm done for now.

**Comment by nxdefiant** [comment]
Since "health" is installed by default I assume @gfwilliams  wants to review this personally.

**Comment by gfwilliams** [comment]
This looks great! Thanks for your work on this!

I guess at some point in the future we could have an `interface.html` so it can be set from the app loader too, but this seems great for now.

... also moving `step goal` into this app would be great! It's currently in the health app (but also some pedometers) I think and would be really good to move to one place.

Merging now...

**Pull request merged**
