### PR TITLE
Add http-server dependency

### PR DESCRIPTION
**Pull request by atjn**
Otherwise the `local` and `start` npm scripts do not work :)

### CODE REVIEW

**Comment by bobrippling** [comment]
Sounds good, cc'ing @gfwilliams with it being a central change

**Comment by gfwilliams** [comment]
Thanks, yes, this is fine - although I do like to try and keep the dependencies as low as possible usually.

I'd be interested to know how much `local/start` commands are used though - it's something that was contributed but that I don't think was ever documented anywhere.

**Comment by atjn** [comment]
I looked at [`testing`](https://github.com/espruino/BangleApps?tab=readme-ov-file#testing) and found both the online and offline options to be very complicated for me. I already have the code open in an editor, so it is every easy to run `npm install && npm run local`.

**Comment by nxdefiant** [comment]
Fun, I did not knew the `npm run local`, I always did  `npm start` instead

**Pull request merged**
