### PR TITLE
Casio Logo Widget

### PR DESCRIPTION
**Pull request by VitaliiTsilnyk**
A simple widget that displays Casio logo when clock screen is active.

Looks nice in combination with the LCD Clock / LCD Clock Plus.

### CODE REVIEW

**Comment by bobrippling** [comment]
Nice! Out of interest, how does this look with the light theme?

**Comment by VitaliiTsilnyk** [comment]
Good question. I only tested it with LCD Clock (which overrides the theme with its own) before submitting the PR. Just tested it with Anton Clock and it basically disappears since it's hardcoded to be white.

**Comment by gfwilliams** [comment]
Thanks! As @bobrippling says, it wouldn't work - but it's the image itself is 1 bit so Espruino will automatically choose the right theme - all that's needed is to remove setColor (which I have just done)

**Comment by VitaliiTsilnyk** [comment]
Just custom themes, with red foreground for example, etc. Making the logo the same color as the other text looks off.
image image

Looks much better when it's white (more like silver in real life) or black.
image image
Looks like an actual logo that's not part of the watch screen.

**Comment by gfwilliams** [comment]
Ok, I just put a change in. I've just not seen people using themes like that normally...

**Pull request merged**
