### PR TITLE
MarioClock [Enhancement] - Nightmode + 3 levels of darkness + Settings persisted + New info banner messages

### PR DESCRIPTION
**Pull request by paulcockrell**
# Changes
* In night mode, further left swipes reduce the screen brightness (3 levels) until returning to day-mode
* Persist and load user settings
* Display info banner message when phone connects/disconnects
* Display info banner message when phone battery <= 10% (checks every 10 mins) along with character speech low-battery bubble.

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
I love the MarioClock. Would it be possible for night mode and character to be saved, so that the watch face stays with the same setup if you leave the clock and come back?

**Comment by paulcockrell** [comment]
Hi @Didgeridoohan sure thats a great idea, ill take a look at implementing this later today.

**Comment by paulcockrell** [comment]
@Didgeridoohan Actually I have done your change request in this PR :-)

**Comment by Didgeridoohan** [comment]
Yay! Thank you.

**Pull request merged**
