### PR TITLE
Remove custom boolean formatters

### PR DESCRIPTION
**Pull request by alessandrococco**
This PR removes the 99% of the Yes/No, On/Off, etc.  custom boolean formatters.

See https://github.com/espruino/BangleApps/pull/1750#issuecomment-1157382452

### CODE REVIEW

**Comment by Stiralbios** [comment]
Can you revert the change for  TerminalClock. I think it will create conflicts with #1979  ?
I saw your replaced `+ " min"` per + "m" too. The value displayed will be different then no ?

**Comment by alessandrococco** [comment]
> Can you revert the change for TerminalClock ? I think it will create conflicts with #1979 ? 

Sure! Sorry, I didn't notice your PR 😅 

> I saw your replaced `+ " min"` per `+ "m"` too. The value displayed will be different then no ?

Yes, I noticed that many apps use "m" to abbreviate min/minutes in the settings menu.

I just reverted all the changes to TerminalClock ;-)

**Comment by Stiralbios** [comment]
Ok thanks. No problem ;)

I didn't notice the "m" thing on other apps before. I made the change to use the default boolean on my pull request and use "m" instead of " min" in the setting.

**Comment by gfwilliams** [comment]
Great - thanks for this!

**Pull request merged**
