### PR TITLE
[draguboard] Create draguboard app from dragboard

### PR DESCRIPTION
**Pull request by lauzonhomeschool**
By using a bigger part of the touch area (vs the original dragboard), we can have bigger and more distanced characters to improve accuracy.

### CODE REVIEW

**Comment by thyttan** [comment]
Cool!

**Comment by thyttan** [comment]
The UI is drawn like this for me:

image

**Comment by lauzonhomeschool** [comment]
That's weird.  What's your firmware version?  Mine is 2v16.7.  Do you see the original dragboard normally?

**Comment by lauzonhomeschool** [comment]
Seems appRect is not initialized at the same time depending on the params, I'll rework it.  Thanks for testing.

**Pull request closed without merging**
