### PR TITLE
Data files

### PR DESCRIPTION
**Pull request by rigrig**
Fix for #243

Adds a "data" section to apps.json, with data files to clean on uninstall   
These are added to `appid.info` as "dataFiles" or "storageFiles", and can contain wildcards.
If an app contains `<appid>.settings.js` and no "data" section, it is assumed to store its settings in `<appid>.settings.json`. So if all you want to do is save settings, you don't need to worry about adding a "data" section.

Also added commit to use this for the `gpsrec` app, as it seemed a good example app with pretty much every feature:
```json
"data": [
  {"name": "gpsrec.json"},
  {"wildcard": ".gpsrc?", "storageFile": true}
]
```
Which becomes this in `gpsrec.info`:
```json
,"dataFiles":"gpsrec.json","storageFiles":".gpsrc?"}
```
I made sanitycheck `WARN` if a wildcard pattern does not contain the appid, but that means it now complains about `gpsrec` :-(

Apps need to declare data files with "name" or "wildcard", and `sanitycheck` complains if you get it wrong. Both types are lumped together as-is in `<appid>.info` though, and removeApp simply checks if a filename contains `?` or `*` to decide how to handle it. (It could just handle all files as wildcards, but this seems cleaner and saves having to do `Storage.list()`)

the code handles storageFile wildcards by doing basically 
`Storage.list(/filename\u0001/).map(f => f.substr(0, f.length-1))`
 I don't think there is a nicer way to find those?

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - this looks really neat!

Only minor thing I'd say is could we change `dataFiles/storageFiles` to just `data/storage` or something shorter?

Seems stupid I know but as the app JSON for all apps is loaded into memory for the launcher/bootloader, anything we can do to avoid it using up more RAM seems like it'd be good.

**Comment by rigrig** [comment]
I thought about naming it that, but I'm worried it would confuse things: `app.storage` would have different meanings depending on whether it came from `apps.json` or `<appid.info>`. I'll try to come up with some shorter names though.

**Comment by rigrig** [comment]
Instead of separate `dataFiles` and `storagefiles`, I figured I could just put them together in a single `data` property, so you get e.g. `"data":"gpsrec.json;.gpsrc?"`
Right now it's separating regular and storageFiles with a semicolon, I was wondering if there are any characters which are forbidden from showing up in filenames? I'd prefer to use one of those then.
(I looked around a bit, but couldn't find any. If not maybe we could at least make sanitycheck complain about weird characters?)

Also, what would be the most convenient way to adjust existing apps? Add the changes to this PR, or one big new PR, or separate PRs for every app?

**Comment by gfwilliams** [comment]
Thanks - this looks really neat - I'm a bit unsure about hard-coding settings but I guess it makes sense, especially to force use of the same filename.

Maybe we should have a quick think about the filename though. I think stuff I've made just uses `myapp.json` for settings so that should change, but I wonder whether `.settings.json` is a bit long given we only have 28 chars for the filename? Maybe just `.settings`?

There aren't any disallowed characters in filenames (apart from `\0`, but it seems pretty unfriendly). Please could we just use comma? That's what we currently use for the `files` list so I think it makes sense to use the same for `data`. It'd be great to make `sanitycheck` check filenames in `storage` for a comma though.

Am I right in thinking this PR would be totally fine being merged without app changes? If so I'd do that and then modify the apps in a separate PR

**Comment by rigrig** [comment]
I figured most apps would just have the one settings file, and it would keep `apps.json` a bit cleaner if they don't all need to add a boilerplate `"data":[{"name":"myapp.json"}]`.  But leaving the hard-coded bit out would uncomplicate things, and it would be clearer from `apps.json` which apps actually use data files.
Probably best to leave out hard-coded "magic".

`myapp.json` does look like a better name, and it might contain non-settings data. I think I'll make `sanitycheck.js` suggest that.

> Please could we just use comma?

The way I did it now it needs two characters:
- comma between filenames
- semicolon between regular files and storageFiles

App with only regular files: `"data":"file1,file2"`
App with only storageFiles: `"data":";storageFile1,storageFile2"`
App with both: `"data":"file1,file2;storageFile1,storageFile2"`
So for `gpsrec` that turns into `"data":"gpsrec.json;.gpsrc?"` because it uses one regular file and one storageFile wildcard.

**Comment by gfwilliams** [comment]
Ahh, gotcha. Sorry, I didn't read your post properly - yes, semicolon seems pretty sensible then.

And yes, I think probably removing the hard-coded is better - as you say it makes it more obvious if settings files are produced.

thanks!

**Comment by gfwilliams** [comment]
This looks great - thanks for all the work you've put into this!

**Pull request merged**
