### PR TITLE
Chance

### PR DESCRIPTION
**Pull request by Mcsquarex**
Toss a coin just touch the screen  
If you click in the dice button change to roll mode

Roll the dice just touch the screen  
If you click in the coin button change to toss mode

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! This looks great - really nicely designed!

**Comment by Mcsquarex** [comment]
> Thanks! This looks great - really nicely designed!

The app is not yet on banglejs.com/apps is there any waiting time for it to be seen on the page? I await your comments, thanks.

**Comment by gfwilliams** [comment]
Hi - yes, I only update that about once a week. It'll be on the development app loader though: https://espruino.github.io/BangleApps/?id=chance

**Comment by Mcsquarex** [comment]
> Hi - yes, I only update that about once a week. It'll be on the development app loader though: https://espruino.github.io/BangleApps/?id=chance

Ok thanks, Best regards!

**Pull request merged**
