### PR TITLE
+settings for UI, less IO r/w, rm timeout from eval

### PR DESCRIPTION
**Pull request by stweedo**
Still has comm issues sometimes. I haven't looked into it too much yet since it still mostly works. Last I saw it was getting stuck between comms.js and puck.js

### CODE REVIEW

**Comment by stweedo** [comment]
I have lots of new improvements made, just doing some final touches on them. I also removed the timeout for `Puck.eval` but now I need to handle switching to defaults differently. I think besides the communications issues I might have everything full functional (latest bug was leading zero state not reading correctly because of some state save logic that wasn't being set).

I don't see how to convert this pull request to a draft.

**Comment by gfwilliams** [comment]
Top right under 'Reviewers'? At least i see it - I'll do it for you now anyway

**Comment by stweedo** [comment]
Just committed the final touches. Seems nice and stable and fast. Let me know what you think. Thanks!

**Comment by gfwilliams** [comment]
Don't have time to look into it too deeply, but it looks good - merging now!

**Pull request merged**
