### PR TITLE
Update of lap log feature stopwatch app 

### PR DESCRIPTION
**Pull request by Red-The-Hunter**
- made lap logs count up from 1
- made it such that logs scroll to next column after 18th entry
- can now display 36 entries without going off-screen

### CODE REVIEW

**Comment by Red-The-Hunter** [comment]
screenshot (1)
screenshot (2)
screenshot

**Comment by Red-The-Hunter** [comment]
To Do (V0.03)
Remove lap function for BN3 when timer is stopped
Add Save Lap log to file for BN3 when timer is stopped

**Comment by gfwilliams** [comment]
Nice - save laps sounds like a great idea!

**Comment by Red-The-Hunter** [comment]
V0.03
- Remove lap function for BN3 when timer is stopped
- Add Save Lap log to file for BN3 when timer is stopped (Saves as StpWch-[DATE TIME]

**Comment by Red-The-Hunter** [comment]
Screenshot is from Web IDE
screenshot (4)

Because Web IDE cannot use the storage functions, these are files generated by my own watch, thus different amount of entries/different timings
Capture
Capture2

**Comment by Red-The-Hunter** [comment]
Realised something... I should swap BN1 and BN3 because BN3 is used to exit applications...

**Comment by Red-The-Hunter** [comment]
screenshot (5)
screenshot (6)
Swapped functions of BN1 and BN3 so long-pressing BN3 to exit would not save the lap log.
It is fine if the stopwatch resets upon BN 3 press as stopwatch app is being exited.

**Comment by Red-The-Hunter** [comment]
To-Do (V0.04)
- Add total time elapsed counter
- Contemplate if total time elapsed should be main counter displayed or lap time should be main display

**Comment by gfwilliams** [comment]
This is great - thanks! I'll add a tutorial soon on making an `interface.html` so there can be a nice way to load the lap times

**Pull request merged**
