### PR TITLE
sleepphasealarm: Fix json dates

### PR DESCRIPTION
**Pull request by nxdefiant**
Fix handle dates saved as object with milliseconds

see https://forum.espruino.com/comments/17322019/

### CODE REVIEW

**Comment by thyttan** [comment]
I'm unsure how this will play with https://github.com/espruino/Espruino/commit/805c317d67ac9d73bd1bcbf017ed521b941a3586 ?

**Comment by nxdefiant** [comment]
Date.toISOString() is the old behaviour restored. The ternary should handle both variants `new Date(typeof o === 'string' ? o : o.ms)`

**Comment by nxdefiant** [comment]
Yes, sleep phases recorded with these firmware versions have the other data format saved in storage.

**Comment by thyttan** [comment]
Ok - thanks for the fix and clarifications! 🙂

**Pull request merged**
