### PR TITLE
Widbgjs update to 0.02

### PR DESCRIPTION
**Pull request by phrogg**
Fixed wrong filename in settings.

### CODE REVIEW

**Comment by nxdefiant** [comment]
You also need to update the version in metadata.json

**Comment by phrogg** [comment]
> You also need to update the version in metadata.json

Thanks for the hint. Done.

**Comment by phrogg** [comment]
There still seems to be an issue i will be closing this for now. Sorry.

**Comment by phrogg** [comment]
Works now :)

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
