### PR TITLE
added Back translation

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - has this actually been tested? It seems like in most cases the text is `> Back` and so the translation as-is may not work?

**Comment by matjaz** [comment]
yeah. The idea is to explicitly call `locale.translate()`.
Actually, what if `E.showMenu()` would call it implicitly? and an option so app can extend locale.trans.

**Comment by gfwilliams** [comment]
> Actually, what if E.showMenu() would call it implicitly?

That's what it does (and showMessage/etc). That's the whole point really - that apps don't generally need to be written with it in mind: https://github.com/espruino/Espruino/blob/master/libs/js/banglejs/E_showMenu.js#L57

**Comment by gfwilliams** [comment]
So was this tested at all? Literally the *only* app I see the string `Back` in is the GPS recorder. None of the others will work

**Comment by matjaz** [comment]
no. I'll open new PR if you don't mind.

**Pull request closed without merging**
