### PR TITLE
gpstrek - Adds zoomable map view of loaded route

### PR DESCRIPTION
**Pull request by halemmerich**
- Adds the new map and overview screen
- Allows uploading route as GPX via interface.html (OsmAnd exports work fine)
- Cleans up some of the older code

screenMap
screenOverviewScroll

TODO:

- [x] Fix touch listener handling events for the widget bar
- [x] Tweak performance a bit more
- [x] Update README with new features
- [x] Render route chunks in timeouts to keep app responsive for long routes
- [x] Fix position marker placement relative to route
- [x] Sort files in route menu by name
- [x] Fix route mirroring for map display
- [x] Fix auto search not refreshing the map display
- [x] Catch no filename set case before uploading in interface.html
- [x] Fix waypoint search for mirrored route
- [x] Fix auto search being to slow if moving faster than walking spead with waypoint dense routes
- [x] Rework UI to be consistent for map and slice view
- [x] Check if state should actually be cleared on each app restart
- [x] Update screenshots for new map UI

Sneak preview on my apploader: [https://halemmerich.github.io/BangleApps/?id=gpstrek](https://halemmerich.github.io/BangleApps/?id=gpstrek)

### CODE REVIEW

**Comment by halemmerich** [comment]
@gfwilliams The apploader view in Bangle.js GadgetBridge does not seem to allow opening a file chooser. Is this known/wanted behaviour or caused by my ancient Android version (Android 8.1, deactivated Play services)? Chromium 108 installed from [https://github.com/bromite/chromium/releases](https://github.com/bromite/chromium/releases) works on the same phone. x86 desktop chromium under linux works as well.

**Comment by gfwilliams** [comment]
This looks neat - it'll be great when it's ready to merge

> The apploader view in Bangle.js GadgetBridge does not seem to allow opening a file chooser. Is this known/wanted behaviour

Yes - it's a known issue, and not related to your phone. I've just tried to put some changes in to fix it at https://codeberg.org/gfwilliams/Gadgetbridge/commit/8e7bfa1e9115c69ee2d9fa0b86859f37681db925

**Comment by halemmerich** [comment]
Great, thanks :) That will up the convenience of using this a lot.

**Comment by halemmerich** [comment]
> I've just tried to put some changes in to fix it 

Can confirm it mostly works in current nightly. The filename is not set correctly automatically in my interface.html, but I did not yet investigate why that is. Manually setting a file name and then uploading works fine.

**Comment by halemmerich** [comment]
This should now be fine for merging.

**Pull request merged**
