### PR TITLE
gipy: new release with bugfixes

### PR DESCRIPTION
**Pull request by wagnerf42**
hi, i did a few bugfixes in the maps creations and display.

it should be much better now. some bugs only happened in the interface and not in my offline code so i did not see it immediately.

### CODE REVIEW

**Comment by nxdefiant** [comment]
Can I report a bug here? The attached .gpx-file with a route randomly placed west of london fails on the official and [your apploader](https://wagnerf42.github.io/BangleApps/):
[testgpx.zip](https://github.com/espruino/BangleApps/files/11925258/testgpx.zip)

If I replace the negative longitude values with positive ones the gpx-file passes.

**Comment by wagnerf42** [comment]
hum, i'm not shocked by this one. i need to look at it in details. i'll take a look tomorrow.

thanks for the report

**Comment by gfwilliams** [comment]
Is it worth me waiting to merge this until you've had a chance to look at that issue?

**Comment by wagnerf42** [comment]
i would better merge now and already fix the ongoing issues which are affecting everyone. my work schedule is a bit busy right now so i'm not sure when i'll fix the other one.

**Comment by gfwilliams** [comment]
No problem - thanks!

**Comment by wagnerf42** [comment]
@nxdefiant hey, i think i fixed the negative coordinates bug.
i'll do a bit of tests before releasing again but you can give it a try here : https://wagnerf42.github.io/BangleApps/

thanks for the report

**Comment by nxdefiant** [comment]
Cool, I'm going to test it, thx.

Looks like it also gets the option to traverse a track backwards, that was on my wishlist.

Also on my wishlist is an option to disable buzzing ;)

**Comment by nxdefiant** [comment]
@wagnerf42 testet with a 20km route in Brittany, all good. Thanks/Merci.

**Pull request merged**
