### PR TITLE
Ratchet launch: add caching

### PR DESCRIPTION
**Pull request by bobrippling**
@jsphpl hope this is ok - I've added app caching (taken from the launcher app) to the ratcher launcher

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great, thanks! Please can you bump the version?

**Comment by jsphpl** [comment]
@bobrippling cool, thank you! No need to ask - seems like this apps repository is a doocracy.

**Comment by bobrippling** [comment]
Sounds grand, thanks!

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
