### PR TITLE
Created a vertical watch face

### PR DESCRIPTION
**Pull request by eaydev**
Upgraded vertical watch face with heart rate monitor and battery

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks good - are you ready to merge?

**Comment by eaydev** [comment]
Yes

**Comment by gfwilliams** [comment]
Is it ready now?

**Comment by eaydev** [comment]
the basic watch features are ready and the HRM too. The only thing that is yet to work is the pedometer :)

**Comment by gfwilliams** [comment]
Thanks!

**Comment by MalteKiefer** [comment]
Question, what must I do to get the heart rate working?
Only see a dash "-" the hole time?

**Comment by eaydev** [comment]
I believe the code should indicate what button to press to activate the
heart monitor.

I'm on a long hiatus :)

**Comment by gfwilliams** [comment]
`BTN1` by the look of it - I've just changed the description to mention that

**Pull request merged**
