### PR TITLE
Powermanager - Fix wrapping

### PR DESCRIPTION
**Pull request by halemmerich**
* Fixes of by one error in indexing the arguments for the wrapped function. This causes the timeout to be given as first argument to functions instead of the actual first argument.
* Fixes widget drawing even if hidden

### CODE REVIEW

**Comment by nxdefiant** [comment]
Does that fix I can no longer edit alarms when logging is active?
> Uncaught TypeError: Expecting Object, got Number
 at line 26 col 213 in alarm.app.js
....assign(alarm,selectedAlarm);}var time=require("time_utils").de...
                                 ^
in function called from line 17 col 1948 in .boot0
....apply(undefined,arguments.slice(1));let end=Date.now()-start;let f=a.toSt...
                                            ^
in function called from system

Also I think that powermanager.default.json is missing in metadata.json.

**Comment by halemmerich** [comment]
The error message certainly matches the problem caused by the fix. So maybe to slightly probably :)

**Comment by nxdefiant** [comment]
Pasted the wrong file, it is "powermanager.json" that is missing in metadata.json.

**Comment by halemmerich** [comment]
@nxdefiant Found an additional problem with alarms: `Multi Timer` gives a string instead of a function to setTimeout when the timer has finished. This caused the timer to overflow and not raising an alarm. This is now worked around by not really wrapping those string functions.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
