### PR TITLE
new gpstrack app

### PR DESCRIPTION
**Pull request by jeffmer**
This app displays tracks recorded by gpsrec together with duration and distance on the bangle.js screen. It uses equirectangular projection which is accurate for small distances and faster than Mercator.

### CODE REVIEW

**Comment by jeffmer** [comment]
Screen shot of app:

**Comment by gfwilliams** [comment]
This looks great - thanks! Just before I merge, do you think this is something that might make sense being added to the GPS recorder app itself, since there is already a menu?

https://github.com/espruino/BangleApps/blob/master/apps/gpsrec/app.js

Up to you, but if you think it's a good idea then I'm happy to move your code over.

**Comment by jeffmer** [comment]
Yes, very happy for you to merge this with the GPS Recorder - please go ahead. It was easier to develop separately. 

Jeff

**Comment by gfwilliams** [comment]
Thanks! I just merged this in - it's really helpful!

**Pull request closed without merging**
