### PR TITLE
Update gpsnav app to 0.03 with waypoint editor

### PR DESCRIPTION
**Pull request by jeffmer**
This version has a waypoint editor that uses the interface mechanism. Consequently, it is invoked by clicking on the download data icon from app icon in the app loader. This is a little misleading as the waypoint editor both downloads and then updates the edited waypoints.json data to the Bangle.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Wow, nice - thanks!

This has come up before - it seems the 'interface' system itself works ok, but the icon/'download' name is wrong? I'm very happy to get that changed, but spectre's out of the box icons aren't that great: https://picturepan2.github.io/spectre/elements/icons.html

**Comment by jeffmer** [comment]
Yes, it’s the icon. What about using the same  ‘icon-menu’ used for the customised apps? It would not be confusing as it is in a different place and both actions result in interacting with a new pane/window.

**Comment by gfwilliams** [comment]
I guess... I bet people will still get confused :) What about icon-edit or icon-more-horiz?

**Comment by jeffmer** [comment]
Icon-edit is good for me, however, icon-more-horiz might be more general. Of course, it’s probably better to leave it as is - people do not like change:-)

**Pull request merged**
