### PR TITLE
imageclock - Fix the clock not refreshing completely after switch

### PR DESCRIPTION
**Pull request by halemmerich**
Clock did not refresh completely once after switching from launcher if the drawing in timeouts option in the customizer was deactivated.

### CODE REVIEW

**Comment by gfwilliams** [comment]
There's a warning from the CI check here:

```
Clock imageclock file calls loadWidgets before setUI (clock widget/etc won't be aware a clock app is running)
```

Is it possible to swap the call order around?

Also `if (!global.WIDGETS)` isn't required because loadWidgets is now smart enough to check

**Comment by halemmerich** [comment]
> Is it possible to swap the call order around?

Yes :)

**Comment by halemmerich** [comment]
I had to re-add a loading screen, since some watchfaces take a few hundred ms to load. If the button is pressed in that loading time the launcher would be loaded again without any indication what happened.
Double button press now effectively starts loading the clock and stops it again showing the loading screen for the time in between presses. At least it is still a few times faster than the normal way, which takes around 3 seconds on my daily driver bangle.
This iteration is now ready to merge :)

**Comment by gfwilliams** [comment]
Thanks! Maybe the double press needs some thought - although you'd hope that it should only take effect after setUI is called. Maybe the previous press gets queued as the device is busy - we could try and work around that by adding a setTimeout inside setUI

**Pull request merged**
