### PR TITLE
[Rebble Clock] various fixes

### PR DESCRIPTION
**Pull request by Rarder44**
- fix autoCycle
- removed unused font
- font reconverted and compressed with heatshrink

### CODE REVIEW

**Comment by Rarder44** [comment]
- imported suncalc and trimmed

**Comment by gfwilliams** [comment]
Looks good, but please could you tweak the changelog and version? Looks like 2 lines are deleted and the version has gone back by one!

**Comment by Rarder44** [comment]
by bad;
in the first two commits I increased the version (0.08 and 0.09) then I realized that it was useless to keep increasing it for each fix until the pull was finalized.
for this I then restored to 0.08 and merged the changelog lines.

**Comment by gfwilliams** [comment]
Ok, thanks - probably best in future to just keep bumping it though. This'll be a bit confusing to anyone that installed it from the dev app loader :)

**Comment by Rarder44** [comment]
ok, sorry!

**Pull request merged**
