### PR TITLE
messagesoverlay - Rendering and UI improvements

### PR DESCRIPTION
**Pull request by halemmerich**
* Renders short messages in big font and centered up to as many lines as fit
* Longer messages are all rendered in smaller font on all their pages to keep them consistent
* Adds Settings
* Messages can be cleared automatically when bangle is locked
* Adds visual indicator for multiple messages in queue

### CODE REVIEW

**Comment by thyttan** [comment]
How is the indicators for the messages queue supposed to work?

For me it works like this:
*# of messages* : *# of indication angles*
1:0
2:1
3:1
4:2
5:2
6:2
7:2

**Comment by halemmerich** [comment]
Yes, thats how it is implemented. The values are chosen pretty randomly, I just wanted to see at a glance roughly how many messages I can expect to be stacked. The messages are redrawn over the whole area so we could easily do one additional line per message up to a value.

**Comment by thyttan** [comment]
I notice that the watch screen will light up when I clear notifications on the phone. This is regardless of if I already cleared the message on the watch or not. I don't think this is intended?

I think ideally dismissing on the phone would never light up the watch screen, only clear the message if still shown.

**Comment by halemmerich** [comment]
Hm, I thought I fixed that behaviour. A quick test on my watch seems to work fine in that regard. It checks the message for the new property. Maybe that is not enough for all types of messages? I tested with Conversations.

**Comment by thyttan** [comment]
Maybe I'm not on your latest commit. Will try again

**Comment by thyttan** [comment]
Yes, sorry - you seem to have fixed it! :)

I'll merge now :+1: Thanks!

**Comment by thyttan** [comment]
@halemmerich 

Maybe we want to do something about these now that the lint exemption was removed. Sorry - didn't notice it before. 

```

/home/runner/work/BangleApps/BangleApps/apps/messagesoverlay/lib.js
Warning:   520:5   warning  'toRemove' is not defined  no-undef
Warning:   530:9   warning  'toRemove' is not defined  no-undef
Warning:   535:27  warning  'toRemove' is not defined  no-undef
Warning:   536:18  warning  'toRemove' is not defined  no-undef
Warning:   608:3   warning  'quiet' is not defined     no-undef
Warning:   674:3   warning  'bpp' is not defined       no-undef
Warning:   676:25  warning  'bpp' is not defined       no-undef
Warning:   676:45  warning  'bpp' is not defined       no-undef
Warning:   683:5   warning  'bpp' is not defined       no-undef
Warning:   701:63  warning  'bpp' is not defined       no-undef
Warning:   708:31  warning  'bpp' is not defined       no-undef
Warning:   709:50  warning  'bpp' is not defined       no-undef
Warning:   718:7   warning  'bpp' is not defined       no-undef
```

**Comment by halemmerich** [comment]
Yes, I overlook those regularly as well... Will do a patch for those as a new PR.

**Pull request merged**
