### PR TITLE
messagesoverlay - Use event based mechanism

### PR DESCRIPTION
**Pull request by halemmerich**
This uses the `messages` events instead of overloading the require function to get the messages.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! That looks mile better.

You happy with this or are you waiting to test it a bit more

**Comment by halemmerich** [comment]
It works fine in the sense that everything seems to work as before, but currently the unhandled messages (tested nav and music) seem to reach the original message ui code, but do not seem to be handled there. I do not know yet if the issue lies in `messagesoverlay` or `messagegui`.

**Comment by halemmerich** [comment]
Some further testing showed that handling the messages works fine, they just do not auto open on clock when using test messages, selecting them in the message list works fine. Testing with "real" navigation using OsmAnd seems to work fine, including auto opening on the clock.

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
