### PR TITLE
A Tea Timer application

### PR DESCRIPTION
**Pull request by vovcia-clug**
A Tea Timer application

### CODE REVIEW

**Comment by thyttan** [comment]
Hi - thanks for opening your first PR here :)

I'm going to check this out on my watch and come back. 

One thing we will probably want to work out before merging to the main repo here is adapt to using the scheduling library, found here: https://github.com/espruino/BangleApps/tree/master/apps/sched .

**Comment by vovcia-clug** [comment]
Hi @thyttan, we managed to refactor code to use sched api. Some functionality (backward ticking) is gone, but it's not a big deal.

**Comment by thyttan** [comment]
Sorry, I feel guilty now asking for that scheduler rewrite... I guess that is most important if you want the alarms to be able to run in the background, and this app didn't. On the other hand now the timer persists on exit and that differentiates it from [the other tea timer app](https://espruino.github.io/BangleApps/?id=teatimer) - so thanks! :)

Two suggestions if you want to work some more:
- the icon looks a little wonky on my watch:
image
- Maybe the visual countdown can be reinitialized on app launch if the timer is already running in the background?

Especially the icon would be nice to fix before merging - but if you want to do it in a version 2 that's alright as well! Just say and I'll merge.

I'm not sure what you mean with the following?
> Some functionality (backward ticking) is gone, but it's not a big deal.

The countdown starts ticking when starting the timer on my watch.

**Comment by vovcia-clug** [comment]
@thyttan Hi, I changed icon, added fix for restarting application while timer is running and made some minor fixes.

**Comment by thyttan** [comment]
Very nicely done 🙂👌I'll go ahead and merge. Thanks again! 🎉

**Pull request merged**
